### ISSUE TITLE
Icon/Logo request: FINOS CDM Logo + Colour schemes required for access via Rosetta

### ISSUE THREAD

**Issue by minesh-s-patel** [finos/common-domain-model#1961]
[Rosetta](https://rosetta-technology.io/) requires Logos, icons and colour schemes. Can you make this available in the github repo?

Thanks

**Comment by iansloyan** [comment]
Hey @minesh-s-patel - I have sent you the logos via email

**Comment by minesh-s-patel** [comment]
> Hey @minesh-s-patel - I have sent you the logos via email

Thanks. I have the icons - We can get [Rosetta](https://rosetta-technology.io/) updated to the new icons.

**Comment by maoo** [comment]
FYI - here's the logo on FINOS landscape - https://landscape.finos.org/logos/common-domain-model.svg
