### ISSUE TITLE
Update branding and website for CDM Documentation to FINOS

### ISSUE THREAD

**Issue by minesh-s-patel** [finos/common-domain-model#1967]
While the source documentation is already migrated to the FINOS repository, the CDM docs site is currently located at https://cdm.docs.rosetta-technology.io. These should be migrated to a standard FINOS URL. 

Tasks
- [ ] @minesh-s-patel submits some final bulk changes to the `documentation` folder
- [ ] @minesh-s-patel and team branch/fork out the main branch and convert the `documentation` folder (containing RST files) into `docs` (containing files in MD format)
- [x] @maoo and @TheJuanAndOnly99 contribute to the branch/fork by adding Docusaurus content to build the [project-blueprint web structure](https://project-blueprint.finos.org/) - see https://github.com/maoo/common-domain-model/tree/docusaurus-website and https://docusaurus-website--heroic-starburst-9c64f5.netlify.app/
- [ ] @maoo and @TheJuanAndOnly99 configure Netlify to publish the new website under cdm.finos.org
- [ ] @maoo @eteridvalishvili and @iansloyan create a new issue with a detailed plan to a) update the table of contents b) update branding if/where necessary and c) provide an onboarding experience to CDM for the main personas (decision maker, business analyst, developer, ...)

**Comment by minesh-s-patel** [comment]
From email chain:

All the CDM docs are in the common-domain-model repo and there is a docker file that builds it all. All content is in RST (not MD) but all migratable if we choose.

The tech used is [sphinx](https://www.sphinx-doc.org/en/master/) which is pretty standard.

See
https://github.com/finos/common-domain-model/tree/master/documentation

Docker file:
https://github.com/finos/common-domain-model/blob/master/documentation/Dockerfile

**Comment by minesh-s-patel** [comment]
@maoo 

I understand that the standard way to deploy docs at FINOS is to use [Netlify](https://www.netlify.com/). Can you point me to some docs where I can see how this is done?

**Comment by iansloyan** [comment]
Is this issue closed? I see the CDM documentation in a folder on finos/coomon-domain-model domain now?
