### ISSUE TITLE
March 14th - Common Domain Model Inaugural Meeting Minutes

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2011]
# **Common Domain Model**

## **Date**

March 14 2023 - 10am EST / 2pm GMT

## **Meeting notices**

* FINOS Project leads are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).
* All participants in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies).
* FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
* FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available. 

## **Agenda**
- [x] 1. Convene & roll call (5mins)
- [x] 2. Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [x] 3. Review Meeting Notices (see above)
- [x] 4. Introduction to the structure of the meetings 	
  - a. WGs Overview  

<img width="979" alt="Screen Shot 2023-03-08 at 4 05 33 PM" src="https://user-images.githubusercontent.com/117176765/223849865-bdcdf99b-2f99-4db0-8246-42da4b523ed7.png">

   **CDM Steering Working Group**
   https://github.com/finos/common-domain-model#2-working-groups

![ReleaseVersionApproval-initialsketch](https://user-images.githubusercontent.com/61597464/224986552-972eef67-9af7-4c51-8da8-3aa0930a953c.png)

  - b. How to join and participate in the meetings 

To stay up-to-date on all upcoming meetings, please refer to the [community calendar](https://www.finos.org/finos-community-calendar). Additionally, if you would like to be added to any recurring meetings, please send an email to help@finos.org.

  - c. Date, time and host of the meetings
- [x] 5. Upcoming Meetings
**Contribution Review WG**
Host Rotation: Gabriel Callsen/Tom Healey, Chris Rayner, Ian Sloyan/Ruddy Vincent
Date: 3/21/23 (Biweekly, 1st and 3rd Tuesday, 10AM EST)
**Collateral WG**
Host: Vernon Alden Smith
 Date: 3/28/23 (Monthly, last Tuesday, 10AM EST)
**Technology Architecture WG**
 Host: Chris Rayner 
 Dates: 4/13/23 (Monthly, 2nd Thursday, 2pm GMT)
- [x] 6. EasyCLA Signing 

Those who intend to become participants in the CDM project and create pull requests against the CDM repository at FINOS – we encourage all of the CDM community to review this process and check your corporate status internally and start the process of becoming a FINOS CLA-covered participant.

The FINOS CLA defines the terms under which intellectual property has been contributed.  Every individual who wants to make a contribution to participate in a FINOS-hosted standards project must formally enroll as a participant using the [Community Specification License](https://github.com/finos/common-domain-model/blob/master/LICENSE.md) (CSL) , which is available for firms (Corporate CLA) and individuals (Individual CLA). By enforcing participants to be covered by a CLA, we protect consumers from having legal disputes around intellectual property.

The Linux Foundation provides a framework called [EasyCLA](https://protect-usb.mimecast.com/s/nEmcC3Yx4yU2W5gigxEWI?domain=easycla.lfx.linuxfoundation.org/), which a) flags contributions that are submitted by participants not covered by CLA and b) simplifies the onboarding and signature of CLAs as firms or individuals.

Many organizations that are members of ICMA, ISDA, and ISLA are already setup with Corporate CLA on EasyCLA and a CDM contributor may just need to be added to the list under their organization.

Organizations who want to onboard their employees on EasyCLA can follow these simple steps:

1. Access [https://organization.lfx.linuxfoundation.org](https://protect-usb.mimecast.com/s/_b1MC4Wy5zUlRp2Sx3wN-?domain=organization.lfx.linuxfoundation.org) and add or manage your organization; you'll need to have an LF ID, the page will guide you through the profile creation if needed.
2. As soon as you are in front of your Organisation's landing page in EasyCLA, you can search for the FINOS (The Fintech Open Source foundation) project (in the left sidebar) and define one or more CLA Managers, individuals within the organization who have the authority to add or remove employees from the list of approved contributors.

Any employee who submits a Pull Request via GitHub on the CDM repository will either be identified by the EasyCLA bot (and the PR will be green-flagged accordingly) or flagged as "Not Covered", reporting instructions on how to a) define her/his affiliation and b) notify the CLA Manager of the employer to add the contributor to the approved list.

Here is an interesting [video on Youtube](https://protect-usb.mimecast.com/s/aL-9C5Az6Rf6wVPsyQd0V?domain=youtube.com) that can help understand how the process works, which can hopefully provide a clearer overview of the tool. Alternatively, please click on the following link to find out more 
https://docs.linuxfoundation.org/lfx/easycla and/or https://github.com/finos/standards-project-blueprint/blob/master/governance-documents/Getting%20Started.md#best-practices

- [x] 7. Example of contribution workflow

![image](https://user-images.githubusercontent.com/112546065/224347802-8548b1f5-ccf2-4698-9668-46499916534d.png)

- [x] 8. AOB, Q&A & Adjourn (5mins)

## **Decisions Made**

1.  N/A for this inaugural meeting

## **Action Items**

1.  Issue to be created where "CDM Getting Started" style details can all be shared. Potential for a workshop to be run on this topic in the future too.

### **Zoom Info**

* Meeting link: [https://zoom.us/j/91534818345?pwd=czVWamk4cVVrMHEydXl5ZlNoQmVHdz09](https://zoom.us/j/91534818345?pwd=czVWamk4cVVrMHEydXl5ZlNoQmVHdz09)
* Meeting number: 915 3481 8345
* Password: 728199
* More ways to join:
    * Find your local number: https://zoom.us/u/aer8zOwD1B
    * Join by phone:  +1 360 209 5623 US Toll 

## **Untracked attendees**

   <td>Full name,

   </td>
   <td>Affiliation,

   </td>
   <td>GitHub username.

   </td>
  <tr>
  <tr>

**Comment by brooklynrob** [comment]
Rob Underwood here. So excited to see this effort kicking off!

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS here

**Comment by nigelcobb** [comment]
Nigel Cobb / REGnosys here

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA - Anseo!

**Comment by eteridvalishvili** [comment]
Eteri Dvalishvili / FINOS

**Comment by maoo** [comment]
Maurizio (mao) Pillitu / CTO at FINOS 👋

**Comment by davidshone** [comment]
David Shone (ISLA) present

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by dyek** [comment]
Dunstan Yek / FORVIS Global Advisory (UK) Ltd

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by manucarreramoreno** [comment]
Manuel Carrera / TradeHeader

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by gabriel-ICMA** [comment]
Gabriel Callsen / ICMA

**Comment by annamunoz** [comment]
Anna Munoz / Tradeheader

**Comment by mcleo-d** [comment]
James McLeod / FINOS 👋🏻

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend

**Comment by BenAJohnson** [comment]
Ben Johnson / FORVIS UK

**Comment by FAM-CEB** [comment]
Frederico Alcantara de Melo / Council of Europe Development Bank (CEB)

**Comment by Milage** [comment]
Robert Miles / GLMX

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FTAdvisory

**Comment by ben-aubry** [comment]
Ben Aubry / Axoni

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by antonkaplanaxoni** [comment]
Anton Kaplan / Axoni

**Comment by rowan-ICMA** [comment]
Rowan Varrall / ICMA

**Comment by mmani99** [comment]
Mani Pillai / otcDigital

**Comment by rsiddharthan** [comment]
Sid Siddharthan / Barclays

**Comment by AnneSup** [comment]
Anne Suprenant/ Swift

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by aostlerspgi** [comment]
Anthony Ostler / S&P Global

**Comment by ronaldssebalamu** [comment]
hello

**Comment by LianaKirk** [comment]
Liana Kirk / ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by PetkoRuskov** [comment]
Hello :-)

**Comment by JohnTKN** [comment]
John Anderson from Tokenovate - Happy to be here

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by jduscherer** [comment]
apologies, was late to the call!

**Comment by AlainSayagh** [comment]
Alain Sayagh / Council Of Europe Development Bank

**Comment by PetkoRuskov** [comment]
Petko Ruskov, Sofia University. Happy to be here. Thank you!
