### ISSUE TITLE
Contribution Review WG - March 21 11AM EST/3pm GMT

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2013]
**Date**
Tuesday 21st Feb 2023 - 11am EST / 3pm GMT

**Zoom Info**

Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1679240390101264&usg=AOvVaw1PnD252w3SjoKYr0EucBVI)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1679240390101264&usg=AOvVaw0n_HNO1FMT4I_YBkDPqkuk)

**Meeting Notices**

FINOS Project leads are responsible for observing the FINOS guidelines for running project meetings. Project maintainers can find additional resources in the FINOS Maintainers Cheatsheet.

**All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

**Agenda**

- [ ] - Convene & roll call, review meeting notices (5mins)
- [ ] - Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] - Review action items from previous meeting (5mins)
          * (Ready for public review? QQ by @mcleo-d) Terms of Reference
          * FAQ/Get Started Issue, [CDM FAQ](https://github.com/finos/common-domain-model/issues/2058)
- [ ] - Contribution Workflow and Tagging Rules
- [ ] - PRs Under Review
- [ ] - FINOS Hackathons
- [2023-05-03 - Hackathon at BMO NYC](https://www.finos.org/hosted-events/2023-05-03-member-exclusive-hackathon-bmo)
Register for our first Hackathon at BMO NYC on May 3-4, 2023. 
- [From 2023-04-24 to 2023-05-18 - Global Accessibility Awareness Day
Hackathon ](https://www.finos.org/hosted-events/2023-05-18-gaad-hackathon)
Register for our virtual Hackathon by April 21st, 2023. 
- [ ] - CDM Mailing List 
For future updates about the Common Domain Model please email [cdm+subscribe@lists.finos.org](mailto:cdm+subscribe@lists.finos.org) to subscribe to the [CDM mailing list ](https://lists.finos.org/g/cdm). 
- [ ] - AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Contributors should use labels on their PRs: Major, Minor or Patch. (Follow up from maoo if there is an existing FINOS standard.)

## Action Items
- [ ] Members to review ToR and provide comments.
- [ ] Members to review CDM FAQs and provide comments.
- [ ] FINOS to provide guidance on how to fix EasyCLA coverage error.
- [ ] ICMA to open issue for comments on when contracts should be split, closed and opened.
- [ ] Members to review pending PRs and comment, approve or request changes.

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by eteridvalishvili** [comment]
Eteri Dvalishvili / FINOS

**Comment by dyek** [comment]
Dunstan Yek/FORVIS

**Comment by eteridvalishvili** [comment]
Adding in Mark Prestileo / Wellington who is having an issue with GitHub.

**Comment by iansloyan** [comment]
Ian Sloyan ./ ISDA

**Comment by GeorginaJarratt** [comment]
Georgina Jarratt - ICMA
