### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by nigelcobb** [finos/common-domain-model#2029]
A release schedule should be provided for the CDM giving detail to implementors on current supported versions of the model and when future versions are expected to be released.

**Comment by eteridvalishvili** [comment]
Hi @nigelcobb The PRs linked to this issue have both been resolved so I am closing. Please feel free to reopen if necessary. Thank you!

**Comment by eteridvalishvili** [comment]
Hi @nigelcobb and @lolabeis Closing this issue. Please reopen if necessary.
