### ISSUE TITLE
Technology Architecture Working Group Minutes - April 13th 9 AM EST

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2057]
Common Domain Model Technology Architecture WG Meeting

## Date
April 13th, 2023- 9am ET / 2pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Introduction to the group
<img width="980" alt="finos-cdm-governance-structure" src="https://user-images.githubusercontent.com/112546065/231506793-36db0d7b-9e81-4382-a774-e41c0f983b27.png">

- [x] Proposed Terms of Reference

**Purpose**
To discuss and actively enhance the Common Domain Model (CDM) to expand its support for existing and future technologies, tooling, services, infrastructure and deployment architectures. 

**Scope**
The group shall discuss and agree upon enhancements in relation to the technological development and improvement of the CDM. Where appropriate, the group will undertake the work required to develop and contribute the changes for these enhancements into the production CDM. 

Topics for discussion – in no particular order – include, but are not limited to, the following areas:
- Defining discrete and self-contained use cases which will benefit technology, service or data providers and encourage broader CDM usage
- Make it easier to pick and use the model by providing implementation code examples and deployment architecture examples
- Improve existing tooling and expand tooling options
- Support for more programming languages/code generators out of the box
- Collaboration with other FINOS projects like FDC3 and Legend
- Incorporation of external code into the CDM distribution
- Discover and recover technical debt wherever possible
- Expand and improve test case depth and coverage
- Document technical aspects of the model usage and deployment

**Responsibilities**
As outlined in README.md, the initial maintainers of the CDM Technology Architecture Working Group will be nominated by ISLA, ISDA and ICMA. Additional Maintainers can be proposed by the working group participants and approved by the existing Maintainers. 

Participants of the group will be expected to get actively involved in further developing the CDM. This could be related to data modelling, developing additional programs, tooling or test cases, or assisting with documentation and technical authoring. 

Where a recommendation has been made by the group, participants with the relevant skillset will be encouraged to assist with the work required to promote the changes to the production CDM.

**Membership**
The group is open to all members of the FINOS community with an interest in furthering the technology and infrastructure supporting the Common Domain Model.

It is expected that participants of the group will have a background in modelling, application development or deployment, API or service implementation or technical architecture. 

An understanding of financial markets and trading is preferable.

**Recommendations and decision-making**
As outlined in governance.md, the CDM Technology Architecture Working Group will operate by consensus-based decision-making.

- [x] Specific Projects to consider
- [x] Community raised Projects
       - CDM Version update in Legend
- [x] Next Meeting
**Date:** 11th May 2023
**Time:** UK 2pm
- [x] AOB, Q&A & Adjourn (5mins)
- [x] Join us for our first FINOS in-person Hackathon at the BMO (Bank of Montreal) offices in New York City. [Sign up here.](https://www.finos.org/hosted-events/2023-05-03-member-exclusive-hackathon-bmo)  [Explore the use cases here](https://www.finos.org/member-exclusive-hackathon-use-cases) and if you have some you’d like to share, [contact our CTO Maurizio Pillitu](mailto:maurizio.pillitu@finos.org).
- [x] [Register](https://www.finos.org/hosted-events/2023-06-14-member-meeting) for our first member meeting hosted at J.P. Morgan Chase - Embankment, London on June 14th - 15th. We’ll also have some public events! Read more below. Do you have a real world example of a FINOS project that you could demo? Showcase it at the member meeting as part of our project expo. Reach out to [marketing@finos.org](mailto:marketing@finos.org) or eteri.dvalishvili@finos.org.

## Decisions Made
- [x] Decision 1: Terms of Reference (ToR) should be more general in nature
- [x] Decision 2: Need more definition around the role of Maintainers for the group (to be added/referenced in the ToR)
- [x] Decision 3: ToR should also describe what is out of scope for this group
- [x] Decision 4: First project proposed as analysis of CDM versioning/build

## Action Items
- [x] Action 1: Chris: Contact those nominated as Maintainers for the WG
- [x] Action 2: Chris: Update the ToR into a new draft for the next meeting
- [x] Action 3: Chris: Take suggested specific projects out of the Scope above into the Ideas section of the CDM github
- [x] Action 4: Chris: Define Agenda for next meeting: 
       - Review ToR changes
       - Nominated Maintainer introductions and approval by participants
       - Discuss and prioritise initial projects 
       - Feedback on usage by the community of Legend and Rosetta

### Zoom info
- Join Zoom Meeting
[https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09](https://www.google.com/url?q=https://zoom.us/j/99036410403?pwd%3DMXNINndYcEd0dTBUZERuYTFwRGpWZz09&sa=D&source=calendar&ust=1679458708845084&usg=AOvVaw2Ivq06qtzhsqHJpvG5qZ0V)
- Meeting ID: 990 3641 0403
- Passcode: 745379
- Find your local number: [https://zoom.us/u/adtpQBjgT9](https://www.google.com/url?q=https://zoom.us/u/adtpQBjgT9&sa=D&source=calendar&ust=1679458708845084&usg=AOvVaw0PtuaQ0WdDrKaUSsvOSGQ2)

**Comment by dschwartznyc** [comment]
Dan Schwartz / FTAdvisory

**Comment by gabriel-ICMA** [comment]
Gabriel / ICMA

**Comment by smsant** [comment]
Sarah Santos / UPenn

**Comment by jgavronsky** [comment]
Jane / FINOS here

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend

**Comment by LuisNacarino** [comment]
Luis Nacarino / Santander

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by ronaldssebalamu** [comment]
Ronald Ssebalamu / FINOS

**Comment by fredericgignoux** [comment]
Frederic GIGNOUX / Societe Generale

**Comment by chrisisla** [comment]
Chris Rayner / ISLA
