### ISSUE TITLE
CDM Design Principle for Splitting, Closing and Opening New Contracts

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2061]
ICMA has put forward a proposal and design guideline on when contracts should be split, closed and opened. The fundamental rule is that anytime a contract does not mature naturally, as defined by the terms of the contract, then the contract would be closed and a new contract opened. This step in the workflow enables a designer to copy the existing parameters of an existing contract over to a new contract that would have modified terms.

This does not imply that external applications, downstream systems, or other service providers will follow this same rule or that a new UTI or other reference must change in the process of closing and opening a new contact in the CDM. 

This also does not mean that cash or securities transfers must take place as a result. Securities transfer instructions and cash transfer instructions are separate events and flows unrelated to the CDM close and open process.

Example of closing and opening repo trades:

- Change in maturity date, if fixed date.
- Change in repo rate/spread (does not apply to floating rate contracts where the index changes.)
- Change in collateral
- Change in general terms (notice date, early term option)

We welcome comments and recommendations on this design policy.

**Comment by chrisisla** [comment]
My thoughts are as follows:

If a contract is closed in the real world then the CDM should provide the same functionality. 

If an event optionally closes the contract, then the CDM should by default not close the contract, but there should be a way for the function to be able to close the contract if requested to. 

If the legal documentation laying out the terms of the trade allows for specific events without closing the contract then the CDM should not close the contract. 

In the situation where legal documents (e.g. GMRA, GMSLA) and best practices defined by trading associations (e.g. ISDA, ISLA, ICMA) have differences, then the CDM should do its best to harmonise the actions, but provide options for closing and/or not closing where appropriate.

For securities lending trades, the specific events listed above for repo would not require a contract to be closed:

- Change in maturity date/termination date – default would be to not close the original contract
- Change in rate – default would be to not close for either fixed or floating rate
- Change in collateral – default is not to close as substitution is allowed (but set in contract terms)
- Change in general terms – need a definition of what is “general” term as neither of the data items referenced would necessitate the closing of a securities lending contract

**Comment by tomhealey-icma** [comment]
There appears to be some confusion on this issue and the proposals don't really address the question. GMRA and other legal rules reside in the legal agreement model and should not be embedded in generic events. The same applies to regulatory rules like SFTR, or clearing and settlement rules. Why is this necessary, because the rules are different across the many service providers even within the same domain. The further this point, not all repos are traded on a GMRA. The second point is that, in this case of a substitution, the contract execution details, terms, UTI, and trade ID all remained the same. This is not the same as a new execution, so the process would fully support GMRA rules if needed, although as I believe it is not intended to follow a GMRA model. Rules from elements of the model are intended to be handled in workflow or custom designed functions. So what I suggest is to field proposals on a generic set of rules that are independent of any specific product domain and a separate set of helper functions specific to ISLA for handling specific security lending workflows.

**Comment by JBZ-Fragmos** [comment]
in all business cases where the event "would not require a contract to be closed" thus for all the ones you have listed, then you may _first_ consider these **two kinds of existing Instructions**, which shall permit to represent the related events, _and if_ not fully represented, _then_ you may want to consider a _refactoring_ :

- "**termsChange**" 
    - current **functional effect** is to "cancel/replace" 
    - **scope** of items updated = **Product** attributes
    - _REMARK_ : current proposal to increase the scope which has no reason to be restricted to Payout, since other Trades attributes might need to be updated (as first obvious business case, please see 

- **quantityChange**
    - current **functional effect** depends which directionEnum value you populate in the file : may be either Increase or Decrease or Replace
    - **scope** of items updated = **TradeLot** attributes e.g. PriceQuantity arrays
    - _REMARK_ : current functions are not covering all use cases in my opinion... and actually, for clarity, in FragmosChain, we have already implemented "home-made" functions, because we needed to cover more complex usages of quantityChange than the ones currently covered by existing Rosetta functions (at some point, we may decide to share, or not, our "home-made" functions in OpenSource, depending on the appetite from other participants and business interest for us...)

See below for each type of use case you listed which existing or refactored instruction you may try to use :
- Change in maturity date/termination date – default would be to not close the original contract 
    - use **cf. termsChange**
- Change in rate – default would be to not close for either fixed or floating rate 
    - use **cf. quantityChange**
- Change in collateral – default is not to close as substitution is allowed (but set in contract terms) 
    - use **cf. termsChange**
    - _with refactoring_ : need to extend current scope because collateral is not part of Payout node**
- Change in general terms – need a definition of what is “general” term as neither of the data items referenced would necessitate the closing of a securities lending contract 
    - **cf. termsChange** _if_ not closing
    - _else_ _with refactoring_ : to represent specific event which "closes & re-open" trade **

hope this helps
