### ISSUE TITLE
Emums should be formatted in UpperCamelCase

### ISSUE THREAD

**Issue by hugohills-regnosys** [finos/common-domain-model#2072]
Enums should be formatted in UpperCamelCase, with the exception of: 
- enums linked to external schemas such as FpML coding schemes, e.g., `BusinessCenterEnum` which is linked to http://www.fpml.org/coding-scheme/business-center
- other exceptions?

There are a number of enums that do not conform such as `EventTimestampQualificationEnum`.  Needs reviewing and amending.

**Comment by tomhealey-icma** [comment]
Now that this is up for discussion. I prefer enumerations in all upper case with the underscore as the only special character. Any other domain definition, FIX, FpML, SFTR should be done through mapping synonyms.

**Comment by tomhealey-icma** [comment]
Closed

**Comment by lolabeis** [comment]
This issue is referenced in PR #2060 that got merged, but that PR only surfaced the issue, it did not close it. Therefore the issue is still open.
