### ISSUE TITLE
 Download Rosetta VS Code plugin

### ISSUE THREAD

**Issue by oromano3** [finos/common-domain-model#2076]
Hi All,

I would like to make changes to Rosetta files directly on my desktop using the Rosetta VS Code plugin, but I cannot download the plugin through the following link indicated on the guidelines https://github.com/REGnosys/rosetta-dsl/tree/master/vscode-plugin.

Could you please support me?

**Comment by minesh-s-patel** [comment]
Hi,

Try this link. https://github.com/REGnosys/rosetta-dsl/tree/master/rosetta-ide/vscode

**Comment by minesh-s-patel** [comment]
@oromano3 - We fixed the link on the README.
