### ISSUE TITLE
Contribution Review Working Group - April 4, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2089]
# CDM  Contribution Review Working Group Minutes

## Date
April 4th, 2023 - 10am ET / 3pm GMT

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2013
- [ ] EasyCLA - Those who intend to become participants in the CDM project and create pull requests against the CDM repository at FINOS are encouraged to check their corporate status internally and start the process of becoming a FINOS CLA-covered participant.

Organizations who want to onboard their employees on EasyCLA can follow these simple steps:

1. Access [https://organization.lfx.linuxfoundation.org](https://protect-usb.mimecast.com/s/_b1MC4Wy5zUlRp2Sx3wN-?domain=organization.lfx.linuxfoundation.org) and add or manage your organization; you'll need to have an LF ID, the page will guide you through the profile creation if needed.
2. As soon as you are in front of your Organisation's landing page in EasyCLA, you can search for the FINOS (The Fintech Open Source foundation) project (in the left sidebar) and define one or more CLA Managers, individuals within the organization who have the authority to add or remove employees from the list of approved contributors.

- [ ] Structured Products WG has been scheduled. You can find the meeting information on the [FINOS community calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York). 
Host: Jean-Baptiste Ziade
Date: 4/11/23 (Monthly, second Tuesday, 10AM EST)
- [ ] Review of open Pull Requests and any delays
- [ ] Initial discussion of PR Triage process being developed - thoughts from community re best practice welcome
- [ ] AOB, Q&A & Adjourn (5mins) 

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1680707665490477&usg=AOvVaw27ezpMUl_gHX1o5d0MiqYd)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1680707665490477&usg=AOvVaw3U98rse5dQKfiq6nLP1vg3)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by eacunaISDA** [comment]
Eleonora Acuna / ISDA

**Comment by rvincentISDA** [comment]
Ruddy ISDA

**Comment by syoon078** [comment]
Sarah Yoon / FORVIS

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by ADaleISLA** [comment]
Adrian Dale / ISLA
