### ISSUE TITLE
Structured Products Working Group

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/common-domain-model#2092]
## Date
Tuesday, April 11 2023 - 10am ET / 3pm BST

## Untracked attendees
- Fullname, Affiliation, GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Agenda item 1
- [ ] Agenda item 2
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

- CDM is inviting you to a scheduled Zoom meeting.

- Join Zoom Meeting

[https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09](https://www.google.com/url?q=https://zoom.us/j/92136087343?pwd%3DVER4aW83TC9HNDVxbXU3UUkxU1BoUT09&sa=D&source=calendar&ust=1681564533916496&usg=AOvVaw2lBttowS_0ID74F592Syrw)

Meeting ID: 921 3608 7343
Passcode: 861434
One tap mobile
+19292056099,,92136087343# US (New York)
+16469313860,,92136087343# US

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste ZIADE (CPO - Fragmos Chain)

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by dschwartznyc** [comment]
Dan Schwartz/FT Advisory

**Comment by SergioGuirreri** [comment]
Sergio Guirreri / Reply

**Comment by jgavronsky** [comment]
Jane / FINOS here
