### ISSUE TITLE
FRAGMOS - Fixed Rate Compounding

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2098]
**REQUEST** : 

- **remove** both **existing conditions** below which are currently preventing to define Compounding features for Fixed Rate
   - condition FpML_ird_9
   - condition FpML_ird_29

![image](https://user-images.githubusercontent.com/92978493/232394818-72b1efa0-651a-405d-aa36-342929c69d72.png)

**RATIONALE** :

**Fixed Rate compounding must be permitted**

Please consider recent ISDA 2021 for instance : 
![image](https://github.com/finos/common-domain-model/assets/92978493/f9bba5b0-e3e3-46bc-85fa-81a618817ab9)

**Comment by mgratacos** [comment]
I disagree. Compounding Method is only specified for the treatment of the **Spread** in case there is compounding in the floating leg. It is not a flag to specify whether compounding applies.

**Comment by JBZ-Fragmos** [comment]
you are correct that Compounding method is about Spread treatment, not about the fact compounding would apply to any leg, however there is another rule in the model that requires CompoundingMethod to exist when Frequency of Payment Dates is inferior to Frequency of CalculationPeriodDates, so maybe this is where the rules might be modified...

for now, will de-prioritize this request (thus will close this ticket)
