### ISSUE TITLE
FRAGMOS * whole Model benefit + required for Struct *  - upgrade Observable to make it more generic

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2106]
**PROBLEM STATEMENT**
As of today both **inconsistency** and **overlaps** exists between Observable and Product :

- ProductIdentifier is an attribute of Observable whereas Product is not. Yet Product encompasses ProductIdentifier as part of larger scope. That is to say Product should replace ProductIdentifier attribute in Observable. That will solve one main issue with current state today where it is **impossible** today **to represent Basket as an Observable** 
=> this has in turn **multiple side-effect**one as an **example** is when using the **Transfer** : it is **impossible to represent the transfer of a Basket.**.. because only single productIdentifier can designate the asset being transfered...)

- Another angle of view why current situation is **not satisfactory** : why Commodity exists in both Product and Observable whereas **Index, Loan, Security, Basket do not exist in Observable** ? that means you cannot "observe" an Index ? you cannot "observe" a Security or a Basket" ? obviously this is wrong : one may want to observe these items on markets...

- Besides, **ForeignExchange** in Product **needs to be harmonized** with QuotedCurrenyPair in Observable ; also ForeignExchange has no ProductIdentifier and may not be considered as a Product actually

- Also the refactoring of Observable shall go with a litgh **refactorig of current Basket type** i.e. for consistency proposal the Basket shall be amended as well in order to benefit from the amendment made on Observable - the main issue with Basket today is that basketComponent is actually of type Product that is de facto restricting components in nature, I mean **basketComponents should precisely consists in the new Observable as refactored,** so that Basket can contain not only multiple products but also multiple currencyPairs, or floatingRateOptions i.e. any type of Observable in the end might be considered as basket component...  (see below PROPOSAL where both refactoring are detailed : for Observable, and also for Basket per se)

![image](https://user-images.githubusercontent.com/92978493/232561169-be60899d-d2b9-4f9c-be77-4857e33c8551.png)

**PROPOSAL**

- To refactor Observable to encompass Product together with other kinds of Observable which are not Product i.e. QuotedCurrencyPair and FloatingRateOptions

- To remove  ForeignExchange from Product (we assume that QuotedCurrencyPair shall replace it everywhere / also ForeignExchange has no ProductIdentifier so may not be considered as a Product actually)

- Also currencyPair card needs to be updated from (0..1) currently to (0..*) because when Basket exists, then several currencyPairs mihght need to be observed

- This also required **Product** to be refactored : 

1. below we notably propose to add Basket, that is core need for consistency reason when refactoring Observable... 
2. we also propose to add Digital Asset
3. and two minor items to optionally further define Observable which are : Exchange and RelatedExchange

![image](https://user-images.githubusercontent.com/92978493/232561302-637c4998-10c6-4d1e-b8d0-8537d675d88c.png)

![image](https://user-images.githubusercontent.com/92978493/232563250-fcc40648-0ca9-44e2-97d7-465e6857d554.png)

to get global picture, here is the graphical view :

![image](https://user-images.githubusercontent.com/92978493/232563029-85f0afa1-fbbe-452a-81e3-9b3911d8e54d.png)

- AS AN INFORMATION, together with this GitHub Issue, the **Basket** object needs to be refactored as well to ensure the new Observable item also benefits to Basket >>> thay is covered in the linked GitHub Issue : 
https://github.com/finos/common-domain-model/issues/2506

![image](https://github.com/finos/common-domain-model/assets/92978493/4423334b-befd-49ba-80d2-9ca2fb0ea166)

**Comment by JBZ-Fragmos** [comment]
just to provide **an example of a Use Case** for the refactoring proposed above that is to represent a **vanilla FX Correl Swap**.

so many other Use Cases exist, but at least I provide one that is basic, on purpose, to show why this refactoring is needed i.e. withtout such refactoring, it is not possible - unless i've missed something ? - to represent such Product as of today, though a vanilla type of Product... 

indeed, a FX Correl Swap means to represent a **Basket made of at least (2 possibly more) CurrencyPair components**

yet this is **not possible today**, neither via Observable root, nor via Underlier root, because of the Basket type

because the current structure of the Underlier that is of object type Product, does not permit to represent a Basket made of CurrencyPair components (you can only include ForeignExchange which is not at all convenient, as compared to CurrencyPair, because ForeignExchange is per se a kind of sub-payout that include required attributes which are not at stake for the simple purposes to define straight CurrencyPairs)

**with the above refactoring proposal, such type of product, also more complex ones, would be easily and properly represented**

**Comment by jiahaodengbb** [comment]
Is it possible to use `productIdentifier` to "observe" a basket?

**Comment by jiahaodengbb** [comment]
Small comment to the doc in your proposed change to the `FloatingRateOption`, do you mean:
```
Specification of a floating rate option as a floating rate index and tenor.
```

**Comment by jiahaodengbb** [comment]
Have we considered keeping both `ProductIdentifier` and `Product` in the `NewObservable`? I am asking because it seems to be more efficient to use `ProductIdentifier` to observe the product from the market if there is already a ticker for that product. If there is no `ProductIdentifier`, we may use `Product` to "structure" our own observable.

**Comment by jiahaodengbb** [comment]
I am OK with adding `Basket` and `DigitalAsset` to `NewProduct`. 

Could you explain why we want to add the `exchange` and `relatedExchange` to `NewProduct`?

**Comment by JBZ-Fragmos** [comment]
simply because **this information is missing** i.e. most of termsheets mention this information for each underlier the main exchange (spot market) and the relatedExchange (related derivatives market)

example below : 
![image](https://github.com/finos/common-domain-model/assets/92978493/4d5def5d-9dea-4a49-a37a-efd38975486a)

**Comment by JBZ-Fragmos** [comment]
regarding other questions 
_"Is it possible to use productIdentifier to "observe" a basket?"_

- yes, CDM is agnostic to the fact productIdentifer is effectiveley observable in market or might be bespoke suhc as it is when applied to basket

**Comment by JBZ-Fragmos** [comment]
regarding other questions
"Have we considered keeping both ProductIdentifier and Product in the NewObservable? "

- actually this is already there, i mean ProductIdentifier is an attribute it is juts n+1 node down below for instance here : 

![image](https://github.com/finos/common-domain-model/assets/92978493/2f40a83f-bff2-47b0-962f-399f34e68569)

importantly that is how it works in CDM today we do not need to refactor, the only missing point is to gather all types of observable together, hence the proposal to have Observable = ratOption or currencyPair or product (which as yo uwish dully has a productIdentifier an attribute)


- -

**Comment by JBZ-Fragmos** [comment]
regarding other questions _"FloatingRateOption, do you mean: Specification of a floating rate option as a floating rate index and tenor"_

- i mean exactly as it is in current model, i propose **no change** to the exiting type objkect FloatingRateOption below, hwich effectively contains the option per se AND tenor : 
![image](https://github.com/finos/common-domain-model/assets/92978493/c1fe4348-4ac9-45a0-83c8-b4632829875b)

**Comment by jiahaodengbb** [comment]
> * i mean exactly as it is in current model, i propose **no change** to the exiting type objkect FloatingRateOption below, hwich effectively contains the option per se AND tenor :

Thanks. Then in your screenshot there might be a typo as it says "specifies a floating rate index and tenor". Could you fix that? 
![](https://user-images.githubusercontent.com/92978493/232561302-637c4998-10c6-4d1e-b8d0-8537d675d88c.png)

**Comment by JBZ-Fragmos** [comment]
but this is original narrative that currently exists for the type FloatingRateOption and it looks good to me ; maybe i've not fully understood your point - let's clarify it during our call today

**Comment by llynhiavu** [comment]
Does anyone recall by any chance if indexTenor was incorrectly set as mandatory in CDM 4.x?

and corrected in CDM 5.x since:

![cdm-indexTenor-5](https://github.com/finos/common-domain-model/assets/132079003/9aaae3e7-2a6a-492a-9ca5-1adab51334af)

a firm using 4.x is asking. Thanks.

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
