### ISSUE TITLE
CDM should have automated tests for Windows and Linux

### ISSUE THREAD

**Issue by hugohills-regnosys** [finos/common-domain-model#2111]
Following issue https://github.com/finos/common-domain-model/issues/2110, the CDM should have automated testing on Windows.  Currently the CI/CD builds are all running on linux.

**Comment by eteridvalishvili** [comment]
Hi @hugohills-regnosys As you have resolved https://github.com/finos/common-domain-model/issues/2176, I believe it is okay to close this issue as well. Please reopen if necessary. Thank you!
