### ISSUE TITLE
Collateral Working Group - April 25, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2115]
# CDM  Collateral Working Group Minutes

## Date
April 25th, 2023 - 10 am ET / 3 pm GMT

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2055
- [ ] Join us for our first FINOS in-person Hackathon at the BMO (Bank of Montreal) offices in New York City. [Sign up here.](https://www.finos.org/hosted-events/2023-05-03-member-exclusive-hackathon-bmo)  [Explore the use cases here](https://www.finos.org/member-exclusive-hackathon-use-cases) and if you have some you’d like to share, [contact our CTO Maurizio Pillitu](mailto:maurizio.pillitu@finos.org).
- [ ] [Register](https://www.finos.org/hosted-events/2023-06-14-member-meeting) for our first member meeting hosted at J.P. Morgan Chase - Embankment, London on June 14th - 15th. We’ll also have some public events! Read more below. Do you have a real world example of a FINOS project that you could demo? Showcase it at the member meeting as part of our project expo. Reach out to [marketing@finos.org](mailto:marketing@finos.org) or eteri.dvalishvili@finos.org.
- [ ] CDM Collateral Working Group Meeting Slides 25th April 2023
[ISDA Common Domain Model - Collateral WG 25th April 2023.pdf](https://github.com/finos/common-domain-model/files/11310988/ISDA.Common.Domain.Model.-.Collateral.WG.25th.April.2023.pdf)
- [ ] 1. CDM Collateral Working Group - Upcoming book of work / Update of new WG ToR
[ISDA CDM Collateral WG Terms of Reference- Version 8 - April 2023 DRAFT.docx](https://github.com/finos/common-domain-model/files/11310973/ISDA.CDM.Collateral.WG.Terms.of.Reference-.Version.8.-.April.2023.DRAFT.docx)
- [ ] 2. Cash Collateral Interest Contribution Update and Next Steps
- [ ] 3. SFTR Collateral Transfer Methods
- [ ] 4. Collateral Provisions - Data Type Review 
- [ ] 5. Eligible Collateral Updates
       -         Eligible Collateral – Change of data type name/label contributed
       -         Next Steps re open-source access to CDM object builder.
- [ ] 6. CDM Collateral - Get started guide
- [ ] AOB, Q&A & Adjourn (5mins) 

## Action Items

**Action 1** 
Requirement to establish a means of monitoring the working groups book of work (milestones sections of the draft TOR) on a regular basis. But to also maintain a static ‘Terms of Reference Document’ (TOR) and working group governance structure. Members discussed these could be separated. Finos and the trade associations will review and confirm in due course. 
ISDA will work with FINOS, ISLA and ICMA to establish the new working groups TOR and a means of separately reviewing the book of work. Some of the content will remain, additional scope and content to be added. 

**Action 2**
As referenced in agenda item No 2 - Cash Collateral Interest Contribution Update and Next Steps. This work related to the parameters needed to calculate and process cash collateral interest initially developed for the ISDA CSA is pending contribution to the CDM. After analysis to ensure compatibility going forward and reusability of existing data components related to interest rate products. ISDA will co-ordinate the refactoring of the floating rate specification for the commonality between collateral interest calculation standard interest rate product. Once completed this will be shared with the working group for full review. 

**Action 3**
As referenced in agenda item 3 ‘SFTR Transfer Methods’, ICMA will raise an issue for members to discuss the further various options for representing collateral transfer methods under the various collateral agreements and trade use cases.

**Action 4**
As referenced in agenda item 3 ‘Collateral Provisions Data Type’, ICMA have sent a pull request https://github.com/finos/common-domain-model/pull/2084 to make the cardinality optional for the SFT specific options. Members agreed this may need further review if to be used as a marker specific structure, as further refactoring may be required. 

**Action 5** 
As per agenda item 5, second point. ISDA will give the working group an update related to the open sourcing of the CDM Object Builder when more news becomes available.  

**Action 6**
As per agenda item 6, The trade associations will start to develop a CDM Collateral get started guide and share progress with members in due course. 

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09](https://www.google.com/url?q=https://zoom.us/j/96084284579?pwd%3DQTJ3bTBrMURkWXA1S0owa1djaEVIUT09&sa=D&source=calendar&ust=1682356094912169&usg=AOvVaw0342_Ew-y0vMPK4DoKubxw)

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: [https://zoom.us/u/aoBkYnW9l](https://www.google.com/url?q=https://zoom.us/u/aoBkYnW9l&sa=D&source=calendar&ust=1682356094912169&usg=AOvVaw1wU9YdYu0Huo4ZJc9oKUUw)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by dharmkap** [comment]
Dharm Kapadia/EquiLend

**Comment by adamulman** [comment]
Adam  Ulman / SmartStream

**Comment by brooklynrob** [comment]
Rob Underwood / Independent

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FTAdvisory

**Comment by mikealambert** [comment]
Mike Lambert / Broadridge

**Comment by H-Nicol** [comment]
Helen Nicol/CloudMargin

**Comment by duncancarpenterpirum** [comment]
Duncan Carpenter / Pirum Systems

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by SergioGuirreri** [comment]
Sergio Guirreri / Reply

**Comment by Amkada** [comment]
Amed MKADA / Vermeg

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by eteridvalishvili** [comment]
Isabelle / Vermeg - She is unable to comment

**Comment by JanGEoc** [comment]
Jan Grauls / Euroclear

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend (1st 30 min)

**Comment by JamesStillwell** [comment]
James Stillwell / Pirum Systems

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by fldemarche** [comment]
Florent Demarche / Murex

**Comment by GeorginaJarratt** [comment]
Georgina Jarratt, ICMA
