### ISSUE TITLE
Inadequate logging dependencies

### ISSUE THREAD

**Issue by aber4mx** [finos/common-domain-model#2124]
Hello,

The cdm library exposes awkward logging dependencies :
- _ch.qos.reload4j:reload4j:1.2.24_  (replacement implementation of log4j 1)
- _org.slf4j:log4j-over-slf4j:2.0.1_  (also a replacement of log4j1 (same classes), this time to redirect logging to slf4j-api)
- _ch.qos.logback:logback-classic_/_ch.qos.logback:logback-core_ : logging implementation that plugs with slf4j-api

I would expect CDM (and libraries in general) to use a logging abstraction layer (slf4j-api is just perfect) and let the consumer code provide the logging implementation/configuration for runtime.

All these dependencies are transitive, coming from two [regnosys](https://github.com/REGnosys) projects. The attached [dependency tree](https://github.com/finos/common-domain-model/files/11335652/tree.txt) highlights this.
The ideal fix would be to be in the below libraries I suppose, but a intermediate workaround might be to exclude the reload4j and logback implementations froml CDM's dependencies.

Could you share your thoughts on this ?

Thanks,
Adrien

**Comment by hugohills-regnosys** [comment]
Fixed in https://github.com/finos/common-domain-model/pull/2170

**Comment by aber4mx** [comment]
Thank you @hugohills-regnosys !

**Comment by hugohills-regnosys** [comment]
Circling back on this - both concerns raised here are now addressed:

- `reload4j:reload4j` and `log4j:log4j/log4j-core` are already fully banned from CDM's dependency tree (all scopes), which was already in place before this change.
- `ch.qos.logback:logback-classic/logback-core` are now banned outside test scope too, via a build-level check (a Maven Enforcer rule) that fails the build if either is pulled in - directly or transitively - anywhere except test dependencies. That closes the gap you found: CDM's own code only ever compiles against `slf4j-api`, and it's entirely up to the consuming application to choose and configure its own logging implementation, exactly as suggested in this issue.

PR: https://github.com/finos/common-domain-model/pull/5156
