### ISSUE TITLE
Contribution Review Working Group - May 2, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2128]
# CDM  Contribution Review Working Group 

## Date
May 2nd, 2023 - 10 am ET 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
     - [ ]  https://github.com/finos/common-domain-model/issues/2099
- [ ] CDM Development Operating Model - Git Hub Labels and PR processing
           See attached issue for document and examples
              (https://github.com/finos/common-domain-model/issues/2129)
- [ ] AOB, Q&A & Adjourn (5mins) 

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1683054784909702&usg=AOvVaw3Rsuio_fWULs96SdD9FJxT)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1683054784909702&usg=AOvVaw3dWKkaMru7TSNyYrW9eTBX)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by RonAtCFX** [comment]
ron kaim / CFX COnsulting

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by mikealambert** [comment]
Mike Lambert - Broadridge

**Comment by gabriel-ICMA** [comment]
Gabriel / ICMA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by eacunaISDA** [comment]
Eleonora Acuna / ISDA

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by mdemarzio** [comment]
Michelangelo de Marzio ISDA

**Comment by d-sen-gupta** [comment]
Dhruva - JPMC

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by suyashyc** [comment]
Suyash Chaudhary RBC CM
