### ISSUE TITLE
Modelling available inventory in the CDM

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2137]
Lenders and agents broadcast a list of what shares they have available to lend to the market. This list of inventory could be sent to specific/preferred borrowers, to trading venues or sent as a general message to the market. 

The content and format of this detail varies based upon who is sending the inventory out, and who is the intended recipient of the data.

Over the past few months the ISLA Trading WG have explored the data used to describe this type of available inventory. Formats were provided by several vendors and platforms and were analysed by the group. From this a standard set of the data required was derived.

Virtually everything required to model the inventory data using the CDM is already available. At the present time there are only two proposed new types that would need to be added:

- Inventory – a new type to hold the list of inventory (see InventoryRecord) and the parties associated to it e.g. the sending party, receiving party, agent
- InventoryRecord – a new type that holds the details of a single piece of inventory i.e. one security with its available quantity and any other criteria 

The party and security information is already available in the model via the Party and Security types. The quantity of shares and desired rate (if applicable) can be modelled using PriceQuantity. If there are particular collateral requirements these can be modelled using CollateralProvisions.

We welcome feedback on this proposed enhancement to the CDM,  which we aim to present to the Contribution Review Working Group shortly. Please share any comments or requests below.

**Comment by tomhealey-icma** [comment]
Inventory is too general a name for a common term that is widely used in other contexts. If Inventory is only applied to security lending then other product domains would be precluded from using it in a different context such as the inventory held in a trading book. Also there is already a data type called Basket that constitutes a list of securities. So I would suggest creating a new type SecurityLendingOfferingBasket extends Basket:
....
conditions and other attributes needed specifically for security lending transactions.

This would meet the design principle that subtype domains are defined using a pre-fix modifier to the primary data type and doesn't replicate existing type containers and attributes.

**Comment by chrisisla** [comment]
"Basket" extends ProductBase and looks to be designed to hold products, whereas at this stage of the lifecycle there is no product. It also does not have a PriceQuantity underneath it (that I can see) which is one of the key requirements. 

We also looked at using "Position" but again, that defines products and trades, neither of which are present when the available shares are broadcast.

Agreed "Inventory" is generic - the term used in the market today to describe these lists is actually "Availability", which is even more generic, but also an option, so I'm keen to hear any other suggestions on possible naming. I would shy away from adding anything industry/market specific like "SecurityLending" in the name if we can.

**Comment by tomhealey-icma** [comment]
There really is a product, it's the basket of securities. The reason for making it an extension of the basket is to all for adding any specific attributes needed to address price, quantity, etc.

**Comment by tomhealey-icma** [comment]
I also want to point out that what you describing is more than just inventory, there's a sender, receiver and agent. Since this is pre-trade workflow I would suggest starting from that point with a 
type RequestForQuote: 
        product Product
        ...

**Comment by chrisisla** [comment]
I disagree that a basket of securities constitutes a "product". Sounds like we (the maintainers) need to define exactly what a "product" is!

Under Basket you have basketConstituent which is of type Product. Under Product the only item that would be used would be the security - but that is probably not necessary as you have the productIdentifier via extension . Everything under Product is optional so as you suggest, Basket could be extended, but it does adds a load of noise to the object (which I'm sure can be said when using a lot of types in the model...)

At the moment I don't see any real benefit to extending Basket, but thanks for the suggestion @tomhealey-icma

**Comment by chrisisla** [comment]
The RFQ is the step after this. So firstly the lender/agent would send out the availability and then the borrower would build the RFQ based upon those details if they wanted to. The RFQ we're thinking would be created as a new workflowstep -> proposedEvent.

**Comment by tomhealey-icma** [comment]
Going back to your initial description that inventory has a sender and receiver is not really a base case for the use of Inventory type which refers to a holding in the most generic sense. What you're describing is really two separate types, InventoryAvailableToLend entends Inventory which also raises the question of inventory vs position. 

Regarding a basket as product, it actually is a product of products. Baskets have their own pricing and can have their own identifier. And inventory may itself contain baskets. 

Inventory itself is not a product it's the result of owning or holding products.

**Comment by chrisisla** [comment]
Thanks for the replies @tomhealey-icma, we’ve spent some time going through the suggestions and playing with the model components. 

We looked at “Basket” and felt that it wasn’t right for this context. Having a basket of securities implies that there is some commonality between all the securities in the basket e.g. a basket of FTSE 100 shares. Basket can also be used to describe a trading basket, where the basket is used in its entirety, which is not the case with availability, whereby one, several or even none of the securities included could be utilised. 

The industry recognised term for the securities that a lender has available is “Availability”, and this looks to be true for both securities lending and repo markets. In earlier comments I think the main sticking point was the use of the term “Inventory” as it was felt that this term must be flexible enough to be used in the model in different contexts. Due to these two points we’re going to revert back to using “Availability” and “AvailabilityRecord” to disambiguate the usage of this data.
