### ISSUE TITLE
Proposal for adding purchase price and repurchase price to CDM

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2138]
Background
Repo trading is typically quoted in terms of security, rate and term. Settlement amount and final termination amount are determined based on security price and haircut or separately the loan amount can be agreed independently of the security price. 
The GMRA and best practices explicitly specify that repo contracts are defined by the purchase price and repurchase price. Knowing that these amounts as the agreed amounts by the counterparties is important when it comes to lifecycle events such as early payments, repricing and substitutions. It’s not always the case that adjusted collateral value equals loan amount. Repurchase price is also critical in determining exposure and margin. 
Currently, the CDM does not explicitly support the purchase price and repurchase price. For repo transactions they need to be added. I see three options:

1.	Explicitly add purchase price and repurchase price to tradeLot. To keep it generic we can call it initial price and final price.
2.	Explicitly add purchase price and repurchase price as new distinct attribute to InterestRatePayout. Again, to keep it generic we can call it initial price and final price.
3.	Lastly there is a possibility to add these amounts with only a minor change to the model by doing the following:

a.	Under InterestRatePayout include principalPayment, initial and final in repo execution:
"principalPayment": {
	"initialPayment": true,
	"finalPayment": true,
	"intermediatePayment": false,
	"principalPaymentSchedule": {
	"initialPrincipalPayment": {
	"principalAmount": {
	"unit": {											"currency": {												"value": "GBP"												}},
		"value": 1011650.34}}, -purchase price
finalPrincipalPayment": {
"principalAmount": {
	"unit": {	"currency": {											"value": "GBP"											}},
"value": 1011684.06}}}} <- repurchase price

b.	Change cardinality of settlement terms to (0..2) and add attribute termination date:

"settlementTerms":[ {
		"valuationDate":{
		"valuationDate":{
			"adjustedDate":"2023-04-14"
					}}	
"cashSettlementTerms": [{
		"cashSettlementAmount": {
					"unit": {
					"currency": {
						"value": "GBP"
						}},
					"value": 1011650.34 <-purchase price

					}}],
		"terminationDate":{
		"terminationDate":{
			"adjustedDate":"2023-04-17"
					}}	
"cashSettlementTerms": [{
		"cashSettlementAmount": {
					"unit": {
					"currency": {
						"value": "GBP"
						}},
					"value": 1011684.06 <- repurchase price

					}}],

**Comment by chrisisla** [comment]
Hi @tomhealey-icma ,
If we introduced these prices then do you think these would help in differentiating a repo from a stock loan? So a repo would have an initial and a final price but a stock loan would only have an initial price (if it had this price at all)? 
Also just wondering why you would not just add new price expression enums under `PriceQuantity` for these two prices?
Thanks

**Comment by tomhealey-icma** [comment]
Reviewing price components to use for purchase price.
