### ISSUE TITLE
Usage of [docReference] 

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2139]
The [docReference] mechanism available in the Rosetta DSL is designed to hold URLs to external resources. Recent additions to the model include a lot of text in these tags which is not inline with their intended usage, as described here: 

[https://docs.rosetta-technology.io/rosetta/rosetta-dsl/rosetta-modelling-component/#external-reference-data](https://docs.rosetta-technology.io/rosetta/rosetta-dsl/rosetta-modelling-component/#external-reference-data)

The proposal is that only links to external data are placed in docReferences, and not the referenced data/text itself. This will ensure that:
-	The model does not become cluttered – if multiple industry bodies and contributors to the model all add large amounts of text it will become increasingly difficult to discern the model content
-	The model does not need changing any time the text needs to be updated – this will future proof the model and reduce ongoing housekeeping
-	Any changes in the IP/trademarks/ownership pertaining to the text will not require a change to the model
-	The model only includes useful comments describing the elements in the model itself, leaving best practice and market details outside of the model

**Comment by chrisisla** [comment]
@iansloyan , @valdensmith - I have added you as assignees as we discussed this the other day.

**Comment by tomhealey-icma** [comment]
I agree with all the points above and I would suggest adding these points to the design principles.

**Comment by valdensmith** [comment]
Hi All. It would be good to set up discussion on this topic? I wanted to understand the longer term plan on document references. I can see some related to the GMRA in different places of the Eligible Collateral specification which may raise some questions from those reviewing and implementations, this area of the model receives a lot of attention. I am not saying its not useful to reference document information but my opinion is we need to approach this without overloading the model with text and having a consistent way agreed by all the TAs. Also I believe this would be a topic to raise and useful to get direction from members of the working groups especially the CDM Collateral WG.

**Comment by hugohills-regnosys** [comment]
The other intended usages of `[docReference]` are documented here:

https://docs.rosetta-technology.io/rosetta/rosetta-dsl/rosetta-modelling-component/#document-content-syntax

**Comment by chrisisla** [comment]
Thanks for this @hugohills-regnosys. I don't think it is a good idea to be embedding large amounts of text into the model though, based upon the reasons I outlined above. 

I think comments about particular types etc. are useful, but promoting the addition of large chunks of text from essentially being cut and paste into the model should not be encouraged.

**Comment by iansloyan** [comment]
While the syntax has been used correctly according to Rosetta's capabilities. It's usage in the general model has never been considered. Where doc references are needed to point to a regulation or specific document (which necessitated a bespoke or specific type in the model) I think that usage was well expected. However usage to relate a legal term to a fundamental CDM type like "Trade" was not expected.

There is a fundamental design strategy question which needs to be addressed in relation to this I think. Perhaps that can be discussed in a call? Or at the next Contribution and Review committee?
As we have a legalDocumentation model available to model structure and terms found in documents such as the GMRA, ISDA Master Agreement, or GMSLA, should we us the doc references in the main model at all in the CDM? Or, if we are using doc references for a particular type should there be an onus to also collate the equivalent from other products/markets?

**Comment by eteridvalishvili** [comment]
Hi @chrisisla Did this meeting take place and can we close the issue out?

**Comment by chrisisla** [comment]
Hi @eteridvalishvili,
The meeting took place yes, and there has been some follow up on this in a recent SWG. Consensus was that we should put less detail/text in the model, rather than more, and use docReference to link to external content, rather than add loads of text to the model itself. 
As a follow up I need to go through and see where we can reduce the text in the existing docReference tags and submit a PR. I think this can be considered separately so I'll close this issue and open a new one when I get a chance to review the model.
Thanks!
