### ISSUE TITLE
FINOS Structured Products Project - May 9 

### ISSUE THREAD

**Issue by Julia-Ritter** [finos/common-domain-model#2141]
FINOS Structured Products Project
Date
May 9th, 2023 - 10am ET / 3pm GMT

Meeting notices
FINOS Project leads are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

All participants in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact [legal@finos.org](mailto:legal@finos.org) with any questions.

FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

Agenda
 Convene & roll call (5mins)
 Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
 Review Meeting Notices (see above)
 Approve past meeting minutes
 https://github.com/finos/common-domain-model/issues/2089
 Join us for our first FINOS in-person Hackathon at the BMO (Bank of Montreal) offices in New York City. [Sign up here.](https://www.finos.org/hosted-events/2023-05-03-member-exclusive-hackathon-bmo) [Explore the use cases here](https://www.finos.org/member-exclusive-hackathon-use-cases) and if you have some you’d like to share, [contact our CTO Maurizio Pillitu](mailto:maurizio.pillitu@finos.org).
 [Register](https://www.finos.org/hosted-events/2023-06-14-member-meeting) for our first member meeting hosted at J.P. Morgan Chase - Embankment, London on June 14th - 15th. We’ll also have some public events! Read more below. Do you have a real world example of a FINOS project that you could demo? Showcase it at the member meeting as part of our project expo. Reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org).
 PR labels and tagging
 AOB, Q&A & Adjourn (5mins)

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by adavies42** [comment]
Aaron/Morgan Stanley

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziade (FragmosChain)
