### ISSUE TITLE
Technology Architecture Working Group - May 11, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2142]
# CDM  Technology Architecture Working Group

## Date
May 11th, 2023 - 9 am ET 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] [Register](https://www.finos.org/hosted-events/2023-06-14-member-meeting) for our first member meeting hosted at J.P. Morgan Chase - Embankment, London on June 14th - 15th. Do you have a real-world example of a FINOS project that you could demo? Showcase it at the member meeting as part of our project expo. Reach out to [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org).
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
     - [x]  https://github.com/finos/common-domain-model/issues/2057
- [x] Review and Approve Terms of Reference 
     - [x]  https://github.com/finos/common-domain-model/issues/2136
- [x] Maintainer introductions
- [x] Discuss and prioritise initial projects
     - [x] How to simplify getting examples and test cases for specific CDM versions (github?)
     - [x] Definition of the build process and what it should include
     - [x] Java logging dependencies
     - [x] Collaborative sandbox for experimenting with ideas (so can see alpha versions perhaps)
- [x] Feedback on usage by the community of Legend and Rosetta
- [x] AOB, Q&A & Adjourn (5mins) 
  - **Presenters Wanted** for CDM Talks and Demos at FINOS Member Meeting, JMPC, London - Thursday 15th June
    - **Getting hands on with the Common Domain Model (30 mins)**
      - The audience for this talk will be the engineers and team members who will practically engage with the CDM for doing the work. I'm happy for you to shape this session to get the most out of engaging with the CDM directly.
    - **The Business Benefits of Implementing the Common Domain Model (30 mins)**
      - The audience of the talk will be business leads who will assess the CDM for its digital transformation benefits and who will unlock the budgets needed for engineering teams and others to engage.      

## Decisions Made

- Approved minutes from previous meeting (’23 Apr 13)
- Ratified ToR.  Specifically defined the WG’s scope:
  - The purpose of this group is to promote the adoption and use of the Common Domain Model (CDM) through collaborative Open-Source development that aligns CDM’s architecture, tooling, services, infrastructure, development practices, and deployment to existing and future technologies. 
  - Agreed to kick off projects supporting areas of initial focus: improvements to Version Management and Build Processes
- Group's goal is to review, analyse and propose changes to the current process where there are gaps. Initial concerns included:
  - Ensuring that the current “production” release of CDM is readily definable.
  - Ensuring that developers can easily find Rosetta DSLs, sample CDM, code libraries and other artefacts tied to a particular version.  These may all exist but are not so easily found.
  - Share current Build Process to level set
  - Objective to present analysis / recommendations to the next WG meeting
- Discussion included creation of Sandbox capability which was put to lower priority.
- Discussion included the potential for expanding the use of Legend in the modelling process.

## Action Items
- [x] Version Management and Build Process : Spin up a task force to investigate the issue and make recommendations: **Dan**
   - email sent to cdm lists
- [x] Version Management and Build Process : Collate current understanding leveraging and expanding an initial draft of “CDM Getting Started”: **Tom**
   - Brought forward to June 8th Meeting, setting as complete here
- [x] Version Management and Build Process : Review current build process with REGnosys: **Chris to liaise with Hugo**
   - arranged meeting with Minesh
- [x] Other: Store ratified ToR according to FINOS protocol: **Chris and Eteri**
- [x] Other: Preliminary analysis for use of Legend in modelling: **Chris and Tom**
   - Brought forward to June 8th Meeting, setting as complete here

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09](https://www.google.com/url?q=https://zoom.us/j/99036410403?pwd%3DMXNINndYcEd0dTBUZERuYTFwRGpWZz09&sa=D&source=calendar&ust=1683922682114658&usg=AOvVaw2KKSMMROIGH16Y4_MZHqXk)

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: [https://zoom.us/u/adtpQBjgT9](https://www.google.com/url?q=https://zoom.us/u/adtpQBjgT9&sa=D&source=calendar&ust=1683922682114658&usg=AOvVaw0h2IXuikcBYejENKNAefbv)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by gabriel-ICMA** [comment]
Gabriel / ICMA

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FT Advisory

**Comment by smsant** [comment]
Sarah Santos / UPenn

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys

**Comment by richlinnellAxoni** [comment]
Rich Linnell : Axoni

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA
