### ISSUE TITLE
CDM Collateral Working Group - May 30th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2146]
# CDM  Collateral Working Group

## Date
May 30th, 2023 - 10 am ET 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x]  Review Meeting Notices (see above)
- [x] June 14th and 15 London Member Meeting - FINOS project use cases needed - Project Expo CTA
- [x] OSFF NY 2023 - The Call for Proposals is open and accepting submissions through Friday, June 23 at 11:59 PM. [Link](https://events.linuxfoundation.org/open-source-finance-forum-new-york/program/cfp/)
- [x]  Approve past meeting minutes
    - [x] https://github.com/finos/common-domain-model/issues/2115
- [x] CDM Collateral WG - Meeting Slides 
[ISDA Common Domain Model - Collateral WG 30th May 2023.pdf](https://github.com/finos/common-domain-model/files/11567458/ISDA.Common.Domain.Model.-.Collateral.WG.30th.May.2023.pdf)
- [x] 1. CDM Collateral Working Group 'Book of Work' final version 1 / Update for WG ToR
[ISDA CDM Collateral WG Book of Work May 2023.pdf](https://github.com/finos/common-domain-model/files/11567525/ISDA.CDM.Collateral.WG.Book.of.Work.May.2023.pdf)
For the Terms of Reference, the standard for Governance can be found here in the [Governance.md](https://protect-usb.mimecast.com/s/y1H5Cg79rnFvAvx2uoDHja?domain=github.com) and parts of it are reflected in the CDM [Readme.md](https://protect-usb.mimecast.com/s/yZpHCjA9x0fznzMqC5pv3e?domain=github.com).
- [x] 2. Cash Collateral Interest Contribution Update - Model Review
- [x] AOB, Q&A & Adjourn (5mins) 

## Action Items
- [ ] ACTION 1 - The working groups book of work version 1 can be found as an attachment in the agenda item No1. This will be monitored and updated on an approximate quarterly basis. The tasks identified in the PDF will be transferred into milestones under an ‘Issue’ in the GitHub for members to access and. ISDA will transfer before the next working groups meeting and ensure members know how to review.
- [ ] ACTION 2 - As referenced in agenda item No 2 - Cash Collateral Interest Contribution Update – Model Review. ISDA will co-ordinate the final contribution of this to the CDM. A representative from ICMA noted that once visible in the model they will review for compatibility with Repo products and feedback. 
- [ ] ACTION 3 - It was also referenced that there will be further work in the ISDA version of CDM to address translations related to documents affected by the changes to the cash interest structures in the ISDA test pack. Members of this working group will be informed once completed. 

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09](https://www.google.com/url?q=https://zoom.us/j/96084284579?pwd%3DQTJ3bTBrMURkWXA1S0owa1djaEVIUT09&sa=D&source=calendar&ust=1683994644378167&usg=AOvVaw2RCA5pO1BgtRFtphGXFdjq)

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: [https://zoom.us/u/aoBkYnW9l](https://www.google.com/url?q=https://zoom.us/u/aoBkYnW9l&sa=D&source=calendar&ust=1683994644378167&usg=AOvVaw3kZboEH-UJs6giFTHk0Ksi)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by brianlynn2** [comment]
Brian Lynn GEM/ISDA

**Comment by chrisisla** [comment]
Chris Rayner /ISLA (first 20 minutes)

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by dharm-kapadia** [comment]
Dharm Kapadia / EquiLend (first 30 mins)

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend (1st 30 min)

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by adamulman** [comment]
Adam Ulman, SmartStream

**Comment by RonAtCFX** [comment]
Ron Kaim @ CFX Consulting

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by daniel93152** [comment]
Jiahao Deng @ Bloomberg

**Comment by paulpkelly** [comment]
Paul Kelly, Logical Construct

**Comment by AmyCaruso** [comment]
Amy Caruso, ISDA

**Comment by SergioGuirreri** [comment]
Sergio Guirreri, Reply

**Comment by Alexis25091972** [comment]
Alexis Lucas BNY Mellon

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by SergioGuirreri** [comment]
> 

Sorry I have to leave

**Comment by eteridvalishvili** [comment]
Closing this issue, please reopen it if you see fit.
