### ISSUE TITLE
Contribution Review Working Group - May 23, 2023

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2147]
# CDM  Contribution Review Working Group 

## Date
May 16 2023 - 10 am ET 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes, [link](https://github.com/finos/common-domain-model/issues/2128)
- [ ] June 14th and 15 London Member Meeting - FINOS project use cases needed - Project Expo CTA 
- [ ] OSFF NY 2023 - The Call for Proposals is open and accepting submissions through Friday, June 23 at 11:59 PM. [Link](https://events.linuxfoundation.org/open-source-finance-forum-new-york/program/cfp/)
- [ ] CDM Development Operating Model - Comment and Next Steps
- [ ] PR Review - Submitters to present requested or proposed changes
- [ ] AOB, Q&A & Adjourn (5mins) 
  - @mcleo-d - CDM Talks at the FINOS Member Meeting - June 14th and 15th at JPMorgan Chase, Embankment, London
    - https://www.finos.org/hosted-events/2023-06-14-member-meeting-and-open-house

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1683054784909702&usg=AOvVaw3Rsuio_fWULs96SdD9FJxT)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1683054784909702&usg=AOvVaw3dWKkaMru7TSNyYrW9eTBX)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by dschwartznyc** [comment]
dan schwartz / FT Advisory

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA
