### ISSUE TITLE
Proposal: add Securities Lending roles to enum PartyRoleEnum

### ISSUE THREAD

**Issue by RonAtCFX** [finos/common-domain-model#2158]
Wihtin Securities Lending there is a common nomenclature to use the following rolese for parties, the proposal is to add the below to the enum PartyRoleEnum 

Lender                 "The party that lends out securities under stock lending arrangements as principal"
BeneficialOwner  "The party that lends out securities under stock lending arrangements via an Agent Lender"
Borrower             "The party that borrows securities under stock lending arrangements"

**Comment by chrisisla** [comment]
From a securities lending perspective I agree that being able to specify the lender and the borrower would be good. Adding Beneficial Owner is a good idea too.

@tomhealey-icma do you have any thoughts on this?

**Comment by tomhealey-icma** [comment]
I think adding these role enums would be useful although not typically used in repo transactions that use either buyer/seller or for SFTR purposes, collateral taker/collateral giver.

**Comment by chrisisla** [comment]
Hi @RonAtCFX,
The party roles suggested and agreed on this Issue have been included in the changes for #2340. Thank you for your suggestions, I will now close this Issue.
Thanks! Chris
