### ISSUE TITLE
FRAGMOS - remove condition "PrincipalAmount" that forces PrincipalAmount to exist inside PrincipalPayment

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2163]
**REQUEST** : to remove condition below :
![image](https://github.com/finos/common-domain-model/assets/92978493/2b59dad1-3200-45fe-959b-3273dfd2a2ea)

**RATIONALE** : there are business cases where the amount (also payerReceiver) is unknown for the Principal Payment, though we know a Principal Payment will occur and we aldo know the date. 

- As an example, in **CCS** with variying leg, by definition neither intermediary nor final payments are known in terms of amount and payerReceiver, because it will depend on the FX fixingh for each relevant date.
- Same use case for **NDCCS** : there will be only a final payment, but for the same reason that it depends on the FX Fixing that will occur, at trade inception neither payerReceiver nor the amount can be fixed yet

The current rule is thus excessive by forcing that forces PrincipalAmount to exist. In the two use case above described, it is impossible to define such PrincipalAmount, that being said we still want to populate the date as part of PrincipalPayment and use this item in order to document the fact we agree that a Principal Payment will occurr on that date.

**Comment by tomhealey-icma** [comment]
Seems like a reasonable change to make.

**Comment by lolabeis** [comment]
As per previous DPBE meeting (https://github.com/finos/common-domain-model/issues/2628):
Alternative proposal where the condition is implemented based on information found in `PayoutBase`
[Principal Payment Condition.pptx](https://github.com/finos/common-domain-model/files/15176447/Principal.Payment.Condition.pptx)

**Comment by JBZ-Fragmos** [comment]
Hello

Feedbacks :

Condition A (see below markup on Slide) is not applicable in practice because of

     *   (1) another condition which creates side-effect to the one being proposed
     *   and (2) some business cases e.g. nominal reinvestment, that is another example of product for which you know a PP will occur but you do not know the amount of such PP



  1.  See the condition "NotionalResetOnPerformancePayout" that exists at Payout level. This is preventing reset to exist for interestRatepayout, meaning Condition A would always be "true" thus still always forcing Final PP to exist for interestRatepayout, which is what we wanted to avoid.



To fix this, the first part of condition (below highlighted) from Payout level shall be removed, because it is obviously abusive : it is notably wrong in the case of a resettable CCS which varying leg does actually reset . ***@***.***


  1.  In case there is a reinvestment feature in the Trade terms, then there is an Final PP amount shall not be defined

To fix this : have no other idea than have no condition at all - we may discuss how to take such case into consideration, etc. but the list of product features for which condition would apply or not will be complex, and that mainly comes back to original Fragmos opinion that trying to have too restrictive conditions about PP will cause more problems in terms of modelling than the ones they are supposed to avoid...



Termsheet example :

[A yellow text on a white background  Description automatically generated]

Condition B (see below markup on Slide) that is based on assumption that "Initial PP always exists" is wrong : though Initial PP amount might be known, it does not mean related payment exists. Main use case is NDCCS : usually Final PP will be exchanged (possibly interim) abut no Initial PP exists for such product because at Trade inception, by definition the amount of each leg are equivalent via FX, yet for ND leg it would have to be delivered in the other currency leg, meaning both PP to be exchanged would be equal, that being 0 net exchange - hence no Initial PP exists for such product.


  *   To fix this : have no other idea than have no condition at all - but as above, you may want to complexify condition by taking into accoungt whether related product does qualify with Non-Deliverable features, etc. but same as for previous one : Fragmos point of view is that such conditions create more pbs than solutions...



[A screenshot of a computer  Description automatically generated]

**Comment by lolabeis** [comment]
@JBZ-Fragmos To come back on your points:

1. **`NotionalResetOnPerformancePayout` condition**. You're right, applying the condition to `interestRatePayout` seems abusive and invalid in the resettable CCS case. That said, the absence of `reset` in that case doesn't impact the `FinalPrincipalAmountExists` condition, because `priceQuantity -> quantitySchedule` itself does not exist (instead `quantityReference` and `quantityMultiplier` are populated).
2. **Reinvestment feature**. Isn't the application of that feature a case of `reset = True` in the quantity?
3. **Non-deliverabe CCS**. If `initialPrincipalPayment` is absent, the condition would not apply. But in any case, for a non-deliverable leg, the `principalPayment` should still be denominated as a known amount in the non-deliverable currency (e.g. KRW), regardless of the fact that this amount would be settled in another currency.

**Comment by lolabeis** [comment]
Changes approved at the [CDM Derivatives Products and Business Events Working Group - May 22nd, 2024](https://github.com/finos/common-domain-model/issues/2905)
