### ISSUE TITLE
Modelling master agreements

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2168]
I’ve been looking at how a master agreement could be modelled in the CDM. The focus has been on trying to keep the components as generic as possible so that there is no dependency on specific agreements or specific trade associations. 

Rather than looking at what the modelling could be I’ve been looking at how the JSON representation could look. I’m thinking something along these lines would work:

```
…
    "legalAgreementIdentification": {
        "agreementName": {
            "agreementType": "MasterAgreement",
            "masterAgreementType": "GMSLA"
        },
        "publisher": "ISLA",
        "vintage": "2000"
    },
    "agreementTerms": {
        "agreement": {
            "masterAgreementSchedule": {
                "masterAgreementElections": {
                    "clause": [ 
                        {
                            "identifier": "1234563863296369",	
                            "variantIdentifier": "10001",	
                            "name": "ExistingTransactions",	
                            "variables": [
                                {
                                    "name": "ReferenceAgreement",	
                                    "value": "GMSLA"		
                                },
                                {
                                    "name": "ReferenceAgreementDate",
                                    "value": "2023-10-11"	
                                }
                            ]
                        },
                        {
                         ... next clause
                        }
                    ]
                }
            }
        }
    }
…
```

The items under ```legalAgreementIdentification``` already exist in the model; the items under ```masterAgreementSchedule``` are the pieces that could be added to describe the legal agreement. 

Key points:

- ```clause``` is an array with cardinality of (1..*) i.e. there must be at least one clause in an agreement.
- Each ```clause``` will be made up of:
   - An ```identifier``` with cardinality (1..1). This will be a unique id. This allows a clause from any agreement to be identified without having to use its description etc. This allows the actual text of a clause to be kept outside of the model. It would make sense to have this as an enumerated list to prevent duplication/unintended reuse of an id.
   - A ```variantIdentifier``` with cardinality (1..1). Clauses can have several different variants which are required in order to determine the election of a clause. It might be good to associate the ```variantIdentifier``` to the clause ```identifier```
   - A ```name``` with cardinality (0..1). Textual description of the clause if needed. I think this would be best represented as a string.
- Each ```clause``` can also have a set of variables associated to it which further define the election. A ```variables``` array of cardinality (0..*) is thus required under ```clause```, which will be made up of:
   - A ```name``` with cardinality (1..1) 
   - A ```value``` with cardinality (1..1)
   - (should this list be named “variable” rather than “variables”? should we prefix name/value with variable to make it clearer?)

This is an initial suggestion and I would appreciate any feedback on the proposed structure. There is a lot to consider here from a design perspective so a meeting of the maintainers to discuss this would be a good idea.

**Comment by valdensmith** [comment]
Thanks Chris, this will be good to discuss in more detail when the maintainers meet soon to discuss various legal agreement topics. In the meantime I will review your comments and look at how we represent the ISDA CSA

**Comment by chrisisla** [comment]
Closing this now, will proceed with contributing the structure as above with a few minor tweaks.
