### ISSUE TITLE
Technology Architecture Working Group - June 8th

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2172]
# CDM  Technology Architecture Working Group

## Date
June 8th, 2023 - 9 am ET 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
     - [x]  https://github.com/finos/common-domain-model/issues/2142
- [x] Update on Initial projects
     - [x] Version Management and Build Process : 
        - [x] Spin up a task force to investigate the issue and make recommendations: **Dan**
        - [ ] Collate current understanding leveraging and expanding an initial draft of “CDM Getting Started”: **Tom**
           - Brought forward from 11th May meeting, no update
        - [x] Review current build process with REGnosys: **Chris to liaise with Hugo**
     - [x] Other:
        - [x] Preliminary analysis for use of Legend in modelling: **Chris and Tom**
          - Chris reached out to Tom but got no response. Appears topic has been picked up independently of the TAWG. 
- [x] CDM Build and Release Management
[FINOS - CDM Build and Release Management - Slides](https://github.com/finos/common-domain-model/files/11689692/FINOS.-.CDM.Build.and.Release.Management.pdf)
- [x] AOB, Q&A & Adjourn (5mins) 

## Decisions & Discussion points
- Approved minutes from previous meeting (11th May 2023)
- CDM Build and Release Management
  - Initial discussions on topic of Serialization
  - Currently uses JSON, structure can differ between versions of the CDM which is a problem
  - Suggestion to add version to the JSON as part of the serialization process
  - Hugo noted that current regression tests use JSON files which do not include the version in them
  - Going forward, if the version is included in the JSON then regression tests would need to be made version specific too
  - Further discussion required on granularity and location of versioning
- Windows build issue
  - There is a recurring problem when building the CDM on Windows
  - Generally related to differences in OS and character encoding
  - Hugo suggested that github actions may be able to help

## Action Items
- [x] CDM Build and Release Management: Create discussion topics for each item raised by Dan: **Dan**
- [x] Windows build Issue: Ask for feedback by Maoo on Issue 2176: **Chris**
- [ ] Brought forward from 11th May meeting: Collate current understanding leveraging and expanding an initial draft of “CDM Getting Started”: **Tom**

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09](https://www.google.com/url?q=https://zoom.us/j/99036410403?pwd%3DMXNINndYcEd0dTBUZERuYTFwRGpWZz09&sa=D&source=calendar&ust=1683922682114658&usg=AOvVaw2KKSMMROIGH16Y4_MZHqXk)

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: [https://zoom.us/u/adtpQBjgT9](https://www.google.com/url?q=https://zoom.us/u/adtpQBjgT9&sa=D&source=calendar&ust=1683922682114658&usg=AOvVaw0h2IXuikcBYejENKNAefbv)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

**Comment by RonAtCFX** [comment]
Ron Kaim @ CFX Consulting

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by lolabeis** [comment]
Leo Labeis, REGnosys

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FT Advisory

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by davidshone** [comment]
David Shone, ISLA

**Comment by smsant** [comment]
Sarah Santos, Carnegie Mellon

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend

**Comment by dschwartznyc** [comment]
[FINOS - CDM Build and Release Management.pdf](https://github.com/finos/common-domain-model/files/11689692/FINOS.-.CDM.Build.and.Release.Management.pdf)

**Comment by chrisisla** [comment]
Chris Rayner / ISLA
