### ISSUE TITLE
CDM Contribution Review WG - June 13th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2187]
# CDM  Contribution Review Working Group Minutes

## Date
June 13th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2147
- [ ] Discussion on specific PR proposed by ISLA
       - https://github.com/finos/common-domain-model/pull/2181 
- [ ] Implementation plan for previously discussed Development Operating Model for CDM
       - https://github.com/finos/common-domain-model/issues/2129
- [ ] Review of open PRs and highlighting issues of interest to maintainers
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1687012814857300&usg=AOvVaw0Zq9wD3enNiGoG1hjR7HHQ)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1687012814857300&usg=AOvVaw36gT6pj-tgnGSsAbHk2Xqr)

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by dschwartznyc** [comment]
Daniel Schwartz/FT Advisory

**Comment by d-sen-gupta** [comment]
Dhruva Sen Gupta/JPMC

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM/ISDA

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by eacunaISDA** [comment]
Eleonora Acuna / ISDA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by rvincentISDA** [comment]
Ruddy

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader
