### ISSUE TITLE
CDM Contribution Review WG - June 27th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2215]
# CDM  Contribution Review Working Group Minutes

## Date
June 27th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2187
- [x] Volunteer needed to define content for the [cdm.finos.org](http://cdm.finos.org/) homepage. Preview available here  https://heroic-starburst-9c64f5.netlify.app/. 
- [ ] PR Review
     - Add TripartyAgentEnum to PartyRoleEnum, [2207](https://github.com/finos/common-domain-model/pull/2207)
     - Add settlement party and role to settlement base, [2214](https://github.com/finos/common-domain-model/pull/2214)
     - Add tradeDateTime to Trade type and Execution Instruction, [2210](https://github.com/finos/common-domain-model/pull/2210)
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1688215505723318&usg=AOvVaw2BqDH9fQPSpsrl7EeO0oR5)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1688215505723318&usg=AOvVaw0XKOiRyrDiwfk0sxaJ-ayJ)

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / ISDA & GEM, observing

**Comment by minesh-s-patel** [comment]
Minesh Patel/ REGnosys / @minesh-s-patel

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FT Advisory

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziade / FRAGMOS-CHAIN

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by iansloyan** [comment]
ian sloyan / ISDA

**Comment by pritipal0601** [comment]
Priti Pal / RBC

**Comment by suyashyc** [comment]
Suyash Chaudhary / RBC

**Comment by eacunaISDA** [comment]
Eleonora / ISDA
