### ISSUE TITLE
Python - serialisation of Enum classes

### ISSUE THREAD

**Issue by vjuge** [finos/common-domain-model#2233]
Please introduce slight modification in python distribution, in order to allow json `dumps` serialization of classes derived from Enum.

for instance, an enum which contains only strings (the same approach is applicable for enum made of int, etc)
```python
from enum import Enum

class PartyIdentifierTypeEnum(Enum): 
```

python 3.11+ would require
```python
from enum import StrEnum

class PartyIdentifierTypeEnum(StrEnum): 
```

while python 3.9+ would require
```python
from enum import Enum

class PartyIdentifierTypeEnum(str, Enum): 
```

the later is a preferred solution imo, since it would be compatible with more configurations. (what's the required python version for using cdm, if any ?)

**Comment by SimonCockx** [comment]
Hi @vjuge. I think your last proposal is certainly a good one.

I just wanted to add though that serializing via `dumps` is not the recommended way, and may lead to superfluous empty lists, as highlighted in issue https://github.com/finos/common-domain-model/issues/2186. Using Pydantic with the option `use_enum_values` (and `exclude_defaults` to skip empty lists) will result in the same behaviour as your proposal, without any changes to the Python code.

**Comment by vjuge** [comment]
hi @SimonCockx thanks for the hint, makes sense

**Comment by dschwartznyc** [comment]
to close out the version question - the python CDM implementation expects v3.10+

**Comment by lolabeis** [comment]
And good to see you back at the top of your CDM game @vjuge ! :-)
