### ISSUE TITLE
Modelling Master Agreements

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2235]
Please refer to PR #2234 which holds the development described in this Issue. A previous Issue was created (#2168) where a preliminary version of the development was offered up for feedback.

The new types described in the Pull Request referenced at the top of this Issue allow a master agreement to be represented as generic types and with no actual agreement details being held in the object data itself. An example of a simple master agreement clause using this modelling would be as below:

```
…
    "legalAgreementIdentification": {
        "agreementName": {
            "agreementType": "MasterAgreement",
            "masterAgreementType": "GMSLA"
        },
        "publisher": "ISLA",
        "vintage": "2010"
    },
    "agreementTerms": {
        "agreement": {
            "masterAgreementSchedule": {
                "clause": [ 
                    {
                        "identifier": "ISLA_GMSLA_021",	
                        "name": "DefaultInterestRate",	
                        "variant”: [
                            {
                                “identifier": "ISLA_GMSLA_021_03",	
                                "variableSet": [
                                    {
                                        "name": "RATE_DEF",	
                                        "value": "the Prime Rate as quoted by [RATE_PUB] from time to time"		
                                    },
                                    {
                                        "name": "RATE_PUB",
                                        "value": "the European Central Bank"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                         ... next clause
                    }
                ]
            }
        }
    }
…
```

The items under ```legalAgreementIdentification``` already exist in the model; the items under ```masterAgreementSchedule``` are the pieces that have been added to describe the legal agreement. 

**Key points**

- Some key points about clauses:
   - ```clause``` is an array with cardinality of (1..*) i.e. there must be at least one clause in an agreement.
   - A ```clause``` must contain an ```identifier``` as it has cardinality (1..1). This will be a unique id. This allows a clause from any agreement to be identified without having to use its description etc. This allows the actual full text of a clause to be kept outside of the model. An enumerated list has been used to hold the identifiers – a discussion into the advantages/disadvantages of this approach has been provided below.
   - A ```variant``` array must also be included, its cardinality being (1..*). Clauses can have several different variants which are required in order to determine the election of a clause. It is also possible for a clause to assign different variants to different parties, meaning that we need ```variant``` to be an array.
- Some key points about variants:
   - A ```variant``` must also include an ```identifier```. This has the same structure as the ```clause``` ```identifier``` but with an additional suffix (this is explained in more detail on the PR documentation). 
   - A ```name``` with cardinality (0..1). Textual description of the clause if needed. 
- Each ```variant``` can also have a set of variables associated to it which further define the election. A ```variableSet``` array of cardinality (0..*) is thus required under ```variant```.
- Some key points about variables:
   - The ```variableSet``` array will most frequently be made up of:
      - A ```name``` with cardinality (1..1) 
      - A ```value``` with cardinality (1..1)
   - There are variants that require tables of variables so ```variableSet``` includes a call to itself to allow nested arrays to be defined (thus this new type is named ```variableSet``` and not ```variables``` for example).

**A note on Parties**
Umbrella agreements can often require clauses to be defined as specific to certain parties. It is also possible that variants will be applied to specific parties. For these reasons the ```party``` and ```partyRole``` items have been added under the ```clause``` and ```variant``` items. 

It is not clear at this time where/when a Party would be used rather than a Party Role, thus, to provide flexibility, both types have been included in the design.

**Identifiers**
The suggestion is that the ```clause``` and ```variant``` Identifiers are defined in enumerated lists in the model. 

The advantage of this is that it is then clear to everyone using the model what documents are supported by this structure. It also allows other documentation publishers (i.e. not one of the 3 trade associations ISLA, ISDA and ICMA) to see the preferred identifier structure and to ensure they do not reuse an existing id.

The disadvantage is that the lists could become quite long, especially when the clauses and variants from all the core master agreements (i.e. the GMSLA, ISDAMaster and GMRA) are all supported. 

It might be feasible to use the functionality exposed by the [docReference] clause to access lists of data outside of the model to alleviate this problem. 

In reality though, there is no actual need to define the identifiers in the model itself. The identifiers could be described in the associated clause library documentation itself so there could be no restriction on what is put into these fields in the model. So as long as a consumer has a copy of the clause library documentation they will know what clause and variant identifiers they will need to put in their objects, and how to process legal agreement documents that they receive. 

If the decision is taken to not use enumerated lists to store the identifiers then we can reuse the ```AssignedIdentifier``` type for the ```clause``` and ```variant``` identifiers.

**Comment by chrisisla** [comment]
The structure described in this Issue has been adapted slightly in a later version of the changes, contributed in #2340. No feedback was received on this Issue so I am assuming everything was acceptable. I will close this Issue now to prevent clutter.

**Comment by lolabeis** [comment]
Reopening and linking to the new PR, as discussed
