### ISSUE TITLE
CDM Structured Products WG - July  11th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2242]
# CDM Structured Products Working Group Minutes

## Date
July 11th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2141
- [ ] Speech from new joiners from BBG
- [ ] Gap Analysis for representing TS provided by RBC with current CDM (depending on time we have, see how new modelling would work to properly represent these TS)
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09](https://www.google.com/url?q=https://zoom.us/j/92136087343?pwd%3DVER4aW83TC9HNDVxbXU3UUkxU1BoUT09&sa=D&source=calendar&ust=1689005586558562&usg=AOvVaw1um_oNGG1VpYfu0sUxHRFo)

Meeting ID: 921 3608 7343
Passcode: 861434
Find your local number: [https://zoom.us/u/ad5NMLeH9R](https://www.google.com/url?q=https://zoom.us/u/ad5NMLeH9R&sa=D&source=calendar&ust=1689005586558562&usg=AOvVaw34CSBIZqR1vtIUaVielqFE)

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by eteridvalishvili** [comment]
Eteri / FINOS
