### ISSUE TITLE
 Inaugural CDM Steering WG - July 11th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2243]
# CDM Steering Working Group Minutes

## Date
July 11th, 2023 - 11am ET / 4pm GMT

## Untracked attendees
- Miles Barker / Credit Suisse

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] 1. Review Meeting Notices (see above)
- [ ] 2. Presentation of roadmaps of expected contributions to CDM sponsored by ISDA, ISLA and ICMA in 2023 
- [ ] 3. Discussion on CDM Development Operating Model  (https://github.com/orgs/finos/projects/70/views/1)
          - Agreement/direction needed on components of operating model
          - Agreement/direction needed on target date for completion/implementation
- [ ] 4. Discussion on CDM Major version/production releases and role of CDM Steering WG
         - Should the Steering WG approve each instance or publish a fixed calendar of release dates?
- [ ] 5. Priority areas for the CDM Technology Architecture WG to look at in 2023
             - On what topics should the WG provide recommendations to Steering WG?
             - Initial discussion underway on CDM serialisation (https://github.com/finos/common-domain-model/discussions/2180)
- [ ] 6. Attendance and representation at working groups
             - What are Steering WG recommendations to improve WG attendance in short and long term?
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/97761331363?pwd=elVScWZ2N2dRTGxjMHE1VTdkYldXZz09](https://www.google.com/url?q=https://zoom.us/j/97761331363?pwd%3DelVScWZ2N2dRTGxjMHE1VTdkYldXZz09&sa=D&source=calendar&ust=1689005586558562&usg=AOvVaw2taTZPSuX5Xg3LrYthdYQy)

Meeting ID: 977 6133 1363
Passcode: 937042
Find your local number: [https://zoom.us/u/abmfbv68ZV](https://www.google.com/url?q=https://zoom.us/u/abmfbv68ZV&sa=D&source=calendar&ust=1689005586558562&usg=AOvVaw3aa3rFS6zORoPDhQ-PcE1J)

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by RonAtCFX** [comment]
Ron Kaim /  CFX Consulting

**Comment by valdensmith** [comment]
Vernon ISDA in attendance

**Comment by brianlynn2** [comment]
Brian Lynn / GEM/ISDA

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by davidshone** [comment]
David Shone / ISLA

**Comment by DIVA291265** [comment]
Daniel Ivanier / Fragmos Chain

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by dschwartznyc** [comment]
Daniel schwartz /FT Advisory

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by ADaleISLA** [comment]
Adrian Dale / ISLA
