### ISSUE TITLE
CDM Collateral WG - July 18th 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2254]
# CDM Collateral Working Group Minutes

## Date
July 18th, 2023 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] FINOS Open Source in Financial Services annual survey https://www.research.net/r/SXGZ9KB
- [x] Approve past meeting minutes
       - https://github.com/finos/common-domain-model/issues/2146     
- [x] Meeting Slides
[ISDA Common Domain Model - Collateral WG 18th July 2023.pdf](https://github.com/finos/common-domain-model/files/12050250/ISDA.Common.Domain.Model.-.Collateral.WG.18th.July.2023.pdf)
- [x] 1. Member Update on CDM Implementation – Vermeg  
- [x] 2. Cash Collateral Interest Contribution Completed 
- [x] 3. Update on Securities Lending Collateral Provisions 
- [x] 4. Eligible Collateral Validation use case 
Finos Hackathon overview (NY and LDN 3rd and 4th May) 
CDM Function build and demo 
- [x] 5. Updates on CDM Collateral adoption for H2 2023 
- [x] 6. Barclays RepoHack 2023 : 
https://protect-usb.mimecast.com/s/Q08eCjA9x0fzl2GQSRV9t6?domain=creativeservices.barclays/
Register: [https://www.creativeservices.barclays/ehome/repohack2023/register/](https://protect-usb.mimecast.com/s/Ov_RCk60yrIDY7XzHQPVE1?domain=creativeservices.barclays/)
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items

Action 1:
As referenced in agenda item No 2 - The Cash Collateral Interest Contribution to the CDM has taken place. Members are encouraged to review the structure in the CDM under the data type `DistributionAndInterestPayment`. It would be of benefit to identify and confirm valid use cases to test the model in this area using industry examples. Please contact [valdenmsith@isda.org](mailto:valdenmsith@isda.org) if of interest to your organization.

Action 2:
As referenced in agenda item No 3 – Collateral Provisions. The various scenarios were discussed on how best to identify a trade as a Repo or Sec Lending position. Using a master document to confirm the trade type is not possible as there are cases where a Repo trade for example can be governed by a bespoke or undocumented agreement. A better option would be to use the product qualifier in CDM on the trade/positions itself. ISLA and ICMA will explore this with their members and work towards implementing in the CDM. In turn this will enable a condition to be added to Collateral Provisions to differentiate between Sec lending and Repo trades.

Action 3:
As referenced in agenda item No 4 – Overview of the Eligible Collateral validation use case developed during the Finos Hackathon (NY and LDN 3rd and 4th May 2023) Along with the CDM Function build and demo. 
Please contact [valdenmsith@isda.org](mailto:valdenmsith@isda.org) if you are interested in developing the Collateral validation use case further in the CDM.

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09](https://www.google.com/url?q=https://zoom.us/j/96084284579?pwd%3DQTJ3bTBrMURkWXA1S0owa1djaEVIUT09&sa=D&source=calendar&ust=1689519517677795&usg=AOvVaw3kkutNuZopWLEBFt1TxdCh)

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: [https://zoom.us/u/aoBkYnW9l](https://www.google.com/url?q=https://zoom.us/u/aoBkYnW9l&sa=D&source=calendar&ust=1689519517677795&usg=AOvVaw3bNi4E-qqhzXoR5cRcSWby)

**Comment by valdensmith** [comment]
Vernon Alden-Smith ISDA

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by AmyCaruso** [comment]
Amy Caruso/ISDA

**Comment by minesh-s-patel** [comment]
Minesh Patel / @minesh-s-patel / REGnosys

**Comment by criss11fr** [comment]
Cris Searle - Clearstream

**Comment by AsmaBGH** [comment]
Asma BELGAIED HASSINE/Vermeg

**Comment by tabi5h** [comment]
Tabish Ahmed / ISDA

**Comment by ADaleISLA** [comment]
Adrian Dale / ISLA

**Comment by jzinnegger** [comment]
Joerg Zinnegger / Z-FRM

**Comment by MarkNew-ISDA** [comment]
Mark New/ISDA
