### ISSUE TITLE
Add qualification function for Zero-Strike equity swaps

### ISSUE THREAD

**Issue by ebataller** [finos/common-domain-model#2266]
### Context
The Zero-Strike equity swaps do not have a qualification function in CDM, but these trades should be reportable and qualified accordingly.
To cover the principal payments of zero-strike swaps, synonym mappings from FpML to CDM need to be updated and existing types like `PrincipalPayments` need to be extended.

### Proposal
To solve this, PR [#2267](https://github.com/finos/common-domain-model/pull/2267) adds this qualifying function for Zero-Strike swaps, checking for the existance of total return terms, a single `performancePayout` and the `principalPaymentDescriptions` attribute.

This proposal also includes the synonym mappings and types updates of `PrincipalPayments`, `PrincipalPaymentSchedule` and `PrincipalPayment`, adding the necessary attributes in `principalPaymentDescriptions` to represent and qualify equity zero-strike swaps. Detailed types update description below.

To `PrincipalPayment` type, the following attributes were added:
- `principalPaymentDescriptionDate`, of type `AdjustableOrRelativeDate` (0..1), to represent the adjustable or relative dates from zero-strike swaps.
- `determinationMethod`, of type `DeterminationMethodEnum` (0..1) and `amountRelativeTo`, which is a reference of type `Money` (0..1);
both added to represent the alternative ways of showing the principal amount in zero-strike swaps.

Also, an optional choice condition was added between the `principalPaymentDate` and the `principalPaymentDescriptionDate`
and the required choice condition for the principal amount was expanded by adding the 2 new attributes determinationMethod and `amountRelativeTo`.

To `PrincipalPayments` type, the following attribute was added:
- `principalPaymentDescription`, of type `PrincipalPaymentSchedule` (0..1) was added to differenciate the representation of different elements from FpML in CDM.
`principalPaymentDescriptions` is representing the `principalExchangeDescriptions` inside a `returnSwap`, while `principalPaymentSchedule` is representing the `cashflows` in a `swapStream`.

To `PrincipalPaymentSchedule` type, the following attribute was updated:
- `intermediatePrincipalPayment` attribute had its type and cardinality changed from `AdjustableRelativeOrPeriodicDates` (0..1) to `PrincipalPayment` (0..*).

Also the necessary mapping synonyms from FpML to CDM were added.

**Comment by manel-martos** [comment]
Hello,
@finos-admin 

This issue is linked to PR #2267 
Please add the following labels to this issue.

Minor Enhancement/Change
Category: Modelling
Criticality: Medium
Complexity: Low
Target: Development

**Comment by eteridvalishvili** [comment]
Hi @manel-martos and @ebataller As the PR linked to this issue has been resolved, am I okay to close? Please let me know if there is anything I can do to help with the next steps. Thanks!

**Comment by ebataller** [comment]
Yes I will close this, thank you!
