### ISSUE TITLE
CDM Contribution Review WG - July 25th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2277]
# CDM  Contribution Review Working Group Minutes

## Date
July 25th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Jean-Baptiste Ziade, FRAGMOS

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2215
- [x] **CDM Development Operating Model** 
         - Follow up meeting held to discuss operational process last week. Participants agreed to hold ad-hoc pre-contribution review meetings for a deep dive into proposed model changes. 
         - Contributors (individual or WG) should take active efforts to ensure an issue with sufficient information is associated with PR, that subject matter experts have reviewed any changes and if a major change that ad-hoc pre contribution meeting to educate maintainers so that their approval is straight forward
         - Further discussion to finalise and define the Operating Model and specifically on Release categorization and scheduling (e.g. Prod vs Dev) & Service Level Expectation/Agreement in 2 weeks with goal to implement fully by end of August.
- [x] **PR Review and highlights**
          - https://github.com/finos/common-domain-model/pulls
- [x] **The 2023 State of Open Source in Financial Services survey is live!** [Take the survey now](https://t.sidekickopen53.com/Ctc/RE+23284/chmM804/Jks2-6q7W69sMD-6lZ3pSW2Q2y152d9Z60W92DJNd53TkbjW1ybDdT6nXhrxW6-3xW249ZV_yW16L0x149NWBRN1DBS6nPZhV4W8L7l-X1zj9vmW6TW5xF5Smz9DW2xrCWp2rJHgFW8Rzytb32Hqq6W1_mDgC1KZVGfW7NwsqD5DFJNXW5xgyqy8zrV6mW70tX-f6V2qgCW2f2SBP66PhbbW2h4btZ1Kb3m3W6-xkJP8LbtPhW1QYKKV6VKDBPW68F0CG5ykH-sW23fT2r6GXyd-f58G8QK04) before it closes on August 5th!
- [x] https://github.com/finos/common-domain-model/issues/2058 next steps
- [x] https://github.com/finos/common-domain-model/issues/2176#issuecomment-1640106158
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1690232037968300&usg=AOvVaw3_roCXshkJ3gnyPB27bNTW)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1690232037968300&usg=AOvVaw1GFVQtk_lPo_dbNSLFZBqs)

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by adamulman** [comment]
Adam Ulman / SmartStream

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by mikealambert** [comment]
Mike Lambert - Broadridge

**Comment by brianlynn2** [comment]
Brian Lynn / GEM/ISDA

**Comment by jzinnegger** [comment]
Joerg Zinnegger / Z-FRM

**Comment by iansloyan** [comment]
Ian Sloyan / ISDA

**Comment by tabi5h** [comment]
Tabish Ahmed/ISDA

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory

**Comment by d-sen-gupta** [comment]
Dhruva / JPM

**Comment by dharm-kapadia** [comment]
Dharm Kapadia / EquiLend

**Comment by ebataller** [comment]
Eric Bataller / Tradeheader

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by suyashyc** [comment]
Suyash Chaudhary / RBC
