### ISSUE TITLE
CDM Contribution Review WG - August 1st, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2289]
# CDM Contribution Review Working Group Minutes

## Date
August 1st, 2023 - 10 am ET / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2277
- [x] Use of "Ready to Release" label
- [x] Review PRs
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [x] Chris: Add Agenda items to the next Technology Architecture WG:
  - Review Issue #2269 
  - Review Issue #2015 
  - Review PR #2256
- [ ] Labelling PRs
  - Who can add labels to PRs? Permissions required?
  - How do we categorise PRs? E.g. draft changes for review vs final changes vs discussions
  - Who can close a PR? Permissions required?
  - Can a glossary of the labels and how/when to use them be added to the CDM landing page?
  - Can we have a worked example showing the PR workflow including labels?

### Zoom info
Join Zoom Meeting
[https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09](https://www.google.com/url?q=https://zoom.us/j/96436091087?pwd%3DTUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09&sa=D&source=calendar&ust=1690921968481493&usg=AOvVaw1jQKp6so2RNf3EMik-7y02)

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: [https://zoom.us/u/a3KWGNquN](https://www.google.com/url?q=https://zoom.us/u/a3KWGNquN&sa=D&source=calendar&ust=1690921968481493&usg=AOvVaw37H3mdgVaZpRT6BBVkG9LZ)

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by RonAtCFX** [comment]
Ron Kaim / CFX Consulting

**Comment by mmani99** [comment]
Mani Pillai / otcDigital

**Comment by brianlynn2** [comment]
Brian Lynn / ISDA & GEM

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by Alexis25091972** [comment]
Alexis Lucas / BNY Mellon
