### ISSUE TITLE
Adding commodity classification to CommodityPayout

### ISSUE THREAD

**Issue by mgratacos** [finos/common-domain-model#2295]
### Context
EMIR Refit has the reporting requirement to report the commodity classification in three layers:
a) Commodity Base (EMIR 2.116 Base Product)
b) Commodity Sub-Product (EMIR 2.117 Sub-Product)
c) Commodity Further Sub-Product (EMIR 2.116 Further Sub-Product

Currently there is no support for this in CDM. This is specific for commodity products, for both financially and physically settled commodities.

### Proposal
The proposal is to use an N-layer generic structure using the existing `Taxonomy` data type. Specifically the proposed implementation re-uses the existing `Taxonomy` data type that was originally designed to represented layered classification within a taxonomy. 
- It adds a new `commodityClassification` attribute inside `CommodityPayout`.
- `commodityClassification` is of type `Taxonomy` and it is repeatable.
- Adds a new ordinal attribute within `TaxonomyClassification`.
- Continues using `source` to identify which classification system a set of codes/layers belongs to (ex: set NRGY-OILPBRENT belongs to EMIR).

Pros: Minimal changes and addresses any hierarchical depth. It caters for ISDA V1, V2 and will support Commodity
taxonomies from EMIR and ISDA’s CRP and any others.

<img width="1071" alt="Screenshot 2023-08-02 at 21 09 03" src="https://github.com/finos/common-domain-model/assets/6411070/7ec11789-50a3-4932-92f2-5f932560419d">

<img width="1001" alt="Screenshot 2023-08-02 at 21 29 28" src="https://github.com/finos/common-domain-model/assets/6411070/65165a89-3afa-4291-a287-1c4fb84b3585">

**Comment by mgratacos** [comment]
Labels:
Minor Enhancement/Change
Category: Modelling
Criticality: High
Complexity: Low
Target: Development

**Comment by iansloyan** [comment]
There is a taxonomy type in Commodity which is inherited from productbase - why can this not be done via that type/attribute?
