### ISSUE TITLE
Adding support for Exchange Traded Derivatives to CDM Core

### ISSUE THREAD

**Issue by rogerguitart** [finos/common-domain-model#2299]
## Context

Over the course of the last two months, the _Derivative Products and Business Events Working Group_ has convened on a weekly basis to delve into modelling **Exchange Traded Derivatives** (ETDs) within the CDM framework. These conversations have resulted in the creation of an `exchangeTradedProduct` in CDM. Furthermore, to make certain fields usable for both ETDs and OTC products, the `optionPayout` and `exerciseTerms` components have been refactored. 

### Overview

The proposal consists of:
- An **_ExchangeTradedProduct_** that extends `ProductBase` (fields in brackets in image below)
- The composition between either an exchange traded _future_ attribute and an exchange traded _option_ attribute
    - A **_one-of_** condition will ensure that either `future` or `option` are chosen, but not both (as seen in the code below)
- The **refactoring** of the `OptionPayout` into an `OptionPayoutBase` with normalized `ExerciseTerms` that cover both OTC and ETD options
<img width="597" alt="etdPic1" src="https://github.com/finos/common-domain-model/assets/141412602/569f0bc0-c932-4de4-b984-73fb608ffc9f">
<img width="662" alt="etdPic2" src="https://github.com/finos/common-domain-model/assets/141412602/7aa738bc-b142-495b-a7a1-b3dbb85e9ec7">

### ExchangeTradedProduct Type

The _ExchangeTradedProduct_ type is made up of a mandatory choice between an option or a future, along with the optional fields `productIdentifier` and `productTaxonomy` (extended from `ProductBase`).
- The `future` attribute of type `FuturePayout` extends `PayoutBase` (green box below), and contains _expirationDate_ along with the description of the _underlier_
- The `option` attribute of type `OptionPayoutBase` extends `PayoutBase` (green box below), and contains _exerciseTerms_, _strike_, and _optionType_, along with the description of the _underlier_
<img width="469" alt="etdPic3" src="https://github.com/finos/common-domain-model/assets/141412602/7afa897c-2d84-4599-ba4e-cedfe67a225a">

### Refactoring of ExerciseTerms

The `exerciseTerms` is now of type _Exercise_, and its representation for an option has been **normalized** across ETDs and OTC products.

A new simplified enum has been created for the `style` of the option: _ExerciseStyleEnum_ → This enum simplifies option style, given that a lot of information required for OTCs is not expected in ETOs
- **Pro**: This approach minimizes changes on the OptionPayout and avoids changes on the cardinality of certain mandatory fields
<img width="713" alt="etdPic4" src="https://github.com/finos/common-domain-model/assets/141412602/9e10940d-3175-4b22-a387-3d932e922ea7">

For a comparison between the previous option exercise terms and the new normalized `Exercise`, please see image below. As is shown, the complexity of the fields `americanExercise`, `europeanExercise`, and `bermudaExercise` has been greatly reduced:
<img width="651" alt="etdPic5" src="https://github.com/finos/common-domain-model/assets/141412602/071c2abb-c704-49e4-97b6-c903aa0b95e1">

### Refactoring of OptionPayout

The `OptionPayout` structure within CDM has been harmonized with a new `OptionPayoutBase` type that collects features common across OTC and ETD products. Additionally, the `OptionPayoutBase` also extends `PayoutBase`:
<img width="616" alt="etdPic6" src="https://github.com/finos/common-domain-model/assets/141412602/84190f78-1992-410a-8f82-9233825f0bb1">

**Comment by rogerguitart** [comment]
Labels:
Minor Enhancement/Change
Category: Modelling
Criticality: High
Complexity: Low
Target: Development

**Comment by mgratacos** [comment]
See updated PR to address the ETD representation using the existing payouts: https://github.com/finos/common-domain-model/pull/2342

The options refactoring will be addressed in a separate issue and PR.
