### ISSUE TITLE
Object required in CDM to capture Index names required for regulatory reporting

### ISSUE THREAD

**Issue by winitall01** [finos/common-domain-model#2307]
# Context
Generic object required in CDM to capture Index names required for regulatory reporting

# Background
ESMA EMIR Reporting requires reporting of index names for following fields:

1. `2.85 - Name of the floating rate of leg 1`
2. `2.101 - Name of the floating rate of leg 2`
3. `2.16 - Name of the underlying index`

Currently, there’s no option for capturing index names for the floating rate legs and the underlying index in CDM. 

# Proposal

## _Summary_
This proposal intends to utilise and rearranging existing CDM objects to resolve the issue of capturing index namexs. 

Currently, CDM has a type object named as `IndexReferenceInformation` 
![image](https://github.com/finos/common-domain-model/assets/84881498/e9d4c64e-9eea-4025-ac76-0b4fd74f2686)
This attribute is currently defined to capture information required of Credit Default Swap Index. 

Additionally, there's a type object named as Index which is currently used in EMIR jurisdiction rule modelling to deduce index nmae. Type `Index` is CDM extends `Product base` but contain no attributes of its own. 
![image](https://github.com/finos/common-domain-model/assets/84881498/69dd15cb-eec9-479c-a623-a4925008fa3d)

### Step 1: Split ‘IndexReferenceInformation’ into 
1. Generic ‘IndexReferenceInformation’ - to capture generic index related information
2. Specfic ‘AdditionalIndexReferenceInformation’ - to capture specific index related information required for CDS
![image](https://github.com/finos/common-domain-model/assets/84881498/0910fd91-5879-4e73-96c7-c2327c3429fb)

### Step 2: use ‘IndexReferenceInformation’ in type Index as
![image](https://github.com/finos/common-domain-model/assets/84881498/8b803ab1-2974-4146-a142-e0e5d52a67cd)
This could resolve the requirement of `2.16 - Name of the underlying index` 

### Step 3: Include ‘IndexReferenceInformation’ in FloatingRateOption
![image](https://github.com/finos/common-domain-model/assets/84881498/f704c837-8cc3-49c7-84b9-9de24a0aa9bd)
This will resolve the requirement of supplying names for Floating Rate Legs as required for fields 2.85 and 2.101.

**Comment by rvincentISDA** [comment]
Could you increase the size of the screenshot. It is not legible currently.

**Comment by rvincentISDA** [comment]
To clarify my suggestion:
![image](https://github.com/finos/common-domain-model/assets/66018066/282dd8ef-7e46-4d76-ae03-97a438ce275d)

**Comment by rvincentISDA** [comment]
![image](https://github.com/finos/common-domain-model/assets/66018066/751070e9-ac7a-4322-be5e-b375201c7353)

**Comment by hugohills-regnosys** [comment]
> 

This proposes the following incorrect type hierarchy:
- `FloatingRateOption` extends `Index` extends `ProductBase` - which is wrong because it would mean a `FloatingRateOption` was effectively a product.  i.e. it inherits both `productIdentifier` and `productTaxomony` attributes from `ProductBase`
- `CreditIndexReferenceInformation` extends `Index` extends `ProductBase` - which is wrong because it would mean a `CreditIndexReferenceInformation` was effectively a product.  i.e. it inherits both `productIdentifier` and `productTaxomony` attributes from `ProductBase`

Neither `FloatingRateOption` or `CreditIndexReferenceInformation` should extend `ProductBase`.

**Comment by rvincentISDA** [comment]
Thanks Hugo. Maybe we should get others' perspectives. 

The association to ProductBase by extension does  not make a data type the super type product. It is only associating a list of possible Identifiers and a taxonomy.  The design will most like have to also categorise the Identifiers (ISIN, FIGI etc) similarly to the structural definition of ProductBase. ESMA for example requires to report the ISIN of an FRO. 

Maybe it's ProductBase that carries the wrong name and is overloaded with purposes?

**Comment by lolabeis** [comment]
We should separate the short-term change (driven by immediate DRR requirements) vs the target state.

In the target state, `Index` extending `ProductBase` (and then `CreditIndexReferenceInformation`, `FloatingRateOption` both extending `Index`) is possibly where we want to be.

In the short-term, doing this without any further refactoring of `ProductBase` attributes has the disadvantage that @hugohills-regnosys mentioned. In addition, it would introduce the confusion that `Index` identifiers could be set along 2 different paths:
- the `productIdentifier` attribute, which is the existing one used in production e.g. for equity index
- the new `indexName` and `indexId` attributes

This inconsistency could be addressed by harmonising `productIdentifier` and `indexName` / `indexId`, indeed along the lines suggested by @rvincentISDA. However, this is not a change that can be built in the short-term. In fact, it is related to the broader issue re `Observable` (https://github.com/finos/common-domain-model/issues/2106), which also raises the question of `Product` vs `Observable` (arguably an index is more the latter than the former). Absent that harmonisation, the benefit of hosting both cases under a single `Index` object is limited as their treatment needs to be forked anyway, whereas there are clear drawbacks.

Given the proposed change's impact on DRR, whereby reporting of certain index fields is currently blocked, we should proceed with the proposed short-term change while taking note of the aspirational target state.

**Comment by iansloyan** [comment]
Thank you for presenting the issue to us @lolabeis @winitall01 

If we hone in on the problem being solved - _FloatingRateOption_ is missing id and name of the floating rate index. So to fix that we are inserting an improved _IndexReferenceInformation_ attribute which can store those details. This attribute should be available in Index today but is not. 

I think we are good to proceed on this basis with the related PR **on condition that an issue is raised** to solve the longer term issue add _IndexReferenceInformation_ to Index, have _FloatingRateOption_ extend or be of type Index, and deal with any refactoring or duplication in _IndexReferenceInformation_ with _productIdentifier_ and _productTaxonomy_ which is inherited into index from product base. (Keeping the symmetry of product type usage in place with each product/instrument having taxonomy + product id inherited from base)  
A projected date for when that could be completed would also be welcome.

**Comment by lolabeis** [comment]
Thank you @iansloyan @chrisisla. A new issue has been raised accordingly. ☝️ 

For good audit trail purposes, can I ask you both to formally click on "Approve" for PR #2336, before we merge?
