### ISSUE TITLE
Adding spreadCalculationMethod to InterestRatePayout

### ISSUE THREAD

**Issue by ben-aubry** [finos/common-domain-model#2315]
**Background**:
Currently the CDM implementation for the InterestRatePayout does not support a field called spreadCalculationMethod. This field is usually used for asset swaps. For example, in the case of interest rate derivatives, an inflation asset swap is a common structure. 

**Solution**:
The below PR has been committed to solve for the above. 
https://github.com/finos/common-domain-model/pull/2311

**Comment by ankitkulkarni1** [comment]
#2311 had some merge conflicts - the changes are now in #2332 

Thanks!

**Comment by eteridvalishvili** [comment]
Hi @ankitkulkarni1 and @ben-aubry It seems that the pull requests linked to this issue are either closed or have merge conflicts. Can we close this issue, or do you want to link another PR or need feedback from the maintainers? Also, please let me know if you want any labels added to this issue. I am looking forward to hearing from you. Thank you!

**Comment by ankitkulkarni1** [comment]
@eteridvalishvili this can be closed. https://github.com/finos/common-domain-model/pull/2332 was merged with the same changes. There is a typo in my previous comment - I meant to tag this MR instead of 2311.

**Comment by eteridvalishvili** [comment]
Hi @ankitkulkarni1 Thank you for confirming!
