### ISSUE TITLE
Adding "Delegation Reporting Agreement" to Agreement Type

### ISSUE THREAD

**Issue by winitall01** [finos/common-domain-model#2322]
# *Context* 
Pursuant to Article 9 of the European Market Infrastructure Regulation, some counterparties parties who enter into, modify or terminate certain derivatives transactions sometimes delegate their reporting requirements to another entity who offers delegated reporting services. Currently, there's a gap in CDM to record the presence of report Delegation Agreement between parties. 

# *Proposal*
Build a type to record Delegated Reporting Agreement with following attributes:
	1	`externalReportDelegation` - This Boolean type flag establishes the presence of Reporting Delegation Agreement between Reporting Counterparty and an external `Report submitting Entity`.
	2	`internalReportDelegation` - This Boolean type flag establishes the presence of a reporting agreement between the trading Counterparties themselves. E.g: for a trade between a FC and NFC-, the FC is expected to report the trade on behalf of NFC-, however, presence of a "internalReportDelegation" flag between a FC and NFC- signifies that FC is "NOT" required to report on behalf of NFC- and NFC- is expected to report on it own. Similarly, for a trade between a FC and NFC+, the NFC+ is also expected to report the trade, however, presence of a "internalReportDelegation" flag between a FC and NFC+ signifies that NFC+ has delegated the reporting requirement to FC.

**Comment by winitall01** [comment]
Closing this issue to incorporate the suggestion made during Peer Review discussion on Aug 23' 2003.

**Comment by winitall01** [comment]
@lolabeis @hugohills-regnosys - can you please add labels to this issue.

**Comment by rvincentISDA** [comment]
Could you expand on where will that information ought be documented in CDM ? 

A delegated reporting arrangement usually does not pertain to the trade details, could you also expand what would be the disadvantage in representing that regulatory and jurisdiction specific information in the DRR model rather than CDM? DRR does seem the natural place.

**Comment by lolabeis** [comment]
Implemented via a different approach in DRR
