### ISSUE TITLE
FRAGMOS * whole Model benefit + required for Struct * - improve current "meta" ref behavior (from "cancel/replace" effect to "smart additive" effect)

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2338]
### **PROBLEM STATEMENT**

**current behavior** of **"meta" resolving mecanism** is to have ### **cancel & replace** effect on any existing values that might be already present in the address object with the values attached to the object with the related meta.address

with an example, this is **current** behavior :

GIVEN **location** object only contains unique value that is **floatingRateIndex** :

tradeLot[0].priceQuantity[1].observable.rateOption.meta.location[0].scope,DOCUMENT
tradeLot[0].priceQuantity[1].observable.rateOption.meta.location[0].value,floatingRate
tradeLot[0].priceQuantity[1].observable.rateOption.value.floatingRateIndex.value,USD-SOFR CME Term

AND **address** object already contains unique value that is **indexTenor** :

_interestRatePayout[1].rateSpecification.floatingRate.rateOption.address.scope,DOCUMENT
interestRatePayout[1].rateSpecification.floatingRate.rateOption.address.value,floatingRate
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.period,M
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.periodMultiplier,3_

THEN the resolving mecanism will result as below : 

interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.value.floatingRateIndex.value,USD-SOFR CME Term

one can see that **indexTenor** has been simply removed/overwritten, thus it loots like having been **cancelled & replaced** by floatingRateIndex... and this is the case, indeed : whatever attribute being present in address object, the ones from location object will eventually overwrite them...

### **PROPOSAL**

change behavior so that it becomes **"smart additive"** (instead of having "cancel & replace" effect)

that means the **new resolving behavior** would meet both these **2 conditions** :

**1.** any **extra** attribute existing in meta.location object ("extra" meaning : "not already present in address objecy") would be **added** to the address object
**2.** yet any **already existing** attribute in address object would **stay** i.e. would not be overwritten by the same if existing in location object

_to recap_ : when resolving, this may result in adding new values compare to prior existing ones, but it cannot result in overwriting any existing ones in case same path value is at stake.

with same example, the new behavior would result as below :

_interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.value.floatingRateIndex.value,USD-SOFR CME Term
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.period,M
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.periodMultiplier,3_

behavior is additive : floatingRateIndex is an extra attribute in location object as compared to already existing attributes in address object so resolving logic simply add the extra one...

with another example where same attribute already exist in both location and address object, then the resolving mecanism is NOT overwriting the existing attibute value : 

GIVEN **location** object only contains unique value that is **floatingRateIndex** :

tradeLot[0].priceQuantity[1].observable.rateOption.meta.location[0].scope,DOCUMENT
tradeLot[0].priceQuantity[1].observable.rateOption.meta.location[0].value,floatingRate
tradeLot[0].priceQuantity[1].observable.rateOption.value.floatingRateIndex.value,USD-SOFR CME Term
tradeLot[0].priceQuantity[1].observable.rateOption.value.indexTenor.period,**Y**
tradeLot[0].priceQuantity[1].observable.rateOption.value.periodMultiplier,**1**

AND **address** object already contains unique value that is **indexTenor** :

_interestRatePayout[1].rateSpecification.floatingRate.rateOption.address.scope,DOCUMENT
interestRatePayout[1].rateSpecification.floatingRate.rateOption.address.value,floatingRate
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.period,M
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.periodMultiplier,3_

THEN the resolving mecanism would still result same as previous example (because indexTenor 3M already exist thus remains as it is without being overwritten by 1Y) :

_interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.value.floatingRateIndex.value,USD-SOFR CME Term
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.period,M
interestRatePayout[1].rateSpecification.floatingRate.rateOption.value.indexTenor.periodMultiplier,3_

### **RATIONALE** = save rows of code =mutualize common values 
= add extra common ones, keep specific ones

current behavior "cancel&replace" is restricting the interest of using any reference, because whenever an object that could have an address to refer to a location has at least 1 specific attribute, then no referencing can be used because it would overwrite the specific item... 

our proposal is solving this by having an approach where one can use the location attributes whenever they are shared by multiple object with the related address, while just having to specify in each any specific item if any...

further explanation with example : 

say there is "N" times the same address object with always "4" attributes in it "A, B, C and D" but in each object, only the last one has distinct value so "A", "B" and "C" attributes all have the same end path values, respectively "A,x", "By", and "C,z" whereas D has distinct value, depending each object e.g. "D,1", "D,2", etc. until "D,N" - as below :

accordingly, say we would contemplate a **location** object as below 
A,x
B,y
C,z

and these address objects :

address object 1
**D,1**

address object 2
**D,2**

[...]

address object N
**D,N**

say we would contemplate a **location** object as below 
A,x
B,y
C,z
**D,0**

with current behavior, just because D being specific in each, we cannot use our location object, des^pite the fact A, B and C are common data repeatable for each objects, because current behavior will simply overwrite/remove D1, D2, ..., D,N... ending like below :

address object 1
A,x
B,y
C,z

address object 2
A,x
B,y
C,z

[...]

address object N
A,x
B,y
C,z

so just because of 1 attribute being specific (the D) we areobliged to repeat all A, B C notwithstanding they were common - so we have bigger code i.e. more rows of codes and e cannot use location/address function :

object 1
A,x
B,y
C,z
**D,1**

object 2
A,x
B,y
C,z
**D,2**

[...]

object N
A,x
B,y
C,z
**D,N**

with our proposal ofr the new behavior, we can save code rows because location will be smartly additive as below : 

we can define a **location** object as below 
A,x
B,y
C,z

and these address objects :

address object 1
**D,1**

address object 2
**D,2**

[...]

address object N
**D,N**

and we will get final result as expected, that is resolving output beelow : 

object 1
A,x
B,y
C,z
**D,1**

object 2
A,x
B,y
C,z
**D,2**

[...]

object N
A,x
B,y
C,z
**D,N**

**Comment by jiahaodengbb** [comment]
The high level idea makes sense to me.

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
