### ISSUE TITLE
Commodity spread price type

### ISSUE THREAD

**Issue by manucarreramoreno** [finos/common-domain-model#2339]
_Background_

`priceType` is an enumerated attribute that provides an idea on how to interpret the amount that is being represented. For commodities, the fixed price of a commodity fixed-float swap is taken as an asset price. Currently, the spread is taken as an interest rate, but that is wrong as stated by a Commodity SME, since it should be also an asset price.

_Proposal_

To populate the `priceType` of a commodity spread with `ASSET_PRICE` instead of `INTEREST_RATE`.

_Pull Request_

https://github.com/finos/common-domain-model/pull/2333
https://github.com/finos/common-domain-model/pull/2353

**Comment by PayalKhanna** [comment]
Pull Request
https://github.com/finos/common-domain-model/pull/2352

**Comment by eteridvalishvili** [comment]
Hi @manucarreramoreno It seems that the pull requests linked to this issue have been resolved. Can we close this issue, or do you want to link another PR or need feedback from the maintainers? Also, please let me know if you want any labels added to this issue. I am looking forward to hearing from you. Thank you!

**Comment by manucarreramoreno** [comment]
Hi @eteridvalishvili, yes we can close the issue. As for the tags, I am not very used to them... I am not sure on what to say

**Comment by eteridvalishvili** [comment]
Hi @manucarreramoreno No worries! Thank you for confirming!
