### ISSUE TITLE
Proposed maintainer addition:  David Shone (@dshoneisda)  for ISDA

### ISSUE THREAD

**Issue by dshoneisda** [finos/common-domain-model#2345]
Per the wording in readme.md below there has been an ask for approval from current maintainers to be formally added to the list of maintainers of the CDM. Given the date for the next steering group has slipped to 12th Sept please could I ask the current maintainers to indicate their approval by comment/thumbs up reaction below please. Proposal that majority approval will then be actioned. @eacunaISDA @chrisisla @gabriel-ICMA @tomhealey-icma @iansloyan @minesh-s-patel Apologies if I missed anyone, but could not seem to add the team.

**Proposed maintainer addition:  David Shone (@dshoneisda)  for ISDA**

Note that I don't think the wording below accurately reflects the original intentions of this process and does not reflect the need to ensure continuity when personnel change at firms. I will raise a discussion to agree whether we need a wording change and what that should be.

@eteridvalishvili  FYI

"2.2.2 Appointment of CDM Steering Working Group Maintainers:

At the launch of the project, up to two initial Maintainers will be nominated by ICMA, ISDA, and ISLA (collectively, the “trade associations”).
Additional CDM Steering Group Maintainers may be proposed by Participants. Proposed maintainers will be approved via consensus of the Participants and with agreement of existing Maintainers, and should meet the following criteria:
Proven experience in data modelling and/or software development in financial markets.
In-depth understanding and proven track record of contribution to the CDM, as well as other data standards (such as ISO) and messaging protocols (such as FIX, FpML or Swift)."

**Comment by iansloyan** [comment]
agreed

**Comment by dshoneisda** [comment]
@eteridvalishvili this was approved in yesterday's CRWG, please can you add me to the maintainer team?
