### ISSUE TITLE
Proposed Maintainer addition: Adrian Dale (@ADaleISLA) for ISLA

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2347]
Following on from Issue #2345 added by @dshoneisda, I would like to ask for approval from the current maintainers to add Adrian Dale @ADaleISLA to the list of maintainers of the CDM. Adrian will represent ISLA now that David has moved to ISDA. 

Could the current maintainers (@eacunaISDA @gabriel-ICMA @tomhealey-icma @iansloyan @minesh-s-patel) indicate their approval by comment/thumbs up reaction below please. Proposal that majority approval will then be actioned.

**Comment by iansloyan** [comment]
agreed

**Comment by chrisisla** [comment]
Hi @eteridvalishvili, Adrian becoming a maintainer was agreed at the CRWG yesterday, can you add him to the Maintainers group please? Thanks!
