### ISSUE TITLE
FRAGMOS - Principal Payment Date could be "relativeTo"

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2351]
**PROPOSAL**

update the type of date used for **principalPaymentDate**, from "AdjustableDate" to "AdjustableOrRelativeDate"

this is current situation
![image](https://github.com/finos/common-domain-model/assets/92978493/0ff48a43-29df-49c9-84a8-dafedb94240c)

this is the proposal
![image](https://github.com/finos/common-domain-model/assets/92978493/df828299-5c1e-4709-8c57-705e1aa37324)

**RATIONALE**

there is no good reason why such date might not be "relativeTo" another explicit date to a type of date

as one example among potentially a lot of similar ones, say final principal payment would be defined as relative to the Termination Date, this being defined somewhere else, etc.

**Comment by harry-mcallister-bnpp** [comment]
Please evidence by reference e.g. to a confirmation which specifies the principal payment date (e.g. [Initial|interim|Final] Exchange Date) as a _relative_ date.

**Comment by JBZ-Fragmos** [comment]
Hi

I do not agree having to provide actual termsheet as if evidence is an appropriate requirement to decide if a proposal makes sense or not....

**Comment by harry-mcallister-bnpp** [comment]
There are two (almost) orthogonal; issues here: the first (my original point) is that changes to the model should be evidenced, either by business need or by reason of technical consistency. It wasn't immediately clear (at least, to me) which was the motivation in this case. 

The second issue is that CDM inherits a complex and somewhat inconsistent approach to date specification from FpML. I am  supportive of the Fragmos proposal to rationalise these legacy date structures, and agree that - in the absence of a specific business need - any change to the existing model should be made in the context of the proposed refactoring.
