### ISSUE TITLE
CDM Collateral Working Group - September 26th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2362]
# CDM Collateral Working Group Minutes
Meeting Host: Vernon Alden Smith, ISDA

## Date
September 26th, 2023 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
       - https://github.com/finos/common-domain-model/issues/2254
- [x] Meeting Presentation Material:
[ISDA Common Domain Model - Collateral WG 26th Sept 2023.pdf](https://github.com/finos/common-domain-model/files/12701965/ISDA.Common.Domain.Model.-.Collateral.WG.26th.Sept.2023.pdf)
- [x] 1. Update for CDM extension of the CSA Legacy documents in ‘ISDA Foundations’
- [x] 2. ISDA Create Synonyms updated 
- [x] 3. Addition of party to Eligible Collateral Criteria 
- [x] 4. Potential Model extensions - Eligible Collateral  
- [x] 5. FINOS open-source access to Object Builder for the CDM 
- [x] 6. The Open Source in Finance Forum (OSFF) - November 1st in New York City
           -  Collateral use case function build and demo 
- [x] 7. Barclays RepoHack 2023 : 
  https://protect-usb.mimecast.com/s/Q08eCjA9x0fzl2GQSRV9t6?domain=creativeservices.barclays/
  Register: [https://www.creativeservices.barclays/ehome/repohack2023/register/](https://protect-usb.mimecast.com/s/Ov_RCk60yrIDY7XzHQPVE1?domain=creativeservices.barclays/)
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
 [x] ACTION 1. 
As shown in agenda item No 1 – (Update for CDM extension of the CSA Legacy documents in ‘ISDA Foundations’) If members of this group are interested to join the new ISDA working group ‘ISDA CDM Legal Agreement WG’ please register via the [ISDA Committees page](https://www.isda.org/committees/), or directly contact Vernon Alden-Smith mailto:valdensmith@isda.org

 [x] ACTION 2. 
As referenced in agenda item No 3 – (Addition of party to Eligible Collateral Criteria) Some points were raised by members to ensure we consider as well as a legal agreement how a party can be connected to a trade and eligible collateral. This is more relevant to Repo and Securities financing trades and the Triparty model. If you would like to provide further information or comment, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org). 
ISDA will co-ordinate analysis and bring back to the working group some options to consider for the addition of party to Eligible Collateral Criteria, that factor in the party in the legal agreement and the trade and necessary conditions.

 [x] ACTION 3. 
As referenced in agenda item No 4 (Potential Model extensions - Eligible Collateral). For the ISO currency and country lists, members also mentioned the requirement for currency groups such as ‘European Union’ and country groups such as’G10, G20’ these can be referenced in eligible collateral lists. Also, on the same topic where the CDM model data type ‘IssuerCriteria’ has attribute ‘issuerCountryOfOrigin’, members recommended they will need to express these also as ‘Country of Incorporation’ and ‘Country of Risk’ 
ISDA will add these points as considerations as we establish how best to move forward with adding the referenced ISO lists to the CDM. Any further model additions/options on the topic will be shown to the working group for approval prior to any contributions. 

 [x] ACTION 4. 
Other items discussed in agenda item No 4 (Potential Model extensions - Eligible Collateral) as listed below: 
•	Eligibility rule related to asset price falling below a specified level in a local currency. 
•	Define variable maturity alongside set maturity profiles. 
•	Annual price- based volatility of Equity over a period (1yr) preceding a valuation date as a %. 
If these concepts are required in the CDM ‘EligibleCollateralSpecificaton’ structure, additional information will be required in the form of examples and more background information. If you would like to provide further information or comment, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790

**Comment by adamulman** [comment]
Adam Ulman - SmartStream

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu - ISDA

**Comment by benoitcuisinier** [comment]
benoit cuisinier / adenza

**Comment by vishalpnaikjpm** [comment]
Finos cdm-java jars are present on central maven repo
but its dpenedent jars are not present in central mavane repo so we are unable to procure the jars.


<dependency>
    <groupId>org.finos.cdm</groupId>
    <artifactId>cdm-java</artifactId>
    <version>5.0.0-dev.24</version>
</dependency>



But following dependencies are not on central maven repo
com.regnosys » rosetta-common | 7.6.3  |  
com.regnosys.rosetta » com.regnosys.rosetta.lib | 8.4.1 |  
com.regnosys.rosetta » com.regnosys.rosetta.blueprint.lib | 8.4.1


Becasue of that we are not able to procure the jars. Please look in to this

**Comment by VRao85** [comment]
Vinit Rao / Adenza

**Comment by fldemarche** [comment]
Florent Demarche / Murex

**Comment by mpmca** [comment]
Marion / Adenza
