### ISSUE TITLE
Document build and release process

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2363]
The CRWG requested the build and release process to be documented. Ian commented that he has been working with Regnosys on this issue.

**Comment by chrisisla** [comment]
Hi @tomhealey-icma,
A review of the release process was delegated to the TAWG a while ago (#2172), preliminary discussions and basic workflows have been mapped out and are due to be presented at the SWG on Sept 12th (#2341 agenda point 6a).
Thanks!

**Comment by lolabeis** [comment]
For reference, including the document presented at the Sep 12th SWG that describes the build and release process:
[CDM_ReleaseProcess.pdf](https://github.com/finos/common-domain-model/files/13334797/CDM_ReleaseProcess.pdf)
