### ISSUE TITLE
Changes to product qualification rules

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2365]
The existing product qualification rules only allow economicTerms as an input. EconomicTerms is insufficient to fully qualify a product. Addition types include productTaxonomy and legalAgreement. The legalAgreement currently sits in contractDetails of the trade but should be part of the product. 

This proposal will add legalAgreement to product and allow product type as an input to product qualification functions.

**Comment by harry-mcallister-bnpp** [comment]
Hi Tom, I think that the problem statement would benefit from expansion with reference to illustrative examples. 

I remain sceptical in relation to _productTaxonomy_ as an input to qualification, as taxonomy should generally be considered a _derived_ property based on economic terms + (in some cases) reference data about the underlyer. 

The case is arguable with respect to _legalAgreement_, depending on the scope of _"product"_ i.e. the level at which it is defined. Consider the case of a dual-currency option sold as a note. Is the _note_ the product; or do we consider the _option_ to be the product, and the _note_ the legal wrapper in which it is distributed (I favour the latter interpretation)?

**Comment by lolabeis** [comment]
Removing link to #2419, as this PR would not close the present issue

**Comment by tomhealey-icma** [comment]
Meeting held on asset/product change. After this is complete the product qualification rules will have to be re-written.
