### ISSUE TITLE
Adding new party role for compression

### ISSUE THREAD

**Issue by ebataller** [finos/common-domain-model#2368]
### BACKGROUND

For PTRR fields it is required to uniquely identify if a counterparty is acting as a compression service provider, so there needs to be a role associated to that party that allows us to differentiate if a compression is being provided by a third-party issuer or if it is a bilateral compression.
The existing party roles of `ClearingFirm` or `ClearingOrganization` are not sufficient to identify if the counterparty is acting as a third-party service provider or CCP for the compression event.

### PROPOSAL
To solve this, a new party role called `CompressionServiceProvider` will be added to the `PartyRoleEnum` enumeration, to uniquely identify if a counterparty is acting as a compression service provider. PR [#2369](https://github.com/finos/common-domain-model/pull/2369) solves this.

**Comment by hugohills-regnosys** [comment]
Fixed in https://github.com/finos/common-domain-model/pull/2369
