### ISSUE TITLE
Enhanced FpML to CDM mapping for events resulting in a termination

### ISSUE THREAD

**Issue by gtarres** [finos/common-domain-model#2377]
### BACKGROUND

The CDM mappings should be updated so that the event taking place is mapped under the CDM `intent` flag, in alignment with the recommendation of the CDM Architecture and Review Committee.
Additionally, mappings should be extended to support option exercises.

### PROPOSAL

The PR [#2376 ](https://github.com/finos/common-domain-model/pull/2376) extends the CDM mapping coverage to capture terminating events under the 'intent' flag and adds support to ingest FpML messages representing option exercises.

**Comment by gtarres** [comment]
Proposed labels for the issue and the corresponding PR:

Category: Modelling
Criticality: Medium/Low
Complexity: Minor Change
Target: Development

**Comment by eteridvalishvili** [comment]
Hi @gtarres It seems that the pull request linked to this issue has been resolved. Can we close this issue, or do you want to link another PR or need feedback from the maintainers? I am looking forward to hearing from you. Thank you!

**Comment by gtarres** [comment]
Hi @eteridvalishvili yes, the mappings were contributed and the issue can be considered as resolved. Thanks!

**Comment by eteridvalishvili** [comment]
Hi @gtarres Thank you for confirming!
