### ISSUE TITLE
Proposed changes to Maintainer appointment and replacement rules

### ISSUE THREAD

**Issue by dshoneisda** [finos/common-domain-model#2379]
Attached are some proposals to update governance rules following some unintended challenges in appointment of maintainers when applying the letter of what is currently written.

File attached sets out proposal I will deliver at Steering group on 12th Sept. There are additional items set out for consideration in a future meeting.

Invite comments at those sessions or below for consideration.
[CDM_Maintainership Governance Proposals.pptx](https://github.com/finos/common-domain-model/files/12547535/CDM_Maintainership.Governance.Proposals.pptx)

**Comment by dshoneisda** [comment]
updated list of considerations for comment prior to Steering in Oct
[CDM_Maintainership Governance Proposals.pptx](https://github.com/finos/common-domain-model/files/12618341/CDM_Maintainership.Governance.Proposals.pptx)

**Comment by chrisisla** [comment]
Commenting on the additional considerations on the presentation:

> Founding member provision
> - Should there be a condition that each of the founding TAs always provide at least one maintainer?

I would suggest not, especially if we set a limit on the maximum number of maintainers allowed. We also have to consider that more TAs will hopefully come onboard and this could again restrict further engagement with the community.

> Rescind maintainership of an organisation or individual by vote of other maintainers
> - Should there be a safeguarding condition to allow for this in unusual circumstances? It is suggested this would need to either be a unanimous or super majority vote of all other maintainers or a similar high bar consensus mechanism to prevent frivolous use

Agree that this should be available and should be a unanimous/super majority vote.

> Notification period
> - Should there be a notice period for change in maintainership status?

Probably not essential but would make sense. Suggestion would be that notification is made in one meeting of the SWG and then actual change would be approved in the next SWG i.e. 1 months' notice

> Regular review
> - It is recommended the Steering group periodically reviews the governance in its entirety after it has reached steady state. Would annually suffice?

Good idea, and yes annually would be good. This could probably be an action point for the first SWG of every year. Hopefully this will be a quick 2 minute read through and then move on.

> Governance changes
> - Suggest formally documenting the process by which a change to governance can be enacted along the lines of:  a) proposed change posted as an issue for discussion, b) chair of steering group asked to add to next session agenda, c) approval by simple majority

Would approval be a simple majority of whoever attends the SWG? Or majority of the maintainers?

> Voting power
> - Is the expectation that there is one vote per entity i.e. that organisations with multiple maintainers acting as OrgReps still only receive one vote

Yes that would seem logical. This would ensure that a private individual has the same voting power as an organisation.

> Ensuring correct skillset
> - There is already wording in the governance stating that maintainers must be able to evidence certain qualities, interests or history with the community. Does this need to be stronger/clearer particularly in respect to OrgReps?

No I don't think so. It makes it clear that maintainers need to have a relevant background. The reputational damage for an organisation that proposes a representative who does not have the correct experience is probably enough to prevent this from being an issue. Plus the other maintainers (by super majority) can vote to rescind maintainership for anyone if necessary

> Number of maintainers
> - Should there be a formal policy on maximum number of maintainers, either in total or per organisation

Yes, we should have a maximum number of maintainers overall (10 perhaps) and have a maximum number for any single organisation (2 is probably enough?). We should also allow the maintainers to request exceptions to this rule (should be covered by the Governance changes you mention above). FINOS and LF I'm sure will be able to provide some guidance on this.

**Comment by dshoneisda** [comment]
Thanks Chris. I am largely in alignment with you above.
On the voting question I will put to the group as is for now (which necessarily assumes all attendees get a say). I believe this is in line with general FINOS guidelines
I seem to remember initial discussions also suggested a maximum no. of maintainers, however I think we would therefore need to have formal editors. It is not clear to me who currently has such editing rights and we need to revisit the editor vs maintainer split in abilities

**Comment by eteridvalishvili** [comment]
Hi @dshoneisda I believe this issue has been resolved. I am closing for now but please reopen if necessary.
