### ISSUE TITLE
Issues with create_partyChange

### ISSUE THREAD

**Issue by ben-aubry** [finos/common-domain-model#2383]
**Background**:
As part of the project we have been implementing the clearing event processing. 
Currently, when implementing the CDM event, we have

**Comment by eteridvalishvili** [comment]
Hi @ben-aubry This issue seems to be unfinished. Can we close this issue, or do you want to link another PR or need feedback from the maintainers? Also, please let me know if you want any labels added to this issue. I am looking forward to hearing from you. Thank you!

**Comment by eteridvalishvili** [comment]
Hi @ben-aubry Closing this issue out for now. Please reopen if necessary.
