### ISSUE TITLE
Windows build failure 5.0.0-dev.27

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2387]
The latest release 5.0.0-dev.27 fails to build on windows:
 [INFO] Reactor Summary for Common Domain Model 0.0.0.master-SNAPSHOT:
"[INFO]
meta" [INFO] Common Domain Model ................................ SUCCESS [  7.089 s]
:[INFO] rosetta-source ..................................... SUCCESS [07:19 min]
 [INFO] rosetta-project .................................... FAILURE [01:55 min]
{[INFO] tests .............................................. SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] distribution ....................................... SKIPPED
[2023-09-13T15-52-22_516.dumpstream.txt](https://github.com/finos/common-domain-model/files/12601506/2023-09-13T15-52-22_516.dumpstream.txt)

[INFO] ------------------------------------------------------------------------

**Comment by minesh-s-patel** [comment]
@tomhealey-icma Can you please provide the full build log?

**Comment by tomhealey-icma** [comment]
The dump is attached.

**Comment by minesh-s-patel** [comment]
> The dump is attached.

The file attached does not seem to have much content. Can you please double check the contents?

See screenshot of the content:

![image](https://github.com/finos/common-domain-model/assets/19842097/c55aadee-d325-4047-a949-ebbe35b5cc8f)

**Comment by tomhealey-icma** [comment]
There is nothing else in the files. Here's the terminal output:
         "scheme" : "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project rosetta-project: There are test failures.
h[ERROR]
t[ERROR] Please refer to D:\IdeaProjects\finos\repo-qualification2\common-domain-model\rosetta-project\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
t[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.17\bin\java" -Xss16m -Xmx1G -jar C:\Users\theal\AppData\Local\Temp\surefire10481994834523908827\surefirebooter13222810640867822339.jar C:\Users\theal\AppData\Local\Temp\surefire10481994834523908827 2023-09-14T10-29-15_938-jvmRun1 surefire1813515682941213849tmp surefire_111142909942987591323tmp"
p[ERROR] Process Exit Code: 0
:[ERROR] Crashed tests:
/[ERROR] com.regnosys.granite.projector.fpml_5_10.Fpml510ProjectionMapperTest
/[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.17\bin\java" -Xss16m -Xmx1G -jar C:\Users\theal\AppData\Local\Temp\surefire10481994834523908827\surefirebooter13222810640867822339.jar C:\Users\theal\AppData\Local\Temp\surefire10481994834523908827 2023-09-14T10-29-15_938-jvmRun1 surefire1813515682941213849tmp surefire_111142909942987591323tmp"
w[ERROR] Process Exit Code: 0
w[ERROR] Crashed tests:
w[ERROR] com.regnosys.granite.projector.fpml_5_10.Fpml510ProjectionMapperTest
.[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
l[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
c[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
h[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
cl[ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
e[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
a[ERROR]        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
r[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
n[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
e[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
t[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
.c[ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
o[ERROR]        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
m[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
/[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
c[ERROR]        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
l[ERROR]        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
e[ERROR]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
a[ERROR]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
r[ERROR]        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
l[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
i[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
n[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
k[ERROR] -> [Help 1]
/[ERROR]
co[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
di[ERROR] Re-run Maven using the -X switch to enable full debug logging.
n[ERROR]
g[ERROR] For more information about the errors and possible solutions, please read the following articles:
-[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
sc[ERROR]
h[ERROR] After correcting the problems, you can resume the build with the command
em[ERROR]   mvn <args> -rf :rosetta-project
e/party-id"
          },
          "value" : "CS2SCM"
        },
        "meta" : {
          "globalKey" : "76fe4afb"
        }
      }, {
        "identifier" : {
          "meta" : {
            "scheme" : "http://www.fpml.org/coding-scheme/external/iso17442"
          },
          "value" : "NOT FOUND"
        },
        "identifierType" : "LEI",
        "meta" : {
          "globalKey" : "d5cc39a5"
        }
      } ]
    }, {
      "meta" : {
        "externalKey" : "party2",
        "globalKey" : "33d8d89"
      },
      "partyId" : [ {
        "i

**Comment by tomhealey-icma** [comment]
I added window-latest to the github workflows. https://github.com/finos/common-domain-model/pull/2391. The latest release should be rebuilt.
