### ISSUE TITLE
Github workflow for Windows build is triggered twice

### ISSUE THREAD

**Issue by SimonCockx** [finos/common-domain-model#2399]
The [Github workflow for a Windows build of the CDM](https://github.com/finos/common-domain-model/blob/master/.github/workflows/windows-build.yml) is triggered twice. E.g., see https://github.com/finos/common-domain-model/pull/2398.

![image](https://github.com/finos/common-domain-model/assets/47859223/d2bc2150-ea00-48b8-a54b-933d196d1f75)

This is because the build is both triggered by the [`push`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push) trigger and the [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) (of type `open`/`synchronize`) trigger:
```
on: [workflow_dispatch, push, pull_request]
```

To eliminate the cost of running these builds multiple times, I propose to change the trigger config to the following:
```
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize]
```
This should correctly trigger the build whenever the head commit of the pull request changes, i.e.,
- when the pull request is opened
- when a new commit is pushed
- when a pull request from a forked repository is raised or the fork is pushed to.

See documentation on the `synchronize` action type here: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request

I suspect the same problem is present for the other two workflows we have (CVE scanning and license scanning).

**Comment by maoo** [comment]
Hi @SimonCockx ! Hi think there is space for improvement, but given that there is no cost associated to action runs, it's low priority.
