### ISSUE TITLE
Support for Commodity Delivery (II)

### ISSUE THREAD

**Issue by JanBaserba** [finos/common-domain-model#2412]
EMIR Refit requires the reporting of delivery information for European electricity and gas commodity products, both physical and financial, in the form of the following fields:

- 2.122. Delivery interval start time
- 2.123. Delivery interval end time
- 2.124. Delivery start date 
- 2.125. Delivery end date
- 2.127. Days of the week
- 2.128. Delivery capacity
- 2.129. Quantity unit
- 2.130. Price/time interval quantity
- 2.131. Currency of the price/time interval quantity

This information is currently not supported in CDM.

**Comment by rvincentISDA** [comment]
The scope of this issue has now been addressed. Accordingly it can be closed
