### ISSUE TITLE
CDM Steering Working Group - October 10, 2023 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2414]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
October 10, 2023  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x]  1.	Convene & Roll Call reminder- @eteridvalishvili 
- [x]  2.	Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  3.	Review  Actions from Sept 12th (1min)- DShone
a.	https://github.com/finos/common-domain-model/issues/2341
- [x] 4. Governance & Operating Topics 
  - [ ] a. Point of order: participants.md- DShone
  - [ ] b. Governance proposals- discussion of feedback on [governance homework questions](https://github.com/finos/common-domain-model/issues/2379)- DShone (15 min)
  - [ ] c. Final proposals based on feedback on [Operating Model](https://github.com/finos/common-domain-model/discussions/2423) and [PR Service Expectations](https://github.com/finos/common-domain-model/issues/2133)- DShone & THealey (15 min)
- [x] 5. Release Schedule
  - [ ] a. Release process- discussion of feedback on [homework questions](https://github.com/finos/common-domain-model/pull/2056)- DShone & CRayner (15 min)
  - [ ] b. Change Control Guidelines- BLynn (15 min)
- [x] 6. Topics from WGs
  - [ ] a. Update- Serialisation- DSchwartz (5min)
  - [ ] b. Update- Ref Data Code List Management- BLynn (5 min)
- [x] 7. AOB

Material attached:

[CDM_Steering_Group231010.pdf](https://github.com/finos/common-domain-model/files/12844590/CDM_Steering_Group231010.pdf)

## Minutes

- Point of order- all those interested in voting as part of the community need to submit a PR to add their names to participants.md
- Agreed as proposed in powerpoint: Founding member provision, Rescind membership, Notification Period, Regular Review, Correct skillset
- Voting power- 1 org/ind vote for maintainers was proposed and passed- in line with existing FINOS governance
- Further discussion required: Number of Maintainers/limits- this needs explanation of editor model and proposal of 10 is breached already as 13 exist today. Carried to next steering group
- Request from group to publish chairs/key contacts of each group
- Acknowledged there would be times that some items would not fit into an existing DWG- these should be raised at the CRWG through exception/escalation. If a new WG is warranted this needs to be proposed to steering WG as per existing governance.
- Noted that DWG sign off is not mandatory but will speed up review and approval of PRs
- Some discussion about existing ToRs of groups and whereabouts as not available easily

## Action Items

- [ ] DShone to collate and arrange for group chairs/key contacts along with group list to be published in github and microsite
- [ ] @eteridvalishvili  to collate existing ToRs for DWGs, publish to microsite, and highlight missing items to steering group
- [ ] @dshoneisda  to check wording around raising of new DWGs to steering group and embellish wording if ambiguous
- [ ] CRayner to create templates for Issues and PRs and run through this and relevant groups
- [ ] All community members inc. maintainers- add names to participants.md
- [ ] @eteridvalishvili - to arrange to explain maintainer vs editor model to community at next steering group
- [ ] @dshoneisda  to carry maintainer limit issue on agenda
- [ ] @dshoneisda  to arrange for passed proposals to have wording updates in readme and on microsite
- [x] @eteridvalishvili and @dshoneisda  to arrange slot for interim steering group to continue conversations and topics not covered w/c 23/10-CLOSED- No acceptance of only suitable slot- next steering group Tues 7th Nov to be used instead
- [ ] @dshoneisda  to confirm capacity of all existing maintainers and arrange for publication on readme/microsite

### Zoom info
Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09

Meeting ID: 937 5620 5037
Passcode: 911071
Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by dschwartznyc** [comment]
Serialization update

[FINOS - CDM SWG Update 20231010.pdf](https://github.com/finos/common-domain-model/files/12847537/FINOS.-.CDM.SWG.Update.20231010.pdf)

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by dschwartznyc** [comment]
dan schwartz / FT Advisory

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by ADaleISLA** [comment]
Adrian Dale / ISLA
