### ISSUE TITLE
CDM Structured Products WG - October 10th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2415]
# CDM Structured Products Working Group Minutes
Meeting Host: Jean-Baptiste Ziadé, Fragmos Chain 

## Date
October 10th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- Ben Wood, JP Morgan
- Jiahao Deng
- Moger, Nicholas, JP Morgan
- Naik, Vishal
- Reza Gorjestani
- Thomas Chin
- Ruddy Vincent, ISDA, [rvincentISDA](https://github.com/rvincentISDA)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
  - [x] https://github.com/finos/common-domain-model/issues/2359
- [x] ObservableBasis 
- [x] Progress updates from our [last call ]((https://github.com/finos/common-domain-model/issues/2359))about “core team / volunteers to perform deep assessment of the model
  - [ ] RBC – feedbacks / questions to share with the group, about :
       - [ ] Feedback from “Gap Analysis”
       - [ ] Deep assessment of Fragmos-Chain Work Space
 - [x] Fragmos-Chain – come back on foundational design principles
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09

Meeting ID: 921 3608 7343
Passcode: 861434
Find your local number: https://zoom.us/u/ad5NMLeH9R

**Comment by JBZ-Fragmos** [comment]
jbz - FragmosChain

**Comment by suyashyc** [comment]
Suyash Chaudhary / RBC

**Comment by xlu208** [comment]
Xiaotian Lu / Bloomberg
