### ISSUE TITLE
CDM Technology Architecture Review WG - October 12th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2416]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
October 12th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2360
- [x] Review progress of topics raised in last meeting
- [x] Discussion Topics
  - [x] Serialisation Update
    - [x] #2180 
  - [x] CDM Reference Data Lists Update
    - [x] #2269
    - [x] [CDM Reference Data Status for TAWG Oct 12 2023.pptx](https://github.com/finos/common-domain-model/files/12882488/CDM.Reference.Data.Status.for.TAWG.Oct.12.2023.pptx)
  - [x] Release Process Update
    - [x] #2056 
    - [x] #2363 
  - [x] Versioning Questions
    - [x] #2305 
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] Election of new chair -  https://github.com/finos/common-domain-model/issues/2450

## Discussion points
*DSL changes*
- Release note for DSL changes need more clarity/description
- DSL would also benefit from roadmap - TAWG to review this possibly?
- Could we perhaps have an interim demo of the changes, not wait a month?

*Serialisation*
- Will the chosen format have an impact on naming perhaps? packaging? version?
- Can we present the recommendation to the TAWG first, prior to presentation to the SWG?
- We can use CDM lists to push out invite, TAs to socialise to their own members

*Reference Data list*
- agreed we need to bundle files, could be a jar, could be some other format
- files/lists probably in JSON to be consistent with serialisation (assuming chosen serialisation format is JSON)

*Release Process*
- Proposal for moving to CDM maintainer control underway
- @chrisisla working on it, will discuss with @tomhealey-icma and show the proposal once ready

## Action Items
- [x] Add DSL roadmap discussion to the next TAWG Agenda - @chrisisla 
- [x] Ask REGnosys if we can organise a demo of the recent DSL changes before the next TAWG - @chrisisla
- [ ] Open question on Serialisation format affecting model type naming/packaging/version - @dschwartznyc to add to discussions
- [ ] Arrange initial presentation of Serialisation recommendation to the TAWG - @chrisisla and @dschwartznyc to co-ordinate
- [ ] Complete proposal for Release Process - @chrisisla to complete and discuss with @tomhealey-icma 
- [x] Versioning discussion to be moved to next TAWG Agenda - @chrisisla 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory

**Comment by ahutusoru123** [comment]
Adrian Hutusoru / Fragmos Chain

**Comment by rvincentISDA** [comment]
Ruddy Vincent / ISDA

**Comment by tzurcher** [comment]
Timothée Zürcher / Pictet

**Comment by fgignoux** [comment]
Frederic Gignoux / SG

**Comment by macprog-guy** [comment]
Eric at Pictet

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by jgavronsky** [comment]
Jane / FINOS
