### ISSUE TITLE
CDM Collateral Working Group - November 15th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2418]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

November 15th, 2023 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
   - [x] https://github.com/finos/common-domain-model/issues/2362
- [ ] CDM Collateral WG 15th Nov - Meeting Material 
[ISDA Common Domain Model - Collateral WG 15th Nov 2023.pdf](https://github.com/finos/common-domain-model/files/13336194/ISDA.Common.Domain.Model.-.Collateral.WG.15th.Nov.2023.pdf)
- [ ] Agenda 1 - ICMA - Buy-Sell/Back Agreements Collateral Provisions
- [ ] Agenda 2 - ISLA - Master Agreement Update 
- [ ] Agenda 3 - Addition of party to Eligible Collateral Criteria 
- [ ] Agenda 4 - Addition of ISO Country codes to the CDM for Eligible Collateral and connection to ISO Currency codes
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
Action 1  - As shown in agenda item No 1 – Presented by ICMA - Buy-Sell/Back Agreements Collateral Provisions. ICMA will create a PR related to the addition of data type ‘CollateralIncomeProvisions’ to the model as shown at the meeting, this can then be visible for others to comment and approve prior to contribution to the CDM  

Agenda 2 - With referenced to agenda item No 2 – ISLA Master Agreement Update. If you would like further information or comment, please mailto:Chris.Rayner@islaemea.org

Action 3 - The model extensions related to agenda items 3 & 4 listed below have been contributed to the CDM and everyone will have fill visibility. We encourage members of the working group  
•	Agenda item No 3 (Addition of party to Eligible Collateral criteria)
•	Agenda item No 4 (Addition of ISO Country codes to the CDM for Eligible Collateral and connection to ISO Currency codes)
If you would like to provide further comment, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by valdensmith** [comment]
Vernon Alden-Smith ISDA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by mpmca** [comment]
Marion / Adenza

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for Regnosys

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by Alexis25091972** [comment]
Alexis Lucas / BNY Mellon International Collateral Management

**Comment by ryanasalt** [comment]
Ryan Saltamacchio / Truist, Capital Markets Operations

**Comment by eteridvalishvili** [comment]
Hi @valdensmith, Closing this issue. Please reopen if necessary.
