### ISSUE TITLE
Recruitment of CDM Working Group and Project Leads

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2450]
This issue captures the names and firms of people who would like to become a Common Domain Model maintainer by joining the leadership for the following working group.

`Technology Architecture Working Group`

Please add your `Name`, `Firm`, `Position`, and the `Reason why you'd make a great CDM working group maintainer` to the comments below ... 👇🏻 

The deadline for nominations is `Wednesday 8th November 2023`.

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader / Managing Partner

I have been involved in CDM since its beginnings. TradeHeader is an active participant of the CDM development. I am also the current chair of the FpML Architecture Working Group. I can provide input from lessons learned over the years developing FpML.

**Comment by eteridvalishvili** [comment]
Hi @chrisisla, Closing this issue. Please feel free to reopen if necessary.
