### ISSUE TITLE
CDM Version

### ISSUE THREAD

**Issue by jonnance** [finos/common-domain-model#2468]
Is there a way to tell which version of the CDM is being used? For example, if I'm looking at a serialized JSON of a CDM TradeState, can I tell which version was used to create that TradeState? Based on that version, I'd want to pull down the right JAR to deserialize it back into Java

**Comment by dshoneisda** [comment]
@dschwartznyc @chrisisla @brianlynn2  this is currently being discussed in the sub-group looking at serialisation right? Something that can be summarised for @jonnance ?

**Comment by brianlynn2** [comment]
Yes, the proposed enhancements to the serialized content would include the CDM version and the specific object that was saved, both of which are missing from the current serialization format.

**Comment by jonnance** [comment]
That's great - do you have a link to this proposal that I could review?

**Comment by dschwartznyc** [comment]
@jonnance you can see much of the discussion in the issue Brian cites above.  the last two meetings were unfortunately canceled due to #OSFF prep and aftermath.  We are nearing the recommendation for the first phase and will likely review it in next week's meeting.  If you'd like to join the discussion please provide an email address and I'll add you to the invite.

**Comment by jonnance** [comment]
@dschwartznyc is this the Technology Architecture Working Group on Thursday? If so, I believe I already have the invite

**Comment by dschwartznyc** [comment]
@jonnance there's a separate serialization task force meeting that will follow the TAWG.  we operate under it with a specific focus on serialization.

From: Jon Nance ***@***.***>
Date: Friday, November 3, 2023 at 12:07 PM
To: finos/common-domain-model ***@***.***>
Cc: dschwartznyc ***@***.***>, Mention ***@***.***>
Subject: Re: [finos/common-domain-model] CDM Version (Issue #2468)

@dschwartznyc<https://github.com/dschwartznyc> is this the Technology Architecture Working Group on Thursday? If so, I believe I already have the invite

**Comment by lolabeis** [comment]
Closing as dealt with under #2180
