### ISSUE TITLE
Adding support for Exchange Traded Positions to CDM Core

### ISSUE THREAD

**Issue by rogerguitart** [finos/common-domain-model#2471]
## Context

Over the last two months, we have been actively engaged in a collaborative effort to model **Exchange Traded Positions** within the framework of the CDM. This initiative has been a collective endeavour, drawing upon the expertise of SMEs. The primary objective has been to establish an MVP representation of Exchange Traded Positions that aligns with the broader CDM and serves for the reporting use case of EMIR Refit and other regulations requiring ETD Reporting.. We have now reached a working model that has gathered consensus among member firms, which entails the creation of a root type `CounterpartyPositionState`, and a new type `CounterpartyPositionBusinessEvent` within the already existing `WorkflowStep` to document the state transition of a position in CDM.

### Overview

The proposal consists of:

- A `CounterpartyPositionState` root type that documents the state transition of a position during its lifecycle. This root type contains:
    - A `counterpartyPosition` field with the necessary details to document the information in a position
    - A `state` field to show the state of the position (closed, cancelled, etc), 
    - An `observationHistory` field with the history of events that impact the position (e.g. corporate action), and 
    - A `valuationHistory` field with the history of valuations and characteristics for that position (closing price, the type of valuation, etc)

<img width="716" alt="pos_image1" src="https://github.com/finos/common-domain-model/assets/141412602/500011f9-8767-4999-aaf3-d3120e940b12">

### CounterpartyPosition Field

Having seen the CounterpartyPositionState root type, the `counterpartyPosition` field inside it is now discussed. This type is characterized by:
- A list of parties and their roles (`party` and `partyRole`), 
- The timestamp for when a position was first opened (`openDateTime`), 
- The `positionBase` with the core constituents that help buid the position (this leverage the already existing `TradableProduct` type), 
- The lineage to the trades that make that position (`tradeReference`),
- The unique identifier of the position in the form of a *Position UTI* (`positionIdentifier`), and
- Information on the collateralization (`collateral`), the execution (`executionDetails`) and contract details (`contractDetails`) regrouped under a new `contractBase` type

<img width="712" alt="pos_image2" src="https://github.com/finos/common-domain-model/assets/141412602/54668186-3e8c-4bf7-a98a-b9c9b1e6b227">

The `contractBase` that is extending the `counterpartyPosition` is intended to hold data attributes common to trades and positions. It consists of contractDetails such as the governing law or master agreements, executionDetails like the execution venue or the type of execution, and collateralization details. It is important to remark that these three fields were already present in the model, and the only update has been to group them under this "contractBase" type:

<img width="600" alt="pos_image2" src="https://github.com/finos/common-domain-model/assets/141412602/1cffbfe3-f25b-437d-ac25-5c2e287970fb">

### ValuationHistory Field

The `valuationHistory` field located inside `CounterpartyPositionState` has multiple cardinality (0..*) and collects the various valuations associated to one counterpartyPositionState. With the use of the mandatory `timestamp` field, one can find out and report when each valuation was made.

<img width="700" alt="pos_image3" src="https://github.com/finos/common-domain-model/assets/141412602/a8835160-782e-4947-a570-eecb3cd5bd94">

### CounterpartyPositionBusinessEvent Type

A workflowStep will feature a `CounterpartyPositionBusinessEvent` field which documents the sate transition of a position. For now, the Minimum Viable Product (MVP) introduces a similar structure as that of `businessEvent`, but only the **after state of type CounterpartyPositionState** is proposed.​ Additionally, there is a new reduced business `intent` with a more limited enumeration deemed applicable to positions. As is shown in the following image, there are now **seven** allowable values for intent. Their business descriptions can be seen in the textual definition below as well:

<img width="720" alt="pos_image4" src="https://github.com/finos/common-domain-model/assets/141412602/7c60c615-3bae-44af-a165-f927ce8810ae">

<img width="716" alt="pos_image5" src="https://github.com/finos/common-domain-model/assets/141412602/aa554532-43df-4e52-99e6-1c3f77f1a1b3">

In order to report positions in the broader scheme of DRR, we have proposed to introduce a `ReportablePosition` field of type `CounterpartyPositionState`, which will be contained inside `ReportableEvent`. Additionally, the `originatingWorkflowStep` will be the one just described above. For clarity, the graphical view of this `ReportablePosition` field would look as follows:
​
<img width="750" alt="pos_image6" src="https://github.com/finos/common-domain-model/assets/141412602/bae66a73-7367-4e05-a2fc-d6567e3e73d0">

**Comment by lolabeis** [comment]
Closed by #2513
