### ISSUE TITLE
CDM Technology Architecture Review WG - November 9th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2484]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
November 9th, 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2416
- [x] Initiative Updates
   - [x] Serialisation update – Dan 
   - [x] Reference data lists update – Brian
- [x] Initiative Prioritisation
   - [x] Release Process
   - [x] Versioning (i.e. naming and aligning artefacts to a version, versioned testing)
   - [x] Interoperability (between versions including transformation between versions)
   - [x] Change Control
   - [x] Testing
   - [x] Standard Error Handling
   - [x] Any more for any more?
- [x] Change Control (if time)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points

_Discussion_
- Serialisation
  - Dan is going to present recommendation at the next SWG (Tuesday 14th November)
  - Might require a major version to be cut to cater for it
  - This is due to changes to generators and validation routines
- Reference Data Lists
  - Brian is going to present update at the next SWG too
  - Wants to define an initial scope and a future scope
  - Ideally wants to phase the development too

_Prioritisation_
- Question: Do the group feel multiple initiatives running at the same time was beneficial?
  - Minesh
    - 2 large initiatives in parallel required too much effort
    - Could be because both initiatives were manned by essentially the same people
    - Suggested going forward we need to make scope of initiatives smaller
    - Optimal would be 4 to 6 weeks of weekly meetings
  - Brian
    - Valuable having multiple in parallel due to crossover of scopes
    - Need to improve scheduling though
    - Less frequent but longer calls better than frequent smaller ones
  - Dan
    - Urgency would dictate whether multiple initiatives need to be run in parallel
    - More engagement and participants in the groups would assist ability to run in parallel
    - Main challenge from current initiatives was defining problem statement and scope
  - Leo also asked how many people were involved in the groups?
    - Serialisation started with about 5 and had 12 on the last meeting
    - Reference Data Lists has been consistent around 4 or 5
    - Suggestion is that we need more people from firms who are actively working with the CDM

- Question: Are there any additional topics that should be added for consideration as new TAWG initiatives?
  - Dan
    - Versioning
    - In relation to aligning artefacts to specific versions
    - In relation to interoperability between versions
  - Testing
    - Version specific testing too
    - Standard Error Handling/Messages
  - Brian
    - Concurred with Dan on the need for better/standard error messaging
  - Minesh
    - Need a technical roadmap so people know what is coming up
    - If there is no roadmap then people will develop solutions themselves

- Question: What would be your top priority?
  - Brian
    - Release process to focus on versioning
    - Believes the release process and versioning topics have a lot of overlap and may need to be done in parallel
  - Tom
    - Release process in relation to how it should be defined and scheduled
    - Chris: Release Schedule and Governance are owned by the SWG, not the TAWG, we can work on the execution
    - Minesh: Current release execution is in Codefresh and can be converted to github actions now
  - Conclusion
    - Release Process execution will be next initiative
    - Scheduling and Governance will be passed to SWG as Agenda items
 
## Action Items
_Action Points_
- [ ] Add DSL change demo to the next Agenda - @eteridvalishvili and @chrisisla 
- [x] Call to arms for Release Process execution initiative to be sent to cdm lists - @chrisisla 
- [x] Serialisation recommendation, Reference Data Lists update and Release Process governance/scheduling to be added to next SWG Agenda - @chrisisla 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISLA

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FT Advisory

**Comment by minesh-s-patel** [comment]
@minesh-s-patel / REGnosys

**Comment by macprog-guy** [comment]
Eric at Pictet

**Comment by fgignoux** [comment]
Frederic GIgnoux / SG

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by phoulgerycka** [comment]
Diana Fulger / no affiliation

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by ahutusoru123** [comment]
Adrian Hutusoru / Fragmos Chain

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by eteridvalishvili** [comment]
Hi @chrisisla, Closing this issue. Please feel free to reopen if I am mistaken.
