### ISSUE TITLE
CDM Steering Working Group - November 14th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2485]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
October 10, 2023  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [ ]  Approve past meeting minutes
  - [ ] https://github.com/finos/common-domain-model/issues/2414 and https://github.com/finos/common-domain-model/issues/2341 This Steering Group carries over topics not completed at last instance (10th October), but will begin with brief updates from ongoing tech initiatives:
1. Topics from WGs
  - [x] a. Update- Serialisation- DSchwartz (5min)
  - [x] b. Update- Ref Data Code List Management- BLynn (5 min)
2. Release Schedule
  - [x] a. Release process- discussion of feedback on [homework questions](https://github.com/finos/common-domain-model/pull/2056)- CRayner (15 min)
  - [x] b. Change Control Guidelines- BLynn (5 min)
3. Governance proposals- Maintainer Limit Discussion
  - [ ] a. @eteridvalishvili  - FINOS to explain maintainer vs editor model (action from last SWG) (5 min)
  - [ ] b. Complete decision on whether to add a maintainer limit- led by DShone (5 min)
4.  Operating Model
 - [ ] a. Complete conversation from last SWG on operating model for PR closure (10 min)
- [ ] 5. AOB

Material from last SWG re-attached:

- [CDM_Steering_Group231010.pdf](https://github.com/finos/common-domain-model/files/12844590/CDM_Steering_Group231010.pdf)
- Materials in support of 1.a Serialization Update / Proposal [FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114.pdf](https://github.com/finos/common-domain-model/files/13339928/FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114.pdf)
- Materials in support of 1b - Reference Data Update / Direction [CDM Reference Data Status for SWG 2023-11-14 v4.pptx](https://github.com/finos/common-domain-model/files/13343365/CDM.Reference.Data.Status.for.SWG.2023-11-14.v4.pptx)

## Minutes
**Admin**

- Previous minutes agreed
- Outstanding Actions carried over:
- @dshoneisda  to confirm capacity of all existing maintainers and arrange for publication on readme/microsite- this has been documented, needs to be published to microsite
- All community members inc. maintainers- add names to participants.md
- @eteridvalishvili /Jane- to arrange to explain maintainer vs editor model to community at next steering group
- @dshoneisda  to carry maintainer limit issue on agenda
- @dshoneisda  to arrange for passed proposals to have wording updates in readme and on microsite
- @dshoneisda  to collate and arrange for group chairs/key contacts along with group list to be published in github and microsite
- @eteridvalishvili to collate existing ToRs for DWGs, publish to microsite, and highlight missing items to steering group
- @dshoneisda  to check wording around raising of new DWGs to steering group and embellish wording if ambiguous
- @chrisisla  to create templates for Issues and PRs and run through this and relevant groups

**Serialisation**

- @dschwartznyc gave an update to the SWG with recommendation on course of action and the need to resource- see material attached in comments
- Estimate of resource need is 4 person months of resource in 2 months of elapsed time

**Ref Data**

- BLynn gave an update on reference data task force
- Phased work likely, with some synergies with work to be carried out for serialisation
- Key benefit: cheaper for users to implement and maintain
- Heads up that resourcing will be required
- Assumption that there will be translations in place for published data into JSON format since CDM can not be expected to ingest every single format of every ref data source
- Further update will be given at next SWG

**Release Process**

- @chrisisla  introduced discussion on release process based on github responses
- A call to arms has gone out already to work through moving build process from CodeFresh to GitHub Actions
- Bigger item is scheduling and timing- multiple options discussed, but no concrete proposal was made as conflicting views, primarily on timing of minor releases with some feeling that necessity should drive minor releases rather than timing
- In order to properly make a proposal various questions on versioning and backward compatibility should be answered first
-  Operating Model & PR Process

There was not time to cover, but no further feedback had come forth
@dshoneisda  proposed that if no further feedback by 24th November, the proposed flow would be published to the microsite as is
 
## Action Items

- [ ] @finos/cdm-maintainers  to publish recommendation in Issue and ask for community volunteers
- [ ] Trade associations to discuss sharing of resourcing/funding for this support feature in absence of volunteers
- [ ] @tomhealey-icma  to fashion a proposal with maintainers and key community members and present for acceptance/vote at next steering group
- [ ] @dshoneisda to publish to microsite the governance and proposed PR flows

### Zoom info
Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09

Meeting ID: 937 5620 5037
Passcode: 911071
Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by dschwartznyc** [comment]
Materials in support of 1.a Serialization Update / Proposal
[FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114.pdf](https://github.com/finos/common-domain-model/files/13339928/FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114.pdf)

**Comment by brianlynn2** [comment]
Materials in support of 1b - Reference Data Update / Direction
[CDM Reference Data Status for SWG 2023-11-14 v4.pptx](https://github.com/finos/common-domain-model/files/13343365/CDM.Reference.Data.Status.for.SWG.2023-11-14.v4.pptx)

**Comment by dschwartznyc** [comment]
Daniel Schwartz/FT Advisory

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by jgavronsky** [comment]
Jane / FINOS
