### ISSUE TITLE
CDM Structured Products WG - November 28th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2486]
# CDM Structured Products Working Group Minutes
Meeting Host: Jean-Baptiste Ziadé, Fragmos Chain 

## Date
November 28th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
  - [ ] https://github.com/finos/common-domain-model/issues/2359
- [ ] Feedbacks, questions, etc; from Contributors who would have gone through the first GitHub Issues above mentioned
- [ ] Core Contributors such as Bloomberg and RBC will be kindly asked if they would like to share with the groups any feedbacks from Deep Dive Work Cessions that took place with FragmosChain, or internal “homeworks” with regards to either of the topics below :
   - [ ] The completion of the Gap Analysis
   - [ ] The assessment of the capacity of the model to represent all the Termsheets appropriately
   - [ ] The review of Distribution of Trade Files using the structured model, drafted by FragmosChain
- [ ] Update about available tools ; notably
  - [ ] already available : view access to the Structured Product workspace of Fragmos-Chain
  - [ ] to come : “Trade Builder” (by FragmosChain of Regnosys representant if present)
- [ ] Next Steps in terms of GitHub Issues drafting, validation by the Structured Group, and Roadmap to submit related PR to FINOS review committee
   - [ ] remind / ensure we agree on the “global strategy” of having 2 shapes of PRs : the ones impacting the whole model, then the ones specific to structuredPayout branch
   - [ ] as part of first shape, list the GitHub Stories and share status (what is drafted, what is validated or not, etc.)
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

- Feedbacks from core participants – namely RBC and BBG – currently reviewing the model is positive for now, as a result of :
   - gap analysis of current CDM in regards of 7 tersmsheets provided by RBC,
   - how such products are effectively modelled if using structuredPayout new objects, based on actual Trade Distribution produced by Fragmos-Chain for all the termsheets
   - bespoke work cessions : BBG/Fragmos, RBD/Fragmos
- BBG has indicated that separate cessions would also take place with RBC to review how Structured Products are represented currently in BBG-DLIB, which may lead to future gap analysis if need be, about CDM capacity to model the whole “workflow” required by Structured Notes e.g. issuance, grey market phase, quotes, placements, etc – for clarity, this would be distinct and complementary exercise, in regards of the termsheet modelling that Structured Group is addressing
- Fragmos-Chain has started documenting the project and related core objects in GitHub, as preliminary work for preparing the future release related “PRs”. The project documentation is broken down into one “Parent Story” that provide an overview then multiple “Child Stories” which focus each on particular new objects required by the “structuredPayout” branch. Headers of Issues all contains “Structured Products” key words one may enter in GitHub for filtering as need be. For instance : [FRAGMOS - Structured Products - Parent Story](https://github.com/finos/common-domain-model/issues/2483)

## Action Items

- Participants are kindly asked to review project documentation that Fragmos-Chain has prepared in GitHub – starting with the following GitHub Issues :
   - [FRAGMOS - Structured Products - Child Story 1.0. - ObservationBasis 0 : Overview](https://github.com/finos/common-domain-model/issues/2494)
   - [FRAGMOS - Structured Products - Child Story 1.1. - ObservationBasis 1 : ObservableValue](https://github.com/finos/common-domain-model/issues/2499)
   - [FRAGMOS - Structured Products - Child Story 1.2. - ObservationBasis 2 : ObservationConditions](https://github.com/finos/common-domain-model/issues/2500)
- Fragmos-Chain to continue drafting/completing the documentation. For clarity : key Issues related to the project are all tagged “Structured Product” in header. All these issues be considered ready for being reviewed by Participants, unless otherwise specified with the word “DRAFT” in header
- Participants are kindly asked to check in internal databases if they could provide other termsheets
   - for instance exotic vol/var payout, possibly involved in exotic dispersion strategies,
   - or with contingent basket “rainbow” features e.g. the “ nth “ best/worst performance
   - or any other products they would like to assess with the new model

### Zoom info
Join Zoom Meeting
https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09

Meeting ID: 921 3608 7343
Passcode: 861434
Find your local number: https://zoom.us/u/ad5NMLeH9R

**Comment by JBZ-Fragmos** [comment]
JB ZIADE  ==  FRAGMOS CHAIN

**Comment by xlu208** [comment]
Xiaotian Lu == Bloomberg LP

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by rvincentISDA** [comment]
Ruddy Vincent / ISDA

**Comment by jiahaodengbb** [comment]
Jiahao Deng == Bloomberg LP
Harry Lipman == Bloomberg LP

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
