### ISSUE TITLE
FRAGMOS - Structured Products - Child Story 1.0. - ObservationBasis 0 : Overview

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2494]
**BACKGROUND - CONCEPTUAL BASIS**

Original need was to define a **generic type of end-value** to be used in **_Product Model_** and consistently re-used in **_Event Model_** which functional meaning shall be to represent **any input, say "X"** also any **output "Y"** for **any payout function, say "F(X)=Y"** 

(where function terms _"F(...)" per se_ e.g. operators, parenthesis rules, inputs composition, etc. are in turn represented by _other new objects_ included in the structuredPayout branch e.g. corePayout breakdown, AggregationFeatures, StructuredFeatures, Branching Logic, etc. as described in _other "Child Stories"_ linked to the Structured Product "Parent Story")

An example of usage as "end-value" of some payout paths, thus in **Product Model**, hereunder in structuredPayout branch :

view with "name"
![image](https://github.com/finos/common-domain-model/assets/92978493/d92af4a8-b541-4949-a733-b51f51d5cb30)

same view with "type"
![image](https://github.com/finos/common-domain-model/assets/92978493/0a7dc845-b089-4fcd-960e-faeed2e6af26)

That being said, the ObservationBasis type is designed to be **consistent per se**, meaning it might exist as stand-alone type, and its generic properties make it ready for being used for multiple representation purposes, _**beyond**_ structuredProduct i.e. **could benefit to the whole model**, notably the **Event Model**. 

For instance :
- could be used to record an generic **"Observation"** of any type, that with no upfront consideration of business usage, whether included or not in payout calculation or to be used for other purposes e.g. sharing valuation data as part of a pricing consensus process, recording barriers being touched, possibly upfront to actual reset that would impact the payout, etc.
- It could also be used to record an Observation that will update the time consumption in the related payout terms, which in our opinion is generic definition of a **"Reset"**

About such re-use of ObservationBasis beyond structuredProduct as new primitive Instruction types, cf. all details in https://github.com/finos/common-domain-model/issues/2504
 
**CDM TYPE DESCRIPTION - OVERVIEW**

The ObservationBasis is made of two core attributes :
- **ObservableValue** - that is to represent "**WHAT**" is observed ; this is close to existing PriceQuantity, but is more generic, cf. all details in https://github.com/finos/common-domain-model/issues/2499
- **ObservationConditions** - that is to represent "**HOW**" it is observed in all meaning of the word "how" e.g. in terms of aggregation method if multiple values, data source, observation time, determination method, etc ; cf. all details in https://github.com/finos/common-domain-model/issues/2500

Importantly, ObservableValue has an **unbounded** cardinality **(0..*)**, whereas ObservationConditions is **unique** **(0..1)**, and **both** have **optional** existence, which is very key for further usage in the model.

Quick overview :
![image](https://github.com/finos/common-domain-model/assets/92978493/91247d13-1203-46c4-9428-574a613c869d)

Detailed view (same as above with unfolded nodes) :
![image](https://github.com/finos/common-domain-model/assets/92978493/7ae60f6a-17a1-45c3-83c6-e3116f173cdb)

Besides, the ObservationBasis concept in the structuredProduct branch actually exists in **two complementary types**
- one is type **"CoreObservationBasis"** and is a **unique** attribute attached to the upfront corePayout root, with _metadata **location**_
- whereas other one is type **"ObservationBasis"** exists in **multiple places** accross the corePayout nodes as an end-leaves, with _metadata **references**_ that correspond to the referenced object located in CoreObservationBasis

Compare both structures : 
![image](https://github.com/finos/common-domain-model/assets/92978493/50868da9-c981-45c0-b553-eccf26c30e60)

**Business usage** : reason for having these two complementary types with references between them :
- is to permit any **_common observation features_** that could be shared by default by most terms of the trade, to be defined in **CoreObervationBasis**
- then **each particular ObservationBasis** may _either_ reference it when values by default shall apply, _else_ specify values when there is a need to **otherwise specify specific values locally** in a particular ObservatioBasis

Example : 
- say the same PriceTypeEnum is used every where as "Closing" by default in CoreObservationBasis thus, thus applying as such in most ObservationBasis occurrences
- except for some particular ObservationBasis, for which he value shall to be "Opening"

**From coding stand-point**, the benefit of CoreObservationBasis is also **to save rows of code** e.g. on some complex product requiring lot of information to be re-used in multiple legs when being modeled

Exemple : Fragmos-Chain could experience a reduction of a trade file initially 2000 rows when using the structured modelling without CoreObservationBasis (for clarity, this one was complex trade per se, also including lot of data anyway e.g. including multi-baskets, etc.), to be reduced down to 750 rows when properly using such referencing.

However, such way to "_reference_ common values by default, _else_ to specify other ones locally", without the common ones to overwrite the local ones as a result of resolving builder - that requires refactoring about current behavior of resolving functions in that matter, as explained in https://github.com/finos/common-domain-model/issues/2338

**Comment by jiahaodengbb** [comment]
@JBZ-Fragmos, I got two questions:

 1. Regarding
     >Importantly, ObservableValue has an unbounded cardinality (0..*), whereas ObservationConditions is unique (0..1), and both have optional existence, which is very key for further usage in the model.  

     In what case could `ObservationConditions` have 0 occurrence? If there is only one  `ObservableValue` then I assume that we can skip `ObservationConditions`. If there are multiple `ObservableValue`s, can we still skip `ObservationConditions`? Is there any default condition?
 
2. For `CoreObservationBasis`, I see that we also allow 0 occurrence for `observableValue`. I understand that for `ObservationBasis`, we may skip `observableValue` if we rely on the metadata to refer to the `CoreObservationBasis`. Could you help me understand in what situation we can skip `observableValue` in `CoreObservationBasis`?

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
