### ISSUE TITLE
FRAGMOS - Structured Products - Child Story 1.1. - ObservationBasis 1 : ObservableValue

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2499]
**OVERVIEW**

ObservableValue is designed to represent "**WHAT**" is observed in very generic manner, as "any type of value with an impact on settlement obligations described in Trade contractual terms, notably when considered as an input for Payout calculations".
Accordingly, an ObservableValue could be :
- market data used in the model as related to some payout terms e.g. price or quantity, either already fixed, or not, thus to be observed in the future when relevant e.g. per observation dates else in regards of payout triggers, or market event, etc.
- also stand-alone market data, associated to an observable (refactored in accordance with https://github.com/finos/common-domain-model/issues/2106)
- and vice-versa i.e. could be either a stand-alone observable thus without price or quantity yet defined, or with such attributes given at inception, or having been observed later during related Trade lifecycle, etc.
- eventually, could also be market event e.g. corporate action, credit default, extraordinary event, etc.

As an information, this type is quite close to existing **PriceQuantity**, though key distinct features shall be considered :
- ObservableValue contains **"structuredFeatures"** attribute described in Child Stories 
     - https://github.com/finos/common-domain-model/issues/2495, 
     - https://github.com/finos/common-domain-model/issues/2496, 
     - https://github.com/finos/common-domain-model/issues/2497
- it also contains **"composite"** as an optional choice to straight "observable" - as info, this component is key for the purpose of re-using the ObservableValue type as par of the Event Model notably for recording the observation of calculations
- ObservableValue has **metadata address** ; whereas the same types e.g. Price or Quantity are metadata location (saying "same type" here to keep it short, yet quantity in ObservableValue is of type "QuantitySchedule" vs. being of type "NonNegativeQuantity" in PriceQuantity that is more restrictive in terms of representation scope)
- ObservableValue exists inside **multiple places** in payout paths nodes i.e. inside "corePayout" components ; whereas PriceQuantity is used outside Payout terms as an attribute of TradeLot
- no settlementTerms neither effectiveDate exists in ObservableValue because such kind of features belongs to ObservationConditions as part of the generic model design consisting in relying on ObservationBasis made of multiple ObservableValue[*] and ObservationConditions

- last not least : "observable" in ObservableValue is of new type, as refactored in https://github.com/finos/common-domain-model/issues/2106 - that being said, this difference with PriceQuantity about "observable" type is temporary i.e. shall not remain a distinct feature, since we assume that PriceQuantity shall update its current "observable" with the refactored type.

As an information, this is PriceQuantity (you can compare with ObservableValue in next section) :
![image](https://github.com/finos/common-domain-model/assets/92978493/a6cb3cb4-1a6d-48c3-9b16-f26c759abbbe)

**CDM TYPE DESCRIPTION**

![image](https://github.com/finos/common-domain-model/assets/92978493/294dc927-70c7-434f-909a-7b3d7e31da83)

**Comment by jiahaodengbb** [comment]
Could you elaborate the difference between `NonNegativeQuantitySchedule` and `QuantitySchedule`? Why do we remove the "NonNegative" part?

**Comment by jiahaodengbb** [comment]
>it also contains "returnRatio" as an optional choice to straight "observable"
Do you mean "priceReturn"? I didn't see returnRatio in the NewObservableValue screenshot.

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziade / FRAGMOS CHAIN

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
