### ISSUE TITLE
FRAGMOS - Structured Products - Child Story 1.2. - ObservationBasis 2 : ObservationConditions

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2500]
**OVERVIEW**

ObservationConditions is designed to represent "HOW" an item represented in CDM is observed in all meaning of the word "how" e.g. in terms of aggregation if multiple values, in terms of data source, time of observation, determination method, etc.

Thehere are _two kinds_ of model components to which ObservationConditions may relate to :

- either an **ObservableValue** (as described in ), thus **as part of an ObservationBasis**, as below

![image](https://github.com/finos/common-domain-model/assets/92978493/1bd55e87-2668-457f-972a-f8f4940253da)

- else, **any other object to which ObservationConditions may be attached to**, mainly when multiple instances exist so the aggregation method shall be specified and it is an  attribute of ObservationConditions, so this type would be re-used in such place, though with another label name, say "**multiple[XXX]AggregationFeatures**" where "[XXX]" referes to the name of the main multiple item at stake - see an example below in a node where multiple instance of "[return]" may exist : 

![image](https://github.com/finos/common-domain-model/assets/92978493/c090c05d-3177-4cf5-a0de-33579899fd56)

**CDM TYPE DESCRIPTION**

![image](https://github.com/finos/common-domain-model/assets/92978493/a4700a03-9a99-4107-8d5b-6d12f3c61a98)

- **observation dates** are described with two types of dates : (**a**) obervationPeriods or (**b**) observationDates ; else both types may be used together as described below (**c**) :
    (**a**) **observationPeriods** permits to define the parameters for building a schedule of periods i.e. segments in series, each made of a pair : period start observation date ; period end observation date
    (**b**) **observationDates** permits _either_ to define observation dates in alternate way i.e. as a list of individual dates (instead of periods) explicit lists of dates as dates in series, that being alternate way to define observation, 
    (**c**) else, given observationPeriods, then the particular observationDates component relativeDates->**dateIsRaltiveToEnum** (further described in https://github.com/finos/common-domain-model/issues/2523#:~:text=FRAGMOS%20%2D%20Enum%20type%20refactoring%202%20%2D%20NewDateRelativeToEnum%20%232523) can be used to specify which date to refer to for anchoring e.g. each Observation Date, etc. 

- **aggregatedFeatures** are described in https://github.com/finos/common-domain-model/issues/2498#:~:text=FRAGMOS%20%2D%20Structured%20Products%20%2D%20Child%20Story%203%20%2D%20AggregationFeatures%20%232498

- **cumulativeObservationConditions** are of same type being nested as an attribute, that is for the purpose of representing successive sets of observations _also_ with ensuring _priority order_ for resolving purposes is properly described i.e. which is actually represented by considering the nesting series of cumulativeObservationConditions as playing same role that parenthesis are playing in standard algebra e.g. say ObsB is nested in ObsA i.e. ObsB is the "cumulative" attribute of ObsA, then this is equivalent to " ObsA**(**ObsB**)** " (As an information, there is a detailed example of business case using "cumulative" attribute, inside previous item Child Story above mentioned for aggregatedFeatures)

- remaining set of attributes is straightforward e.g. determinationMethod, source, etc.

**Comment by jiahaodengbb** [comment]
For the `observationDates`, just want to confirm the behavior of case **(c)** when both **observationPeriods** and **observationDates** are used. Is it right that the **observationPeriods** will be treated as anchor and the **dateIsRelativeTo** will be applied against every date in the **observationPeriods**?

**Comment by jiahaodengbb** [comment]
Could you clarify a little more about the **cumulativeObservationConditions**? I didn't understand " ObsA**(ObsB)** " 
>say ObsB is nested in ObsA i.e. ObsB is the "cumulative" attribute of ObsA, then this is equivalent to " ObsA**(ObsB)** "

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
