### ISSUE TITLE
Missing Floating Rate Index Enums and use of 'OTHER'

### ISSUE THREAD

**Issue by nicholas-moger** [finos/common-domain-model#2508]
Hi we are noticing some missing enums in the floatingRateIndex creation such as USD-Federal-Funds-Target (USD federal funds is there, but this is the target not the actual).

Also in UPI we are able to select 'OTHER' as the Rate Index (which this falls into)

I see there is a separate 'IndexReferenceInformatio' name/value pair - is this the correct place to populate the value if we don't have a valid enum?

This issue will arise in two areas:
1 - Where there is a genuine benchmark which is missing (i.e. USD-Federal-Funds-Target)
2 - Where there is a basis swap with one benchmark being a custom curve such as a CSA curve

In both of these cases the UPI would take OTHER, we would prefer not to have to use OTHER in CDM though.

**Comment by eteridvalishvili** [comment]
Hi @nicholas-moger I hope this message finds you well. I'm following up on your question and wanted to check if it's okay to close now and if you've received your answer. If you haven’t and if you'd like to keep it open please let me know. 

If you're interested in joining the Contribution Review Working Group (CRWG) meetings, we have sessions scheduled for tomorrow, February 6th at 10 am EST/3 pm GMT, and another on February 20th at the same time so you can discuss your questions directly with the maintainers. Please let me know your preferences or if you have any further questions or concerns. Looking forward to hearing from you!
