### ISSUE TITLE
FRAGMOS  * whole Model benefit + required for Struct * - Enum type refactoring 2 - DateIsRelativeToEnum

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2523]
- We want to add this **new Enum type**
- and it will be a **new attribute** in existing type **RelativeDate**

![image](https://github.com/finos/common-domain-model/assets/92978493/21ac9e5b-05a2-42d4-8594-9d62c590257f)

**Rationale** :

this date is **exactly same concept** as the **existing PayRelativeToEnum** that currently points to **CalculationPeriodDates**, which purpose is to designate the type of dates the Payment Dates shall refer to among CalculationPeriodDates, for the purpose of anchoring, possibly calculate offset, etc. 

we want to leverage this logic by making it **more generic**, 
which means
- to **extend the list of Enum values** as compared for instance to current list we have in PayRelativeToEnum
- to consider that **being relativeToEnum shall _not_ be restricted to _Payment Dates only_** i.e. any date being a RelativeDate (whether for valuation, payment, observation, etc;) shall have such Enum attribute with an extensive list so that it may refer to most usual types industry is actually using when booking trades and producing related termsheets e.g. Valuation Date, Termination Date, Observation Date, etc.

_note _ : as regards the Payment Date where current PayRelativeToEnum exists, we could remove it / replace it by the one we propose, that is generic so encompasses the particular business case of Payment Dates among other ones....

**BACKGROUND**
this is required for modelling Structured Product https://github.com/finos/common-domain-model/issues/2483
yet business usage of this component is not restricted to Structured Products, so shall benefit to the whole model

**Comment by jiahaodengbb** [comment]
LGTM

**Comment by JBZ-Fragmos** [comment]
@jiahaodengbb 
thanks for your positive feedback (I assume "LGTM" means "Looks good to me")
FYI, i've just specified/distinguished between more types of termination dates ; for clarity i've juts added these ones compare to initial version you have hecked 
![image](https://github.com/finos/common-domain-model/assets/92978493/f3114af5-e660-431c-9354-65e10f97d8be)

business need / background :
**new** termsheet recently received (cannot disclose here, it is Client TS, will depend if agrees to join next Structured Meeting &/or share Termsheets) :
- rate payoff in where number of days to count for calculating a multiplier value is duration between initial date and early observation event date that is to say a Term period i.e. end date cannot be fixed in advance, hence being relativeToEnum,EARLY_TERMINATION_OBSERVATION_DATE
- and payment is 5 days after, so needed to define such offset as relativeToEnum,EARLY_TERMINATION_SETTLEMENT_DATE

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
