### ISSUE TITLE
FRAGMOS  * whole Model benefit + required for Struct * - Enum type refactoring 4 - DeterminationMethodEnum

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2525]
we want this extended version to replace existing one, also the one proposed below will ensure more consistency with TimeTypeEnum by considering the fact some of relayed Enum values may be the same in the two list, that with no overlap i.e. makes sense as is.

**BACKGROUND**
this is required for modelling Structured Product https://github.com/finos/common-domain-model/issues/2483
yet business usage of this component is not restricted to Structured Products, so shall benefit to the whole model

**PROPOSAL**
![image](https://github.com/finos/common-domain-model/assets/92978493/159db056-2100-48f8-82e2-959778d2faca)

**CURRENT TYPE TO BE REPLACED**
![image](https://github.com/finos/common-domain-model/assets/92978493/27071509-a01b-4231-a11e-5bcf0a9c5f40)

**Comment by jiahaodengbb** [comment]
I see that `AgreedInitialPrice` was removed. Is there no use case for that?

**Comment by jiahaodengbb** [comment]
Also could we provide more business justification for the added enums?

**Comment by jiahaodengbb** [comment]
Small one: 
 
 "... some of relayed Enum values may **he** the same in the two list ..." might be "... some of relayed Enum values may **be** the same in the two list ..."?

**Comment by JBZ-Fragmos** [comment]
thanks, yes, i've corrected typo

**Comment by JBZ-Fragmos** [comment]
i've not removed "AgreedInitialPrice" actually i'm just proposing to change its name i.e. to replace it with "SeparatlyAgreedSpecificPrice" - because i beleive this is not necessarily related to "Inititial" (mostly, yes, but always, not sure... moreover this item would be typically used in context so you have the info in context e.g. if used as part of path "initiaValuationPrice->determinationMethod" then obviously that is for ""initiaValuationPrice"  ... if used elswhere would be for the related object, etc.

**Comment by JBZ-Fragmos** [comment]
regarding "business justification" what i can say is that i've just extended the existing Enum list to other "usual" business cases, for instance specific case of Milano exchange, etc. else have proposed refactoring of existing names e.g. OSP to become eplicit "OfficialSettlementPrice", etc.

**Comment by JBZ-Fragmos** [comment]
any item related to this Issue is either closed or re-open under this one :
https://github.com/finos/common-domain-model/issues/2941
