### ISSUE TITLE
[FIXED] CDM does not support PTRR - Portfolio Rebalancing events

### ISSUE THREAD

**Issue by ebataller** [finos/common-domain-model#2532]
In the technical specification for the EMIR jurisdiction, there are some reportable fields regarding PTRR (Post-Trade Risk Reduction) events. The support in CDM is limited to Compression events, and to allow the complete reporting these PTRR events, it is necessary to include the Portfolio Rebalancing event, by adding its corresponding value to the `EventIntentEnum` and a specific qualification function for this event.

The contribution to solve this issue is in PR [#2531](https://github.com/finos/common-domain-model/pull/2531)

**Comment by eteridvalishvili** [comment]
Hi @ebataller Since the PR connected to this issue has been resolved I have gone ahead and closed this issue, please feel free to reopen the issue if necessary. Thank you!
