### ISSUE TITLE
Cardinality change for after state within CounterpartyPositionBusinessEvent

### ISSUE THREAD

**Issue by rogerguitart** [finos/common-domain-model#2536]
Following the release of counterparty positions in the CDM model, a small modelling update is required regarding the cardinality of the `after` field contained within `counterpartyPositionBusinessEvent`. It was initially contributed as single cardinality `(0..1)`, and we raise the point that it should be modified to multiple cardinality `(0..*)`, as is shown in the image below. This is done to support the case when multiple `after` position states are generated as a result of a _partial option exercise_ event being applied to the position. Additionally, it mirrors the way the `after` trade states within `businessEvent` currently operate for trades.

![image](https://github.com/finos/common-domain-model/assets/141412602/f96aaeea-0f21-47d5-b9ea-159903c75d5e)

**Comment by eteridvalishvili** [comment]
Hi @rogerguitart It seems that the pull request linked to this issue has been resolved. Can we close this issue, or do you want to link another PR or need feedback from the maintainers? Also, please let me know if you want any labels added to this issue. I am looking forward to hearing from you. Thank you!

**Comment by rogerguitart** [comment]
Hi @eteridvalishvili , Yes this issue can be closed now. Regarding the labels, the following could be added:
Category: modelling
Complexity: small bug/Mapping
Criticality: Medium/Low
Target: Production

Thank you very much!
