### ISSUE TITLE
!!Call for volunteers: Serialisation Standardisation- First Phase

### ISSUE THREAD

**Issue by dshoneisda** [finos/common-domain-model#2548]
At the Steering WG on 14th November, @dschwartznyc presented the recommendation from the task force assigned by the TAWG to look at standardising serialisation of CDM.
This recommendation is attached below.

The SWG is calling for any volunteers to look at progressing this work to come forward to the maintainers or comment on this issue.

Offers to complete this work on a funded basis are also welcome. Quotes can be sent to the maintainers for consideration.
Please send through by 8th December

[FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114 (1).pdf](https://github.com/finos/common-domain-model/files/13476192/FINOS.-.CDM.SWG.-.Serialization.Proposal.-.20231114.1.pdf)

**Comment by eteridvalishvili** [comment]
Hi @dshoneisda I am closing this issue as it has passed the deadline.
