### ISSUE TITLE
CDM Collateral Working Group - December 13th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2568]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

December 13th, 2023 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
   - [x] https://github.com/finos/common-domain-model/issues/2418
 - [x] **13th December Meeting Material:**
[ISDA Common Domain Model - Collateral WG 13th Dec 2023.pdf](https://github.com/finos/common-domain-model/files/13600919/ISDA.Common.Domain.Model.-.Collateral.WG.13th.Dec.2023.pdf) 
- [x] **AGENDA 1** - Eligible Collateral CDM extensions 
           •	Addition of Party Role, to identify the role of parties. 
           •	Extend origins of assets and issuers beyond ISO Country codes 
- [x] **AGENDA 2** - Check Eligible Collateral function build, contribution and demo
- [x] **AGENDA 3** - FINOS open-source access to CDM object builder update 
- [x] **AGENDA 4** - CDM Excel download of model
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items

- [x] ACTION 1 - As shown in agenda item No 1 - Addition of Party Role, to identify the role of parties (slides 3-7 of meeting material). Members of the working group are in favour of this model change. ISDA will process with the contribution to the CDM 
- [x] ACTION 2 - As shown in agenda item No 1 - Extend origins of assets and issuers beyond ISO Country codes (slides 8-9 of meeting material). We thank members for their feedback, there is support to add the concept of ‘country of risk’ and another addition ‘country of domicile ‘alongside country of origin/incorporation.   
For groups of countries, members of the working group were in favour of adding, although lists of country groups would require maintenance and changes could cause issues. 
ISDA will prepare a draft contribution related to both the above points to share with members for review at the next working group meeting before proceeding with and CDM model changes. 
- [x] ACTION 3 - As shown in agenda item No 2,3 & 4 (slides 10- 3 of meeting material)
•	Check Eligible Collateral function build, contribution and demo
•	FINOS open-source access to CDM object builder update 
•	CDM Excel download of model
If you have any further questions, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by valdensmith** [comment]
Vernon Alden-Smith ISDA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by fldemarche** [comment]
Florent Demarche - MUREX

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by ryanasalt** [comment]
Ryan Saltamacchio - Truist, Capital Markets Operations

**Comment by criss11fr** [comment]
Cris Searle / Clearstream

**Comment by minesh-s-patel** [comment]
@minesh-s-patel / REGnosys

**Comment by AmyCaruso** [comment]
Amy Caruso, ISDA

**Comment by eacunaISDA** [comment]
@eacunaISDA  / ISDA

**Comment by Oblongs** [comment]
@Oblongs Lionel Smith-Gordon / REGnosys

**Comment by Elena242** [comment]
Elena Parigi Adragna/Symphony
