### ISSUE TITLE
CDM Technology Architecture Review WG - December 14th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2569]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
December 14th, 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2484
- [x] Status of group chair
- [x] Initiative Updates
   - [x] Serialisation update – Chris
   - [x] Reference data lists update – Chris
- [x] Release Process
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points
_Release Process_
- Minesh
  - Community is asking for more transparency on the build process
  - REGnosys happy to support this initiative
  - Rosetta DSL releases recently migrated to github actions so they have some knowledge to share
  - Need to also provide ability for participants to request a release to be built
  - Happy to lead this as an initiative
- Brian
  - Need to consider ability to build from branches i.e. prod, dev, other
  - Would also be nice if Rosetta (or other tools) could create a branch for example
- Dan
  - Permission to push the button should be for CDM Maintainers only
  - Documentation and troubleshooting guide/FAQ should be key deliverables

## Action Items
- [x] Send an email to cdm.lists requesting people to get involved in the initiative - @chrisisla 
- [x] (tentative) Try to come up with a recommendation for the next SWG in January - @minesh-s-patel 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by AdrianJenksD2LT** [comment]
Adrian Jenks / D2LT

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by minesh-s-patel** [comment]
@minesh-s-patel / REGnosys

**Comment by fgignoux** [comment]
Frédéric Gignoux / SG

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by KsarCapital** [comment]
Said Rossi / Ksar Capital
