### ISSUE TITLE
Urgent: CDM Build Failure

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#2573]
CDM builds are failing with the error:
Downloading from regnosys-artifactory-releases: https://regnosys.jfrog.io/regnosys/libs-release/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.xtext:org.eclipse.xtext.xbase.lib/maven-metadata.xml from/to regnosys-artifactory-snapshots (https://regnosys.jfrog.io/regnosys/libs-snapshot): authentication failed for https://regnosys.jfrog.io/regnosys/libs-snapshot/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml, status: 401 Unauthorized
...

**Comment by hugohills-regnosys** [comment]
Also note that any eclipse dependencies such as `org.eclipse.xtext:org.eclipse.xtext.xbase.lib` are downloaded from Maven Central rather than REGnosys artifactory.  See the build logs below from a successful build where it is downloaded from central:

```
Downloading from regnosys-artifactory-releases: https://regnosys.jfrog.io/regnosys/libs-release/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml
Downloading from regnosys-artifactory-snapshots: https://regnosys.jfrog.io/regnosys/libs-snapshot/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml
Downloading from ossrh: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml
Progress (1): 4.1/4.5 kB
Progress (1): 4.5 kB    
Progress (2): 4.5 kB | 776 B
                            
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/maven-metadata.xml (4.5 kB at 450 kB/s)
```

Only REGnosys libraries are stored in the REGnosys artifactory, requests for other libraries will fail.

**Comment by tomhealey-icma** [comment]
No, the settings.xml from github looks like this:
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <servers>
        <server>
            <id>ossrh-distro</id>
            <username>${env.CI_DEPLOY_USERNAME}</username>
            <password>${env.CI_DEPLOY_PASSWORD}</password>
        </server>
        <server>
            <id>ossrh</id>
            <username>${env.CI_DEPLOY_USERNAME}</username>
            <password>${env.CI_DEPLOY_PASSWORD}</password>
        </server>
        <server>
            <id>${env.GPG_KEYNAME}</id>
            <passphrase>${env.GPG_PASSPHRASE}</passphrase>
        </server>
    </servers>
    <profiles>
        <profile>
            <id>gpg</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <gpg.keyname>${env.GPG_KEYNAME}</gpg.keyname>
            </properties>
        </profile>
    </profiles>
</settings>

**Comment by tomhealey-icma** [comment]
I see, but who should address the gpg issue, FINOS? Should we really have two different settings.xml?

**Comment by hugohills-regnosys** [comment]
Actually, for builds, no settings.xml is required at all, it all works with the default maven settings.xml which is used if none is specified.  The build settings.xml I posted in a comment above also works, but is not necessary - I will edit the comment above to avoid confusion.

For the GPG settings.xml file, is there an issue?  The processes that used that settings.xml are working successfully.

**Comment by tomhealey-icma** [comment]
Didn't make any changes but it's working now. It may be related to access to maven central. It would be good to know the root cause.
