### ISSUE TITLE
Price Mappings for knownAmountSchedule not up to date

### ISSUE THREAD

**Issue by gopazoTH** [finos/common-domain-model#2608]
The PriceQuantity>priceSchedule is not represented in the InterestRatePayout when we have a sample with knownAmountSchedule.

**Comment by gopazoTH** [comment]
See AT issue (it also affects CDM): https://airtable.com/appIpXvRzbxjCHyWl/tblcWkWBczriIL1ch/viwSfNnf3ZJ0R7F2w/receQIGUeqCTd2GnK?blocks=hide

**Comment by lolabeis** [comment]
@gopazoTH  No link to Airtable here please, this is not a publicly accessible tool. I have removed. ^^
