### ISSUE TITLE
CDM Technology Architecture WG - January 11th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2612]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
January 11th, 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2569
- [x] Release Process
  - [x] Who would like to participate
  - [x] Scope of the initiative
  - [x] Schedule
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points

_Release Process_
- Great response from people about participating
- Defined initial scope to be put into an Issue for transparency
- Confirmed governance and release schedule out of scope
- Agreed:
  - Dan would organise the sessions, first one being a 2 hour kick off
  - Minesh would be main SME
  - Ongoing initiative schedule to be defined in first meeting
  - Publicise this initiative through FINOS comms
- See also the Action Points

_Native functions_
- Dan raised question of how we should handle native functions in the model
- Consensus was that we needed guidelines on how to manage this
- Ability for users to override CDM with their own libraries also suggested
- Agreed to include in agenda for next meeting

## Action Items

- [x] Liaise with FINOS to get FINOS labs environment setup - @chrisisla 
- [x] Email everyone who offered to participate - @chrisisla 
- [x] Create Issue defining what is in and what is out of scope - @chrisisla 
  - [x] #2623 
- [x] Publicise this initiative using FINOS channels - @eteridvalishvili 
- [x] Update next TAWG agenda to: - @chrisisla 
   - [x] Include revisit of TAWG initiatives in the pipeline
   - [x] Include discussion point on usage of native functions

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by osttra-j-joyce** [comment]
James Joyce / OSTTRA

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by fgignoux** [comment]
Frederic Gignoux / SG

**Comment by d-sen-gupta** [comment]
Dhruva/JPMC

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader (only for the first 30 mins)

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by Perelmuter** [comment]
Rimma Perelmuter/FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
