### ISSUE TITLE
CDM Collateral Working Group - January 30th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2614]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

January 30th, 2023 - 10 am EST / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
   - [x] https://github.com/finos/common-domain-model/issues/2568
- [x] **January 30th Meeting Material** 
[ISDA Common Domain Model - Collateral WG 30th Jan 2024.pdf](https://github.com/finos/common-domain-model/files/14083847/ISDA.Common.Domain.Model.-.Collateral.WG.30th.Jan.2024.pdf)

- [x] Agenda 1.	CDM Eligible Collateral use case adoption update – FIA Tech 
- [x] Agenda 2.	CDM Collateral - Get started guide
- [x] Agenda 3.	Update for CDM extension of the CSA Legacy structure in ‘ISDA Foundations’
- [x] Agenda 4.	Eligible Collateral CDM extensions added to documentation
     - [x]  Eligible Collateral Validation Function 
     - [x] Additions to existing user documentation for recent extensions in the CDM
	Party, applies To and Party Role
- [x] Agenda 5.	CDM Showcase Event– 28th February 2024 
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Action 1 - As shown in agenda item No 2 – CDM Collateral – Get started guide, if members of this group have further ideas or suggestions please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [ ] Action 2  - As shown in agenda item No 3 - Update for CDM extension of the CSA Legacy structure in ‘ISDA Foundations’.
If you are interested in the CDM CSA Legal Agreement development, please join the ISDA CDM Legal Agreement WG. Contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [ ] Action 3 - As shown in agenda item No 5 
If you would like to join the waiting list for the CDM Showcase event 28th February 2024, please register [here](https://www.islaemea.org/isla-events/cdm-showcase/agenda/?utm_campaign=CDM%20Showcase&utm_medium=email&_hsmi=288870523&_hsenc=p2ANqtz-9G4bzDjFS0tPNfZ67pEVD-q5QDRBcuqUTX3WsL-bgbiA_zahKgLgh8YLhQ76gl-FVbVG78CvuP91SbeMXRony6PkUb--YT4TtPD3XZ925dnK4XZbo&utm_content=288870523&utm_source=hs_email)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by valdensmith** [comment]
Vernon A-S ISDA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by dschwartznyc** [comment]
Daniel Schwartz / FT Advisory

**Comment by dharmkap** [comment]
Dharm Kapadia / EquiLend

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi, CloudMargin

**Comment by Elaijja** [comment]
Eleonora Salzmann / PwC GmbH

**Comment by adamulman** [comment]
Adam Ulman / SmartStream

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by rsiddharthan** [comment]
Siddharthan / Barclays

**Comment by OusidaR** [comment]
Ousida Rengenchetty /Vermeg

**Comment by AmyCaruso** [comment]
Amy Caruso, ISDA

**Comment by sashworthTKN** [comment]
Stephen Ashworth /Tokenovate

**Comment by hasnatjx** [comment]
Justin Hasnat / FIA Tech

**Comment by VRao85** [comment]
Vinit Rao/Nasdaq (Adenza)
Rakesh Shetty/Nasdaq (Adenza)
