### ISSUE TITLE
OptionPayout Refactoring - CDM Core Major Release

### ISSUE THREAD

**Issue by rogerguitart** [finos/common-domain-model#2624]
## Context

The current structure of option payout in CDM contains an `exerciseTerms` field, which is responsible for describing the terms for exercising the option. Within `exerciseTerms`, we find the `optionStyle` and `strike` fields. The former contains the three styles an option can have (`americanExercise`, `europeanExercise`, or `bermudaExercise`). These three styles, in turn, have their own fields that might be needed to accurately represent the style of the option at hand. The issue here is that several of these fields repeat across the three option styles, thus making the model redundant and overly complex. This could be greatly simplified by combining all the _distinct_ fields contained currently inside the different option styles and placing them directly inside the `exerciseTerms` container, therefore eliminating the `optionStyle` field. To distinguish whether the option is american, european, or bermuda, a new `style` enumeration could then be added to the model, with the values "american", "european", and "bermuda". Additionally, the strike field should be moved outside exerciseTerms and be located directly under optionPayout, given that it does not convey any information about the exercise terms of an option. 

Altogether, this proposal would bring about _backward incompatible_ changes to the CDM Core model, and therefore would require a _**major CDM release**_.

## Proposal

The proposal consists of:

- Grouping the fields inside `americanExercise`, `europeanExercise`, and `bermudaExercise`, and place them inside the `exerciseTerms`, which is of type `Exercise`.
- Removing the `optionStyle` field within `exerciseTerms`.
- Moving the `strike` field out of the exerciseTerms and inside the `optionPayout`.
- Creating an enumerated list `style` inside the `exerciseTerms` that distinguishes the style of an option ("American", "European", "Bermuda").

![image](https://github.com/finos/common-domain-model/assets/141412602/292e5833-ec71-4ba6-8cc9-251b456f0817)

In addition to these model changes, some conditions to control the style of the option should be included in the `Exercise` type. These conditions ensure that certain fields are present (or absent) depending on the style of the option:

![image](https://github.com/finos/common-domain-model/assets/141412602/23c240b5-f3a3-4934-9cb1-b2b79e1ff3b2)

**Comment by JBZ-Fragmos** [comment]
hi, 
all the proposals look good to me @rogerguitart @mgratacos

**Comment by chrisisla** [comment]
Hi @rogerguitart 

Apologies for not getting back to you sooner on this. When we were looking at `ExtendibleProvision` there was some discussion about this and I am in favour of removing the specific types for each exercise type and replacing them with a single generic type i.e. replace the types `AmericanExercise`, `EuropeanExercise` and `BermudaExercise`. 

The existing `ExerciseTerms` looks to be a good place to put the attributes from within those types and then use conditions to control them. On this final point, are you looking to make all the attributes optional? 

I think this proposal looks good though :+1:

Thanks!

**Comment by rogerguitart** [comment]
Hi @chrisisla ,

Thank you for the feedback. Just as a clarification, I have removed the `AmericanExercise`, `EuropeanExercise`, and `BermudaExercise` fields from the `ExerciseTerms`, but their types are still present in the model, given that they are being used in `ExtendibleProvision` and `CancelableProvision`, as you mention.

Regarding the cardinality, they are all optional with the exception of `expirationTime`, given that this field was present and mandatory in all three exercises. Would this work for you?

Thank you!

**Comment by chrisisla** [comment]
Thanks for clarifying @rogerguitart. 

If you are just putting the attributes from under the 3 exercise types into `ExerciseTerms` then you're introducing duplication in the model, as the terms will be both in `ExerciseTerms` and `AmericanExercise`, `EuropeanExercise` and `BermudaExercise`. It would seem to me that if you want to use `ExerciseTerms` (which is really `OptionExercise`) then you should deprecate the use of the other 3 types at the same time to prevent confusion.

**Comment by rogerguitart** [comment]
@chrisisla Yes you are right - is it okay to add the `[deprecated]` annotation under the 3 exercises for now?

**Comment by lolabeis** [comment]
It's a good proposal @rogerguitart.

> My suggestion would be that everywhere that these 3 exercise types are used should be updated to now use `OptionExercise` instead.
I concur with @chrisisla here. At the time when `ExtendibleProvision` and `CancelableProvision` were introduced (in 2023), the inefficiency of having 3 distinct types of `OptionExercise` was raised. The decision was not to refactor it at the time and re-use "as-is", but that it should come in due course when `OptionExercise` itself gets refactored.

One other point from those discussions was regarding the `OptionStyle` enum values, which should be made more market convention-agnostic. "European", "American" etc. are derivatives-tinted terms which could be replaced by more logical and neutral terms, TBD: e.g. "Continuous" instead of "American".

**Comment by rogerguitart** [comment]
Hi @lolabeis , @chrisisla ,
Thank you for your comments, I also agree with both of you. However, instead of using the `OptionExercise`, could we instead directly use the new `Exercise` inside `CancelableProvision` and `ExtendibleProvision` that is being proposed, which already contains the necessary fields? This way, we could move away from the old `OptionExercise` field (maybe deprecate it) and implement `Exercise` everywhere. For the CancelableProvision it would look something along the lines of the attached image:

![image](https://github.com/finos/common-domain-model/assets/141412602/1b4cd7cf-2ec0-4e66-8c5f-8a519be8ab4c)




What do you think?

**Comment by rogerguitart** [comment]
Hi @chrisisla , @tomhealey-icma ,

I've revised the workspace and recontributed the changes in the PR: #2659 (used to be 2625, but there was a bug in Rosetta that didn't allow me to recontribute). Following your suggestions, I've modified `CancelableProvision` and `ExtendibleProvision` by removing the americanExercise/bermudaExercise/europeanExercise fields and adding the `exerciseTerms` instead. I've also checked, and `OptionalEarlyTermination` also contains the american, bermuda, and european exercises inside, so I've removed them from here as well and added `exerciseTerms`. With these changes, the american/bermuda/european exercise type is never used in the model, so the `[deprecated]` annotation can stand. 

Additionally, I've also added the deprecated annotation to the `OptionStyle` and `OptionExercise`, given these were the old structures within optionPayout that are no longer being used anywhere in the model.

Could you revise these latest updates and let me know your thoughts? Thank you
