### ISSUE TITLE
!!Call for volunteers: Reference Data List Management

### ISSUE THREAD

**Issue by dshoneisda** [finos/common-domain-model#2642]
At the Steering WG on 9th January 2024, @brianlynn2 presented the recommendation from the task force assigned by the TAWG to look at reforming Ref Data List Management within the CDM.
This recommendation is attached below.

The SWG is calling for any volunteers to look at progressing this work to come forward to the maintainers or comment on this issue.

Offers to complete this work on a funded basis are also welcome. Quotes can be sent to the maintainers for consideration.
Please send through by **29th February**

[CDM.Ref.Data.Development.Strategy.for.Jan.2024.v3.pdf](https://github.com/finos/common-domain-model/files/14009235/CDM.Ref.Data.Development.Strategy.for.Jan.2024.v3.pdf)

**Comment by dshoneisda** [comment]
Only one proposal has come in, which is under discussion, and others have raised additional questions. Thus I am proposing the deadline for this is extended to 15th March to address those questions

**Comment by tomhealey-icma** [comment]
David - How was the RFP distributed and to whom?

**Comment by eteridvalishvili** [comment]
Hi @dshoneisda Has the deadline for this been extended, or is this issue ready to be closed?
