### ISSUE TITLE
CDM Technology Architecture WG - February 8th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2663]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
February 8th, 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2612
- [x] Discuss CDM Workshops for March-May @eteridvalishvili
- [x] Initiative Updates - @chrisisla 
  - [x] Serialisation
  - [x] Reference Data Lists
  - [x] Build Process
- [x] CDM News
  - [x] CDM Object Builder - @minesh-s-patel 
  - [x] Contribution of Rosetta DSL - @minesh-s-patel 
  - [x] ISDA CDM Portal being decommissioned - @minesh-s-patel 
  - [x] CDM Code Generator Workshop - @chrisisla 
- [x] Initiative Pipeline - @chrisisla 
  - [x] Present Proposed Roadmap - [TAWG Initiatives Roadmap 2024.pptx](https://github.com/finos/common-domain-model/files/14196887/TAWG.Initiatives.Roadmap.2024.pptx)
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] For future meeting - Discuss usage of native functions

## Minutes &  Discussion points

_Roadmap Suggestions_

- Dan
  - shows both inventory and status of initiatives
  - good to have links to the initiatives (links to github perhaps?)
  - Release Process should be renamed to Build Process
  - keep the completed initiatives (possibly on a separate slide?)
  - suggest the lead on each initiative present/update with status
- Minesh
  - contribute the roadmap to github so can retain old versions
  - suggest converting to markdown (liaise with Mao maybe?)
- Lyteck, Minesh, Brian
  - add milestones and proposed release versions
  - good to state whether initiative requires a major release i.e. breaking changes
  - difficult to state release versions as that is owned by SWG
  - agreed we have good co-ordination with the SWG so hopefully won't be any issues with getting specific changes into requested versions

## Action Items
- [x] Roadmap
   - [x] update roadmap to add links to initiatives - @chrisisla
   - [x] update roadmap to add proposed major releases - @chrisisla
   - [x] investigate using markdown instead of powerpoint for roadmap - @chrisisla
- [x] Add to next meeting Agenda
   - [x] review the updated roadmap
   - [x] discuss and prioritise existing initiatives
   - [x] Initial discussion on native functions if time
   - [x] Remind participants of TAWG initiatives that meetings under those initiatives still under FINOS non-competition guidelines

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by minesh-s-patel** [comment]
@minesh-s-patel / REGnosys

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by dschwartznyc** [comment]
Dan Schwartz/FT Advisory

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for Regnosys
