### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - February 14th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2666]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

February 14th, 2024 - 11:30 am EST / 4:30 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes (N/A)
   - [x] https://github.com/finos/common-domain-model/issues/2658
- [x] Price Return Swaps proposal- Fragmos/REGnosys/JPM - @Oblongs 
[Price Return Swap.pptx](https://github.com/finos/common-domain-model/files/14239739/Price.Return.Swap.pptx)
- [x] Commodity Forwards proposal- Manu Carrera, TradeHeader 
[commodityForwards.pptx](https://github.com/finos/common-domain-model/files/14268957/commodityForwards.pptx)
- [x] Day Count Fractions- Manu Carrera, TradeHeader  [RBAdayCountFractions.pptx](https://github.com/finos/common-domain-model/files/14269026/RBAdayCountFractions.pptx)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes-  

Minutes & Actions

Admin
-	DS ran through anti-trust statement and meeting notices
-	Past meeting minutes approved
-	DS notified attendees that next session would be 27th February NOT 28th February due to the CDM showcase on 28th; attendees to notify DS/FINOS if they do not see that in their diaries

Price Return Swap Proposal
-	LSG ran through the proposal on Fragmos’s behalf; this is to get the proposal out for critique well ahead of DRR deadlines
-	Questions were raised to be considered by Fragmos/JPM ahead of next DPBE:
o	 Why do the three ValuationPrice attributes and NotionalQuantity need to be added to both BasketConstituent and PortfolioPriceReturnTerms; the group was looking for a better understanding of the business use case for this.
o	ValuationPrice seems to be a conflating of two concepts- are they valuations or prices?
o	Is there a plan to introduce component weights explicitly rather than defining weights by notionals
o	There was a question on trade lots and whether increases were across the whole basket
-	Some concurrent changes being made to FpML for accumulators/deaccumulators; this should be co-ordinated with CDM; Lyteck took this as a takeaway. 
-	DS also agreed to follow up with Michelangelo to see if any other comments are forthcoming from ISDA’s Equity groups on the Market Infrastructure side (who were invited to the call)

Commodity Forwards
-	Proposal was challenged as inconsistent with current use of forwards for rate products
-	Explanation from commodity SME that due to the averaging properties and the physical vs cash delivery methods, as set out in the presentation, meant that single payout representation is not as easy as in the rates world
-	Agreed with proposal to make no model changes but for a task to be logged to look at improved modelling  post EMIR Go Live- Manu took this action

Day Count Fractions
-	Proposal presented and agreed by attendees
-	It was noted that this change has already been performed in FpML and should have been made concurrently in CDM, but that had not occurred
-	PR to achieve this to be submitted- Manu

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by HajnalOB** [comment]
Hajnal / REGnosys

**Comment by xlu208** [comment]
Xiaotian Lu / Bloomberg

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by manucarreramoreno** [comment]
Manuel Carrera / Tradeheader SL

**Comment by Oblongs** [comment]
Lionel Smith-Gordon @Oblongs for REGnosys

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
