### ISSUE TITLE
CDM Collateral Working Group - March 26th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2668]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

March 26th, 2023 - 10 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
   - [x] https://github.com/finos/common-domain-model/issues/2614 
 - [x] **Meeting 26th MARCH 2024 Slides** 
**[ISDA Common Domain Model - Collateral WG 26th Mar 2024.pdf](https://github.com/finos/common-domain-model/files/14743071/ISDA.Common.Domain.Model.-.Collateral.WG.26th.Mar.2024.pdf)**
- [x] **AGENDA 1** - CDM Eligible Collateral Member Feedback Update
- [x] **AGENDA 2** - Initial Margin Reporting u
[IM Reporting using CDM - CDM Collateral WG 26 March.pptx.pdf](https://github.com/finos/common-domain-model/files/14743960/IM.Reporting.using.CDM.-.CDM.Collateral.WG.26.March.pptx.pdf)
sing CDM 
- [x] **AGENDA 3** - CDM Collateral - Get started guide Update
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes- @eteridvalishvili 

- Comprehensive review of the implementation of CDM for calculating initial margin and collateral. 
- Key points from the presentation included:
  - Regulatory pressure and increased reliance on margin post-crisis were highlighted as drivers for standardized methodologies.
  - Standardized Schedule and SIM were discussed, with a focus on how CDM can be applied to these calculations.
  - Classification and functional language capabilities of CDM as essential tools for this project.
- Demonstrations using Rosetta to showcase the implementation of methodologies, challenges encountered, and next steps.
- Challenges discussed included composability of functions, sensitivity calculations, and data access limitations.
- Further research on sensitivities, contributing to the CDM repository, and exploring solutions for challenges identified.
- Feedback encouraged from all participants to drive further development.

## Action Items
- [x] **Action 1** 
Rehypothecation. 
In relation agenda 1 topic 1 ‘Margin Type’ detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 3. Members discussed adding to CDM a means for specifying ‘Rehypothecation’ choice to eligible terms as well as margin type. ISDA will review the options for such an addition and feedback to the WG in due course. 
If members of this group have further ideas or suggestions, please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [ ] **Action 2** 
Contract/ Transaction Type. 
In relation to agenda 1 topic 1 ‘Margin Type’ detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 3. Members discussed adding to CDM a means for specifying ‘contract/ transaction type’ such as (Repo, Loans, UMR) to apply to eligible terms as well as margin type, ISDA will review the options for such an addition and feedback to the WG in due course. 
If members of this group have further ideas or suggestions, please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [x] **Action 3** 
Connect Interest payment terms to Eligible Collateral 
In relation agenda 1 topic 3 ‘Interest Terms’ detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 6. Members were not against the proposal to connect Eligible Collateral to Distribution and Interest payment terms. ISDA will proceed with a CDM model extension and advise the WG once completed. 
- [x] **Action 4** 
Add Rating Priority Resolution 
In relation agenda 1 topic 4 ‘Rating Model detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 7. Members were not against the proposal to extend the CDM to enable the user to prioritise between Asset and Issuer ratings. ISDA will proceed with a CDM model extension and advise the WG once completed. 
- [x] **Action 5** 
Initial Margin Reporting using CDM
Please refer to the meeting material slides (IM Reporting using CDM). If members of the working group have any questions related to the presentation given by Marc Gratacos (Trade Header) please contact directly mailto:mgratacos@tradeheader.com
- [x] **Action 6** 
Get Started with CDM for Collateral 
With reference to agenda item No3 ‘Get Started with CDM for Collateral’, detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) paged 9- 18. Unfortunately, we ran out of time to cover this topic during the meeting. The work to develop this resource is underway and ISDA is approx.2/3 of the way through the project We would encourage members to review the slide material and provide any feedback, please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org). by 12th April

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by ziadzee** [comment]
Ziad Al-Ziadi, Banqora, ziadzee

**Comment by adamulman** [comment]
Adam Ulman / SmartStream

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by aidanrussell** [comment]
Aidan Russell / Banqora

**Comment by AmyCaruso** [comment]
Amy Caruso/ ISDA

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi/CloudMargin

**Comment by yniubb** [comment]
Yanwei Niu/ Bloomberg.

**Comment by acrangle-murex** [comment]
Aidan Crangle / Murex

**Comment by Alexis25091972** [comment]
Alexis Lucas / BNY Mellon

**Comment by Davezhou1** [comment]
David Zhou/ Citizens bank

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by valdensmith** [comment]
Vernon Alden-Smith ISDA
