### ISSUE TITLE
Overlap between the representation of the Package Transaction Price and Spread

### ISSUE THREAD

**Issue by gtarres** [finos/common-domain-model#2676]
## Background

Both, the Package Transaction Price and the Spread, are represented in the same place in the model, impeding the distinction between them. Currently, they are specified in:

- `WorkflowStep` -> `businessEvent` -> `packageInformation` -> `price`

- `WorkflowStep` -> `businessEvent` -> `after` -> `trade` -> `executionDetails` -> `packageReference` -> `price`

No way has been found to differentiate both cases within the current representation.

The attributes `packageInformation` and `packageReference` are of type `IdentifiedList`.

## Proposal

To add a new optional `Price` attribute in the `IdentifiedList` type representing the Package Transaction Spread.

![unnamed](https://github.com/finos/common-domain-model/assets/118831133/d9f8fa07-8113-4e5e-8da8-85c3bf3dd6b3)

**Comment by mgratacos** [comment]
The PR is available at: [2680](https://github.com/finos/common-domain-model/pull/2680)

**Comment by mgratacos** [comment]
Labels:
Minor Enhancement/Change
Category: Modelling
Criticality: High
Complexity: Low
Target: Production

**Comment by rogerguitart** [comment]
Hi @lolabeis, I've taken a look at the `arithmeticOperator` to distinguish a spread from a price. However, I think that relying solely on the presence of this field is not 100% restrictive - in theory it could still represent a commission or some type of fee which is not a spread, which would miss the purpose of this PR. Additionally, the definition of `arithmeticOperator` in Rosetta indicates that it could be a multiplier, min/max, among other possibilities. I was not involved in the development process of this, so there may be some context/information I am missing. Nevertheless, I think we still need a way to unequivocally identify a spread, and the proposal at hand does this.

Another approach that achieves the same objective could be to introduce a "Spread" value to the `PriceTypeEnum`. In FpML the enum `assetMeasureScheme` is used to distinguish a `PackagePrice` from a `PackageSpread`, so perhaps we could do the same in CDM. Looking forward to hearing your feedback on this.

FYI @mgratacos @gtarres @JBZ-Fragmos

**Comment by Oblongs** [comment]
Related issue that added the support for spread prices: https://github.com/finos/common-domain-model/issues/2183

**Comment by tomhealey-icma** [comment]
I don't think we should add each price type as an attribute, instead allow multiple prices and tag the price type at a lower level. Otherwise we would need to add yield, discount, premium and other types of prices.

**Comment by lolabeis** [comment]
This issue has been resolved using existing model components, without the need to change the model
