### ISSUE TITLE
REGRESSION in ISDA-Foundation - IndexAdjustmentEvent Type is corrupted ( FRAGMOS ) 

### ISSUE THREAD

**Issue by JBZ-Fragmos** [finos/common-domain-model#2679]
The current type attributes for **IndexAdjustmentEvent** are **WRONG** : 

![image](https://github.com/finos/common-domain-model/assets/92978493/b97b3848-57c8-4175-895b-7391679ec02a)

![image](https://github.com/finos/common-domain-model/assets/92978493/98610ae3-f281-40ee-bcf9-e71e7336fac4)

Hereunder **CORRECT** type / related attributes : 

![image](https://github.com/finos/common-domain-model/assets/92978493/e0f0cde8-b737-4fab-9a16-cab782bc378a)

**Comment by JBZ-Fragmos** [comment]
@eacunaISDA : hi, any feedback / timeline for resolving this one please ?

**Comment by llynhiavu** [comment]
Thanks @JBZ-Fragmos. I confirm that you fixed it in your ISDA Foundations / open contribution (July 22,2024 3.0.0-dev-9)

as:

type IndexAdjustmentEvents: <"Defines the specification of the consequences of Index Events as defined by the 2002 ISDA Equity Derivatives Definitions.">
    indexModification IndexEventConsequenceEnum (1..1) <"Consequence of index modification.">
    indexCancellation IndexEventConsequenceEnum (1..1) <"Consequence of index cancellation.">
    indexDisruption IndexEventConsequenceEnum (1..1) <"Consequence of index disruption.">

**Comment by JBZ-Fragmos** [comment]
Thanks a lot !

Yet could you please send me the link to the PR itself ? I should be able to access any PR I contribute, and original problem for me here is that for now cannot access to PR for Foundation (as of today I can only access to PR for CDM)

**Comment by llynhiavu** [comment]
https://github.com/rosetta-models/isda-foundations/pull/65

you are not listed on it though.
