### ISSUE TITLE
Possible gap in Qualify_AssetClass_InterestRate and Qualify_AssetClass_Commodity

### ISSUE THREAD

**Issue by modobez** [finos/common-domain-model#2683]
It seems to us that the following qualifiers may be missing some logic:

**Qualify_AssetClass_InterestRate**

- 	when checking whether the optionUnderlier is an interestRate, shouldn't the function also probe the 'security' path? In addition to checking under the contractualProduct as is currently the case:

`Qualify_AssetClass_InterestRate( optionUnderlier -> contractualProduct -> economicTerms ) `

**Qualify_AssetClass_Commodity**
- 	same concern as above
- 	missing logic for commo futures under the forwardPayout, which would look something like adding 

> `        // CO Fwd
>         or (economicTerms -> payout -> forwardPayout only exists
>             and if forwardUnderlier exists
>                 then (Qualify_AssetClass_Commodity(forwardUnderlier -> contractualProduct -> economicTerms)
>                       or Qualify_AssetClass_Commodity(forwardUnderlier -> security -> economicTerms)
>                       or forwardUnderlier -> commodity exists
>                       )
>             )
> `

On the DRR side, this has impacts on the Asset Class field; corresponding issues are:
- DRR ISSUE-698: CDM is not able to source for ETD underliers
- DRR ISSUE-689: CDM gap for Commodity futures

**Comment by Oblongs** [comment]
Mathieu - I discussed briefly with TradeHeader colleagues yesterday.  I think the logic needs expansion for a greater variety of ETD products - eg a US Treasury Future, which has an underlier with `securityType` = Loan.

All the ETD samples should be validated that they create the right product qualification when used in a swaption:
https://github.com/rosetta-models/digital-regulatory-reporting/tree/master/rosetta-source/src/main/resources/regulatory-reporting/input/etd
