### ISSUE TITLE
CDM Structured Products WG - March 12th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2738]
# CDM Structured Products Working Group Minutes
Meeting Host: Jean-Baptiste Ziadé, Fragmos Chain 

## Date
March 12th, 2024 - 10am ET / 3pm GMT

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
  - [x] https://github.com/finos/common-domain-model/issues/2664
- [ ] New term-sheet to model “Acc/Decumulator” features
- [ ] Continue our review of model components documented in GitHub Issues – this time we will review “Knock” object
- [x] Upcoming In-person [NYC Workshop Survey](https://www.surveymonkey.com/r/7QLNWMZ)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- Enriching the discussion on financial products rather than removing elements.
- Discussed the need for specificity in observations and underlying assets.
- Emphasized the necessity of clear terms and documentation to avoid misunderstandings.
- Encouraged feedback and questions on the proposal via GitHub.
- Continued the discussion on financial products and derivatives, focusing on observations, underlying assets, and conditions for payouts.
- Mentioned the importance of clearly specifying terms to avoid ambiguity.
- Examples of various financial products and payout conditions.
- Reminded participants to review the proposal and provide feedback.
- Encouraged a positive approach to describing proposals and suggested using visuals for clarity.

## Action Items

- [ ] Participants to review the proposal and provide feedback

### Zoom info
Join Zoom Meeting
https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09

Meeting ID: 921 3608 7343
Passcode: 861434
Find your local number: https://zoom.us/u/ad5NMLeH9R

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski
