### ISSUE TITLE
CDM Steering Working Group - March 12th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2739]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
March 12th, 2024  - 11am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2665
- [x] Update and plans into Q2 for Product/Asset Proposal - @lolabeis / @Oblongs [10 min] 
[Asset-Product-Observable SteerCo 12Mar24.pdf](https://github.com/finos/common-domain-model/files/14541750/Asset-Product-Observable.SteerCo.12Mar24.pdf)
- [x] CDM 6.0 release and 4.x retiring proposals @lolabeis 
[CDM 6.0 release and 4.x retiring.pptx](https://github.com/finos/common-domain-model/files/14572446/CDM.6.0.release.and.4.x.retiring.pptx)
- [x] Update on Release Build and Governance conversations @tomhealey-icma [10 min]
- [x] Change Control discussion @brianlynn2 [10 min]
[CDMChangeControlGuidelines.pptx](https://github.com/finos/common-domain-model/files/14539388/CDMChangeControlGuidelines.pptx)

- [x] New Maintainer proposal @chrisisla [10 min]
- [x] Editor/Triage role update and call for proposals @eteridvalishvili & @dshoneisda [5 min]
- [x] Update on Ref Data List/Serialisation initiatives @dshoneisda & @chrisisla [5 min]
- [x] [CDM Code Generator Workshop](https://regnosys.com/insights/cdm-code-generator-workshop-proves-a-success/) update @chrisisla @minesh-s-patel [10 min]
- [x] Open call for updates from other WGs
- [x] AOB

## Minutes

**Approve past meeting minutes**
Minutes were approved
It was noted that application to install Lyteck Lynhiavu as maintainer was approved
@eteridvalishvili to ensure @llynhiavu is added to maintainers list and documented on the website

 
 **Update and plans into Q2 for Product/Asset Proposal** 
@oblongs ran through proposals in attached material and invited volunteers to join up for a task force that will develop this proposal with a view to being put in place for CDM 6.0
Proposal is detailed here: https://github.com/finos/common-domain-model/issues/2805
Task force meeting number 1 takes place on 28th March and agenda details can be found here: https://github.com/finos/common-domain-model/issues/2807

 CDM 6.0 release and 4.x retiring proposals 
@lolabeis walked the group through attached materials detailing plans to retire support for CDM 4.x and move towards a release of CDM 6.0 at end of Q2.
Question as to why Q2- the refactoring is quite major and the sooner it is done the less time will have passed for additional dependencies to have been incorporated/built upon current versions
@dshoneisda noted that at least one party was near to using CDM 4.x in Production and should be given a chance to be involved in the discussion prior to the lapsing of support for 4.x- this was agreed

 Update on Release Build and Governance conversations 
@tomhealey-icma noted that much feedback had come in. This will be summarised and @tomhealey-icma will arrange further calls where there remains dispute
Summaries are recorded in the following issues:
[Proposal 1: Draft PRs and Ready for Review](https://url.usb.m.mimecastprotect.com/s/q1xZCXY91rUl11gQu60vs9?domain=github.com): [2789](https://url.usb.m.mimecastprotect.com/s/q1xZCXY91rUl11gQu60vs9?domain=github.com)
https://url.usb.m.mimecastprotect.com/s/aXTHCYV92yIKQQv7TGNMWN?domain=github.com: [2792](https://url.usb.m.mimecastprotect.com/s/aXTHCYV92yIKQQv7TGNMWN?domain=github.com)
https://url.usb.m.mimecastprotect.com/s/xMvpCZZ93zc1EEw6IKRnal?domain=github.com: [2793](https://url.usb.m.mimecastprotect.com/s/xMvpCZZ93zc1EEw6IKRnal?domain=github.com)
https://url.usb.m.mimecastprotect.com/s/oF-IC1Vv2GIr1104hX1zPQ?domain=github.com: [2794](https://url.usb.m.mimecastprotect.com/s/oF-IC1Vv2GIr1104hX1zPQ?domain=github.com)
https://url.usb.m.mimecastprotect.com/s/FxgVC2Gw37iLvv4YU9W9um?domain=github.com: [2795](https://url.usb.m.mimecastprotect.com/s/FxgVC2Gw37iLvv4YU9W9um?domain=github.com)

@jiahaodengbb asked about summary documentation @tomhealey-icma said this would follow once these points are agreed upon

 Change Control discussion 
@brianlynn2 presented ideas for change control as per material attached. As much of this information is related to the efforts of @tomhealey-icma on the release build and governance, @dshoneisda advised this material to be fed directly into those conversations. This has been incorporated in the issues above

 New Maintainer proposal 
@chrisisla made the proposal for one maintainer lapse and two new maintainers. Details of these have gone to vote for review at next SWG
Issues explaining rationale and bios are here: 
https://github.com/finos/common-domain-model/issues/2771
https://github.com/finos/common-domain-model/issues/2770

 Editor/Triage role update and call for proposals 
@eteridvalishvili confirmed the triage role is present. It will need updates to allow Editors to label PRs. @eteridvalishvili  to confirm when done
@dshoneisda proposed that key contributors would then be given Editor status so they can label PRs and issues and take the burden off maintainers. Initial proposals were that this would encompass staff from TradeHeader, Fragmos Chain and FT Advisory. This was agreed
Further Editor proposals should be made to the maintainers by mail

 Update on Ref Data List/Serialisation initiatives 
@dshoneisda & @chrisisla confirmed that funding for these was on hold again higher in the sponsoring associations' management structures; future updates will of course be given

 CDM Code Generator Workshop update 
@chrisisla ran briefly through the material attached

There was no time for AOB.

 
### Zoom info
Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09

Meeting ID: 937 5620 5037
Passcode: 911071
Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by ziadzee** [comment]
Ziad Al-Ziadi (Antler)
Ernst Dolce (Antler)
Aidan Russell (Antler)

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by mikealambert** [comment]
Mike Lambert / Broadridge

**Comment by DIVA291265** [comment]
Daniel Ivanier / Fragmos Chain

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by jiahaodengbb** [comment]
Jiahao Deng / Bloomberg

**Comment by lolabeis** [comment]
As just mentioned on the call, regarding the **Update on Release Build and Governance conversations** topic, here are some relevant open "Discussions" on GitHub:
#2423 
#2305 
#2422

**Comment by tomhealey-icma** [comment]
A new issue has been opened for release governance, [2773](https://github.com/finos/common-domain-model/issues/2773).

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys
