### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - March 13th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2740]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

March 13th, 2024 - 11:30 am EST / 3:30 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
   - [x] https://github.com/finos/common-domain-model/issues/2669
- [x] Price Return Swap & Accumulators revised proposals @JBZ-Fragmos (30 min)
[Price Return Swap & Accumulator _ FINAL Deck v2.pptx](https://github.com/finos/common-domain-model/files/14572464/Price.Return.Swap.Accumulator._.FINAL.Deck.v2.pptx)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes-  

- Past minutes were approved
- JB at Fragmos walked through his deck. 
- Swap product model was approved for submission. This has been submitted and merged: https://github.com/finos/common-domain-model/pull/2776
- Accumulator/Deaccumulator required further review and digestion by those on the call- questions and conversation continued here: https://github.com/finos/common-domain-model/pull/2765
- Aim is to present updated proposal on Accumulator/Deaccumulator at DPBE on 27th March
- DS noted that the timing of next DPBE would also be adjusted due to the US clock change, then return to normal

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by JBZ-Fragmos** [comment]
JB Ziadé / FRAGMOS

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by Oblongs** [comment]
Lionel Smith-Gordon/Oblongs for REGnosys

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by HajnalOB** [comment]
Hajnal Orban-Bakk/REGnosys
