### ISSUE TITLE
CDM Technology Architecture WG - March 14th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2741]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
March 14th, 2023 - 10 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2663
- [x] Upcoming In-person [NYC Workshop Survey](https://www.surveymonkey.com/r/7QLNWMZ)
- [x] Remind participants of TAWG initiatives that meetings under those initiatives still under FINOS non-competition guidelines
- [x] Review the updated roadmap - [TAWG Initiatives Roadmap 2024-03.pptx](https://github.com/finos/common-domain-model/files/14561130/TAWG.Initiatives.Roadmap.2024-03.pptx) (10 mins)
- [x] Update on Reference Data (10 mins)
- [x] Update on Build Process (5 mins)
- [x] Discuss and prioritise existing initiatives (20 mins)
 - Versioning
 - Interoperability
 - Change Control
 - Testing
 - Standard Error Handling
 - Native Functions
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] Asset/Product rewrite: #2739

## Minutes &  Discussion points

_Roadmap_
- Chris explained that might start using milestones and add issues to automatically generate a roadmap
- Still being discussed though so for now just updating the Powerpoint

_Reference Data_

Tom
- Scope of the work was possibly too large
- This made it hard for individuals or firms to contribute a piece of the requirement
- Agreed that the task force should come back together to discuss again

Dan
- Also agreed we should open the discussion again
- Could possibly decrease the scope
- But need to ensure take care not to do so and introduce increased technical debt
- Suggested first reviewing priority of initiatives before revisiting the recommendation

_Prioritisation_
- Adrian suggested that we should align on priority based upon what the current focus for CDM is
- Chris confirmed that general feedback from everyone is that CDM Adoption is the current priority
- Elias stated that to get more adoption from the street side, interoperability between systems and CDM versions should be the priority
- Elias also confirmed that they want to use the CDM as the common language for data and processing, not just as a message standard for example
- Adrian agreed with Elias, and also stated that better testing will give firms more confidence in the model and improve stability
- Adrian confirmed that testing of Rosetta functions should be available, in different languages and also in different versions
- Dan agreed that testing in python should be added, as well as implementing python support for functions
- Tom also agreed that testing at the moment involved creating JSON input/output files and then calling the java functions, which was restrictive
- Overall looks like Rosetta testing should be expanded, with ability to create unit tests
- Brian suggested our initiative list could already be too specific, we should perhaps think a level above and map out our goals
- Elias suggested focusing on a single use case might help us map these out
- Adrian said that for him serialisation and the ability to easily migrate between versions were a priority
- Adrian also suggested we could look at what the minimum requirements would be to get the CDM into production at a firm - this in turn will help us decide what we can compromise on now
- Overall, if our vision is adoption then what are our goals to drive that?
- It was agreed that a separate call be setup for interested parties to spend an hour defining these goals and use this to drive our priorities

## Action Items

- [x] Email everyone who agreed to take part on the goals and prioritisation call - @chrisisla 
- [x] Put together an initial presentation based upon the discussions to start the conversation - @chrisisla 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by jiahaodengbb** [comment]
Jiahao Deng / Bloomberg

**Comment by ahutusoru123** [comment]
Adrian Hutusoru / Fragmos Chain

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by aidanrussell** [comment]
Aidan Russell / Banqora

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by eelramy92** [comment]
Elias / Societe Generale
