### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - March 27th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2743]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

March 27th, 2024 - 11:30 am EST / 3:30 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
   - [x] https://github.com/finos/common-domain-model/issues/2740
- [x] Enhanced Contractual Party Mappings https://github.com/finos/common-domain-model/issues/2788 PR [#2806](https://github.com/finos/common-domain-model/pull/2806) @manel-martos @gopazoTH 
- [x] Updated proposals for Accumulators
[AccDecumulator & DifferentialPricePayout _ Deck v0.pptx](https://github.com/finos/common-domain-model/files/14757659/AccDecumulator.DifferentialPricePayout._.Deck.v0.pptx)
, PR: https://github.com/finos/common-domain-model/pull/2765- @JBZ-Fragmos 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes-  

Admin
•	Roll call and meeting notices/policy statements performed
•	Past Meeting Minutes were approved, with note from @lolabeis that the swaps PR from last meeting needed to be also committed on the dev branch, not just the Prod- Action: @JBZ-Fragmos

Enhanced Contractual Party Mappings
•	@gopazo presented proposal which is purely a mappings change to populate fields correctly from FpML, no model change involved
•	Proposal passed

Update proposals for Accumulators
•	@JBZ-Fragmos presented proposals from slides
•	Members of the community raised issues with terminology of knock in/out and how clear that was
•	It was also raised that any model should be generic across all asset classes, not just equities
•	A discussion ensued as to the goal of what was trying to be achieved, which is for the model to contain enough to support DRR
•	Outcome:
o	True modelling of the product will be a lengthy and complex effort, that best belongs in the structured product WG- ISDA is unlikely to fund the full modelling of the product, and community members should make proposals for review
o	To achieve what is required for JPM & Pictet for DRR @JBZ-Fragmos will keep the cumulation feature as an empty type which will then be used in the qualifier
o	@JBZ-Fragmos to agree with JPM & Pictet whether they need a simple enum to indicate accumulator vs deaccumulator
o	DRR reporting will be done as “Equity Other”, with reporting fields pulled from existing forward or option fields

AOB
•	There was no other business proposed

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by Oblongs** [comment]
Lionel Smith-Gordon/Oblongs for REGnosys

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by gopazoTH** [comment]
Gerard Opazo / TradeHeader

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tzurcher** [comment]
tzurcher / Pictet

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by HajnalOB** [comment]
Hajnal/Regnosys

**Comment by nicholas-moger** [comment]
Nick Moger (JPM)

**Comment by dschwartznyc** [comment]
Daniel Schwartz/FT Advisory
