### ISSUE TITLE
Qualify_AssetClass_%  gap for index

### ISSUE THREAD

**Issue by modobez** [finos/common-domain-model#2762]
**Qualify_AssetClass_InterestRate**

When checking whether the optionUnderlier/forwardUnderlier is an interestRate, shouldn't the function also probe the 'index' path? This would be in addition to the current check on  `security -> securityType = SecurityTypeEnum  -> Debt`.

```
       economicTerms -> payout -> interestRatePayout only exists
            or (economicTerms -> payout -> optionPayout only exists
                and ( (optionUnderlier -> security -> securityType = SecurityTypeEnum -> Debt
                        or optionUnderlier -> index -> productTaxonomy -> primaryAssetClass = InterestRate
                      ) 
                    or if optionUnderlier exists
                        then Qualify_AssetClass_InterestRate(
                                    optionUnderlier -> contractualProduct -> economicTerms
                                ) = True
                                or Qualify_AssetClass_InterestRate(
                                    optionUnderlier -> security -> economicTerms
                                ) = True))
            or (economicTerms -> payout -> forwardPayout only exists
                and (forwardUnderlier -> security -> securityType = SecurityTypeEnum -> Debt
                    or forwardUnderlier -> index -> productTaxonomy -> primaryAssetClass = InterestRate
					)
                 )
```

On the DRR side, this has impacts on the EMIR Asset Class field and possibly other AssetClass-dependent fields

**Comment by manucarreramoreno** [comment]
DEV PR: https://github.com/finos/common-domain-model/pull/2838
PROD PR: https://github.com/finos/common-domain-model/pull/2839

**Comment by manucarreramoreno** [comment]
A regression on the qualification of Bond Options and Forwards was spotted after contributing. The necessary changes were made before releasing in prod, but not in dev. The following PR fixes this in dev: https://github.com/finos/common-domain-model/pull/2850
