### ISSUE TITLE
Bonds classification as credit or interest rate

### ISSUE THREAD

**Issue by modobez** [finos/common-domain-model#2763]
Discussions in the EMIR Refit Technical Execution working group showed that bonds classification remained somewhat ambiguous.

In particular, we may need to refine the current logic to, for example, distinguish between sovereign  vs corporate debt so that e.g.
* sovereign -> rate
* corporate -> credit

No matter the conclusion, it would be helpful to add the decision and supporting arguments as "rationale" or comments.

On the DRR side, this impacts the EMIR Asset Class field and possibly other AssetClass-dependent fields.

**Comment by tomhealey-icma** [comment]
This is a taxonomy classification issue that should not be baked into the model. The question of sovereign vs corporate is already addressed based on the issuer/issuertype.

**Comment by mgratacos** [comment]
issuer/issuerType is only available at the collateral level, not at the product/underlyer representation.

**Comment by tomhealey-icma** [comment]
The issuer is fixed and can be linked to an party LEI, therefore I would suggest adding it to productBase. The issuer type is subject to a domain's definition. If we are going to include one specific domain's definition we would need to agree on what standard to use. Otherwise and other domain's can be included in the taxonomy definition.

**Comment by mgratacos** [comment]
I think we can close this issue since from a regulatory perspective, all credit derivative products are classified as asset class "Credit" independently from whether the Bond is Sovereign or Corporate.

**Comment by eteridvalishvili** [comment]
Hi @modobez The issue seems resolved based on the information provided earlier. Please feel free to reopen the issue if necessary. Thank you!
