### ISSUE TITLE
Proposed addition of new Maintainers: Marc Gratacos and Manuel Martos

### ISSUE THREAD

**Issue by chrisisla** [finos/common-domain-model#2771]
As raised at the last SWG (Issue https://github.com/finos/common-domain-model/issues/2739) it has been proposed that two new maintainers should be added in recognition of the contribution that they have given - and continue to give - to the CDM. 

The proposal is that Marc Gratacos (@mgratacos) and Manuel Martos (@manel-martos) are added as maintainers of the CDM. They will be Organisation Representatives, representing TradeHeader. 

Could the current maintainers please indicate their approval by comment/thumbs up reaction below please. Proposal that majority approval will then be actioned at the next SWG in April.

@mgratacos and @manel-martos - please could you add your short bios as comments to this Issue.

**Comment by chrisisla** [comment]
@llynhiavu

**Comment by mgratacos** [comment]
Marc Gratacos is a Managing Partner at TradeHeader. TradeHeader, founded in 2011, is a global consulting firm focused on financial standards such as CDM, FpML, FIX, and ISO 20022. The firm also provides software development and training services. Prior to founding TradeHeader, Marc was a Technical Architect at the International Swaps and Derivatives Association, Inc. (ISDA). He helped to develop FpML (Financial products Markup Language) providing support, analysis, and technical expertise.
Mr. Gratacos received his Masters Degree in information management and systems from the University of California, Berkeley and his BA in economics from the Universitat Pompeu Fabra in Barcelona.

**Comment by dshoneisda** [comment]
I am supportive of the addition of Marc and Manuel. No objections from ISDA

**Comment by manel-martos** [comment]
Manuel Martos is the Chief Technology Officer at Tradeheader, a global consulting firm specializing in financial standards, training and software development. With over a decade of experience in the industry, Manuel has held various tech leadership roles where he successfully implemented innovative solutions to drive business growth and enhance operational efficiency for the industry participants.
Mr. Manuel received his Telecommunication Engineer Degree from the Universitat Politècnica de Catalunya in Barcelona.

**Comment by chrisisla** [comment]
Having spoken to a number of the maintainers the general feeling is that elections like this are best performed over email or other mediums rather than using github Issues. I will email all the maintainers to organise the vote and update this Issue with the results once confirmed.

**Comment by chrisisla** [comment]
This motion has been successfully carried by majority vote of the CDM Maintainers. The decision will be ratified at the next CDM Steering Working Group on April 16th.

**Comment by chrisisla** [comment]
The decision was ratified at the Steering Working Group on April 16th, closing this Issue now.
