### ISSUE TITLE
CDM Asset Refactor Task Force - March 28th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2807]
# CDM Asset Refactor Task Force Minutes
Meeting Host: Lionel Smith Gordon, Regnosys

## Date
March 28th, 2024 - 11am ET / 3pm GMT

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Recap of Proposal
- [ ] Refactoring plan and Task Force cadence
- [ ] AOB, Q&A & Adjourn (5mins)

Materials for this meeting:

[ARTForce 28Mar24.pptx](https://github.com/finos/common-domain-model/files/14761603/ARTForce.28Mar24.pptx)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/91947398280?pwd=YS85Mmo4ejhvV2VKMlpaU1FmeDYydz09

Meeting ID: 919 4739 8280
Passcode: 867245

**Comment by Oblongs** [comment]
Materials for this meeting:

[ARTForce 28Mar24.pptx](https://github.com/finos/common-domain-model/files/14761603/ARTForce.28Mar24.pptx)

**Comment by nicholas-moger** [comment]
Nick Moger (JPM)

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by AdrianJenksD2LT** [comment]
Adrian Jenks / D2LT

**Comment by duncancarpenterpirum** [comment]
Duncan Carpenter / Pirum

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
