### ISSUE TITLE
Could not resolve rosetta-common

### ISSUE THREAD

**Issue by maoo** [finos/common-domain-model#2811]
Hi there! Together with @tomhealey-icma , we're trying to consume CDM from a Gradle build, but we get the following error:

```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.regnosys:rosetta-common:10.15.0.
     Required by:
         project : > org.finos.cdm:cdm-java:6.0.0-dev.27
      > Could not resolve com.regnosys:rosetta-common:10.15.0.
         > Could not get resource 'https://regnosys.jfrog.io/regnosys/libs-release/com/regnosys/rosetta-common/10.15.0/rosetta-common-10.15.0.pom'.
            > Could not GET 'https://regnosys.jfrog.io/regnosys/libs-release/com/regnosys/rosetta-common/10.15.0/rosetta-common-10.15.0.pom'. Received status code 401 from server:
```

Steps to reproduce:
```
git clone git@github.com:finos/traderX.git
cd traderX
git checkout cdm-trade-processor
cd trade-processor
./gradlew build
```

I assume that the same issue can be reproduced in Maven. Please make sure to run without any authentication against the Regnosys artifact manager.

**Comment by maoo** [comment]
```
BUILD SUCCESSFUL in 2m 41s
5 actionable tasks: 2 executed, 3 up-to-date
```

Adding the https://regnosys.jfrog.io/regnosys/libs-snapshot-local repository did the trick, see https://github.com/finos/traderX/commit/45a7fbd541334d2f1e33dcd0e99b703a2fad4a84

**Comment by minesh-s-patel** [comment]
@tomhealey-icma 

Since this issue was created/closed, we have moved all CDM dependencies (including rosetta/rune common) to maven central - so it should work.

Can you paste the full error please?

**Comment by tomhealey-icma** [comment]
Changed the CDM version and it's working now.
