### ISSUE TITLE
[FIXED] Synonym mappings for FpML coding schemes v2-17 are missing in CDM

### ISSUE THREAD

**Issue by ebataller** [finos/common-domain-model#2812]
Background
----------

The version [2-17](https://www.fpml.org/specs_news/publication-of-a-new-set-of-fpml-coding-schemes-catalog-version-2-17/) of the FpML coding schemes was published on February 15, 2024. This new version included some changes that are already present in the corresponding enumerations of the CDM model, but the synonym mappings from FpML to CDM have not been updated to cover the latest changes.

Proposal
--------
The following PRs will add these updated synonym mappings from FpML to CDM for dev:
LinkIdSchemes: [#2852](https://github.com/finos/common-domain-model/pull/2852)
BusinessCenterEnum values: [#2853](https://github.com/finos/common-domain-model/pull/2853)

**Comment by ebataller** [comment]
Tags:
Category: Modelling
Complexity: Small/Bug/Mapping
Criticality: Medium/Low
Target: Development and Production

**Comment by eteridvalishvili** [comment]
Hi @ebataller Can you confirm if this issue is still relevant or whether it can be closed? Please let the CDM maintainers or me know if you have any questions.

CC: @hugohills-regnosys

**Comment by ebataller** [comment]
Hi @eteridvalishvili thanks for bringing this up, the PR [#2852](https://github.com/finos/common-domain-model/pull/2852) is still pending to be contributed, if it can be approved by mantainers.

CC: @hugohills-regnosys
