### ISSUE TITLE
CDM Contribution Review Working Group - April 2nd, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2815]
# CDM Contribution Review Working Group Minutes
Meeting Host: Tom Healey, ICMA

## Date
April 2nd, 2024 - 10 am ET / 3 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2742
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- @tomhealey-icma provided an overview of the current pull requests (PRs) in the GitHub repository, mentioning that there were no major changes. He requested attendees to review the existing PRs.
   - Noted that some PRs were under review, while others were still pending comments.
   - There was discussion about a duplicate draft issue in the GitHub repository, which was identified as already completed. @eacunaISDA agreed to investigate and resolve the issue.
   - Tom highlighted a PR submitted in December that was still pending comments. He urged maintainers to review and provide feedback on it.
- Mention of a PR related to updating mappings from FPML to CDM, but it lacked labels. Tom suggested adding labels manually or working with someone who has access to add them.
- @eteridvalishvili provided an update on creating a new group for contributors to add labels. The group creation was in progress, pending approval at the next steering working group meeting.
- @tomhealey-icma agreed to add labels to the PR and noted a build issue with it.
- A new joiner, sought advice on getting started with making contributions. Tom advised familiarizing oneself with the project, forking a branch, and ensuring the build process works correctly. 

## Action Items

- [x] @eacunaISDA  to investigate and resolve the duplicate draft issue in the GitHub repository.
- [x] Maintainers to review and provide feedback on the PR submitted in December.
- [x] @tomhealey-icma to add labels to the PR and participant to address the build issue.
- [x] @eteridvalishvili to update the README with information for contributors that are interested in having editing permissions. 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: https://zoom.us/u/a3KWGNquN

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by bohuang19** [comment]
Bo Huang/Bloomberg

**Comment by ebataller** [comment]
Eric Bataller / Tradeheader

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
