### ISSUE TITLE
CDM Technology Architecture WG - April 11th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2819]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
April 11th, 2023 - 9 am EST / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2741
- [x] TAWG Vision Statement - [TAWG Vision Statement.pptx](https://github.com/finos/common-domain-model/files/14934979/TAWG.Vision.Statement.pptx)

- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points
_TAWG Vision Statement_
- There was general consensus on an initial version
- A github Discussion was suggested so people can comment before we finalise (propose for next meeting)
- Adoption and Production were discussed
- The presentation was updated with peoples comments - [TAWG Vision Statement.pptx](https://github.com/finos/common-domain-model/files/14958250/TAWG.Vision.Statement.pptx)
- Agreed a github Discussion for comments on the meaning of Adoption was a good idea too

## Action Items
- [x] Create github Discussion so people can comment on the TAWG Vision Statement - @chrisisla - see #2858 
- [x] Create github Discussion so people can comment on what we mean by Adoption - @chrisisla - see #2859 
- [x] Group to review the updated presentation and Discussions so at the next meeting we can:
  - [x] Finalise the Vision Statement
  - [x] Formalise list of elements that form Adoption

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by eelramy92** [comment]
Elias El Ramy/Societe Generale

**Comment by dschwartznyc** [comment]
Dan Schwartz/FT Advisory

**Comment by code-ghalib** [comment]
Rahul Kumar / Bloomberg LP

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by chrisisla** [comment]
Chris Rayner/ISLA

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
