### ISSUE TITLE
CDM Steering Working Group - April 16th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2821]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
April 16th, 2024  - 11am ET / 4pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2739
- [x] Follow ups/Updates from previous meeting:
   - [x] @eteridvalishvili to ensure @llynhiavu is added to maintainers list and documented on the website- Confirm complete
   - [x] CDM 6.0/4.x proposals- opportunity for feedback from group
   - [x] Update on Release Build and Governance conversations @tomhealey-icma 
   - [x] Update on Asset Refactoring Task force progress @Oblongs 
[ARTForce Steering Update 16Apr24.pptx](https://github.com/finos/common-domain-model/files/14994962/ARTForce.Steering.Update.16Apr24.pptx)
   - [x] New maintainer proposal- TradeHeader comprised of two reps @chrisisla 
   - [x] Maintainer removal proposal @chrisisla 
   - [x] Ref Data/Serialisation initiatives @dshoneisda 
- [x] Roadmap review- updates are required @dshoneisda 
- [ ] AOB

## Minutes

- Meeting admin completed
- Previous minutes were approved
- @eteridvalishvili confirmed @llynhiavu was now on the website and added to maintainers list
- Group had no further feedback on CDM 6.0 plans and 4.x support. @dshoneisda reminded @lolabeis that one member will need to upgrade and @dshoneisda continued to chase to arrange discussion [discussion has now been arranged for w/c 29th April]
- Release build & governance: It was agreed that final commentary could be made on existing discussions by COB 19th April. @tomhealey-icma took action to then summarise for maintainers, where no clear consensus was formed a meeting should then be set up to cast a vote [@tomhealey-icma circulated summary 23rd April]
- @Oblongs presented progress on ART based on material attached. @tomhealey-icma questioned whether agreed items had formally been ratified. This discussion to continue in the task force itself. @lolabeis reminded the group of the time and budget pressure, with a view to getting the changes done by May so that testing could take place in June if the deadline of end of Q2 is to be hit
- @chrisisla reported results of maintainer discussions. @manel-martos @mgratacos are both ratified as new maintainers. @iansloyan's maintainership rescinded. @eteridvalishvili to make necessary updates to website and maintainers distribution list
- @dshoneisda noted that funding for serialisation and ref data proposals remains locked while senior TA discussions continue. As such updates on this topic will resume only when those are complete
- @dshoneisda asked the chairs of all of the WGs represented on the current roadmap to review, make updates and send to @eteridvalishvili to update the website
- There was no AOB

### Zoom info
Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09

Meeting ID: 937 5620 5037
Passcode: 911071
Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by dschwartznyc** [comment]
dan schwartz/ft advisory

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
