### ISSUE TITLE
CDM Contribution Review Working Group - April 16th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2823]
# CDM Contribution Review Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
April 16th, 2024 - 10 am ET / 3 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2815
- [x] Pull Requests
  - [x] #2810 - @chrisisla 
  - [x] #2808 - @chrisisla 
- [x] Issues
  - [x]  #2854 - @rogerguitart 
    - [x]  Associated PRs:
      - [x] #2855 
      - [x] #2856
- [x]  Adding Qualification FX Non Deliverable Swap- proposal @manucarreramoreno 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
_Discussion on TRS change_ #2854
- Questions raised around qualification of baskets
- General consensus that qualification needs work, to do as part of ART Force
- Agreed that this change looks okay for now with that caveat
- To be included in next prod release 5.10

_Discussion on FX Non-Deliverable Swap_
- Query on whether this was solely associated to reporting
- Existing qualification of swaps does not take all required data points into account
- Felt though that this incremental change was okay
- Intend to also include in 5.10

_Python change_
- Fix for the Python code generator
- Not a breaking change and needs to go into prod version i.e. should not wait for 6.0
- Dan will liaise with maintainers to confirm

## Action Items
- [ ] Move ahead with TRS change - @rogerguitart 
- [ ] Move ahead with FX Non-Deliverable Swap - @manucarreramoreno 
- [ ] Liaise with maintainers in relation to the Python fix - @dschwartznyc 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: https://zoom.us/u/a3KWGNquN

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziadé - FRAGMOS

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by tabi5h** [comment]
Tabish/ISDA

**Comment by manucarreramoreno** [comment]
Manuel Carrera / TradeHeader

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by bohuang19** [comment]
Bo Huang/ Bloomberg
