### ISSUE TITLE
CDM Collateral Working Group - April 30th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2826]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

April 30th, 2023 - 10 am EST / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
   - [x] https://github.com/finos/common-domain-model/issues/2668
- [x] **Meeting Material 30th April 2024**  
[ISDA Common Domain Model - Collateral WG 30th April 2024.pdf](https://github.com/finos/common-domain-model/files/15147255/ISDA.Common.Domain.Model.-.Collateral.WG.30th.April.2024.pdf)
- [x] **AGENDA 1**  - CDM Collateral - Get started guide Update
- [x] **AGENDA 2** - CDM Eligible Collateral Extensions Update
- [x] **AGENDA 3**  - CDM contribution of the CSA Legacy structure in ‘ISDA Foundations’
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes- @eteridvalishvili 

**Collateral Get Started Guide for CDM** 
- @Oblongs  provided an overview of the development progress of the Get Started Guide for CDM.
  - Need for a comprehensive guide to address feedback on the complexity of the CDM and the challenges in getting started with it.
  - Discussed the structure and content of the guide, including modules A to E, with a focus on making it accessible and engaging for both non-technologists and technologists.
  - Screenshots of the prototype were shared, and key features such as navigation, tooling, and knowledge checks were highlighted.
  - Will be available on the ISDA website and linked through the [CDM Website](cdm.finos.org)

**Proposed Additions to the CDM**
- @valdensmith presented proposed additions to the CDM, including margin type and rating priority resolution, based on previous discussions and member feedback.
  - Reviewed and provided feedback on the proposed additions, including their relevance and potential impact on the CDM structure.
  - Proceeding with the contributions of margin type and rating priority resolution to the CDM.

**Update on Contributions**
- @valdensmith  provided an update on recent contributions to ISDA Foundations. Related to the extension of the CDM for legacy VM CSAs.
  - Completion and contribution of various clauses to ISDA and outlined the ongoing work to cover additional clauses by June or July.
  - Attendees are encouraged to join the ISDA CDM Legal Agreement working group and contribute to the completion of the agreement.

## Action Items

- [ ] **ACTION 1** With reference to agenda item No1 ‘Get Started with CDM for Collateral’, detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) paged 3- 13. We would encourage members provide any feedback, please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org). ISDA will continue to finalize development and launch of the Get Started Guide for Collateral Data Model.
- [ ] **ACTION 2** In relation to agenda 2 ‘Margin Type’ detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 15. As agreed during this working group meeting, ISDA will proceed with this contribution, and share with members once completed. 
- [ ] **ACTION 3** In relation to agenda 2 ‘Rating Model’ detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 16. Members were not against the proposal to extend the CDM to enable the user to prioritize between Asset and Issuer ratings. ISDA will proceed with a CDM model extension and advise the working group once completed. 
- [ ] **ACTION 4** Continue working on extension of VM CSA contributions in ISDA Foundations and aim for completion by June or July.
- [ ] **ACTION 5** Eligible Collateral - Other items for further discussion in future working groups The following items have been listed for future working group discussion: 
•	Exclusions within criteria 
•	ConcentrationLimit is part of Treatment, how they can be combined to address specific use cases
•	A means for specifying ‘contract/ transaction type’ such as (Repo, Loans, UMR) to apply to eligible terms as well as margin type

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09

Meeting ID: 960 8428 4579
Passcode: 477790
Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by valdensmith** [comment]
Vernon ISDA

**Comment by adamulman** [comment]
Adam Ulman SmartStream

**Comment by sf-lseg** [comment]
Sean Funke. Acadia/LSEG

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by GerryDenham** [comment]
Gerry Denham / Eurex

**Comment by dharm-kapadia** [comment]
Dharm Kapadia / EquiLend

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by CrisSearle** [comment]
Cris Searle / Clearstream

**Comment by KHVermeg8686** [comment]
Khaled Hassani/ Vermeg

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
