### ISSUE TITLE
Total Return Swaps with a debt underlier need to report 'CRDT' on AssetClass field

### ISSUE THREAD

**Issue by rogerguitart** [finos/common-domain-model#2854]
# Background

Following discussions with member firms and reviewing the ESMA Guidelines, it has been raised that total return swaps with a debt instrument as their underlier (bond, loan, etc) must report field 2.11 - Asset Class as 'CRDT', while total return swaps on an equity index or a basket of equities should report Asset Class as 'EQUI'. 

# Proposal

Currently, logic in the CDM and DRR is reporting the AssetClass field for TRS's on equities correctly, but is not considering the case of TRS's on a bond or a loan. To fix this, the `Qualify_AssetClass_Credit` function in CDM should be ammended to consider TRS's (an `interestRatePayout` together with a `performancePayout`) that have a `loan` or a `debt` instrument as their underlier:

![image](https://github.com/finos/common-domain-model/assets/141412602/7408783e-9663-45a7-843f-c089e59f9aa7)

Below the fragment in the ESMA Guidelines where this is specified:

![image](https://github.com/finos/common-domain-model/assets/141412602/9b479fd7-adc3-4e08-a734-152e6235f24f)

**Comment by eteridvalishvili** [comment]
Hi @rogerguitart It looks like the pull requests related to this issue have been merged. Can we close this issue as well?
