### ISSUE TITLE
FX Non Deliverable Swaps are not supported in qualification

### ISSUE THREAD

**Issue by manucarreramoreno** [finos/common-domain-model#2868]
# Background

FX swaps are currently supported in CDM, but only the ones that trade deliverable currencies (meaning that the delivery type of the swap is Physical). Some currencies are not deliverable, hence the swaps are cash settled: the non-deliverable swaps.

# Proposal

To add the following QF:

`func Qualify_ForeignExchange_NDS: <"Qualifies a product as Foreign Exchange NDS based on economic terms, which is defined as a contract in which one party borrows one currency from, and simultaneously lends another to, the second party. Each party uses the repayment obligation to its counterparty as collateral and the amount of repayment is fixed at the FX forward rate as of the start of the contract.">`
    `[qualification Product]`
    `inputs:`
        `economicTerms EconomicTerms (1..1)`
    `output:`
        `is_product boolean (1..1)`
    `set is_product:`
        `Qualify_AssetClass_ForeignExchange(economicTerms) = True`
            `and economicTerms -> payout -> forwardPayout -> underlier -> foreignExchange only exists`
            `and economicTerms -> payout -> forwardPayout -> underlier -> foreignExchange count = 2`
            `and economicTerms -> payout -> forwardPayout -> settlementTerms -> cashSettlementTerms exists`

**Comment by manucarreramoreno** [comment]
PROD PR: https://github.com/finos/common-domain-model/pull/2867
DEV PR: https://github.com/finos/common-domain-model/pull/2866

**Comment by eteridvalishvili** [comment]
Hi @manucarreramoreno It seems that all the pull requests related to this issue have been closed. Can we close this issue as well?

**Comment by manucarreramoreno** [comment]
Hi @eteridvalishvili, yes we can close this issue.
