### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - May 8th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2897]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

May 8th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/2829
- [x] https://github.com/finos/common-domain-model/issues/2913
- [ ] https://github.com/finos/common-domain-model/pull/2914
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

Discussions
-	Some agenda items were deferred to the next meeting when JB can attend
o	FRAGMOS – remove condition "PrincipalAmount" that forces PrincipalAmount to exist inside PrincipalPayment #2163
o	fixedPricePayout – continuation of discussion on usage (JBZ Fragmos) [see comments from email to DPBE dist ]
o	commodityPayout – does “delivery” need refactoring (JBZ Fragmos) [see comments from email to DPBE dist ]

-	Proposed modification of AmericanExercise condition under ExerciseTerms #2913 (Roger Guitart TH)
o	AmericanExercise condition update #2914
	The proposal was approved for implementation
	Discussions:
•	Background: A refactoring of the optionPayout that was done some time ago.
o	As part of changing the model to be more generic expirationDate now can appear multiple times for things like Bermuda options. it was noticed that the condition for the American exercise was not restrictive enough because it allows multiple expiration dates. So for American exercise, it makes sense to add this condition and only have one expiration date as we would expect for American options.
•	Harry thought that we had discrete models for each European, Bermudan and American exercise style. He always thoughts the changes to the exerciseTerms was a mistake that’s why he opposed it originally. The refactoring opened the door to issues like the one we’re discussing.
o	You could argue that every day and the term of an American exercise period is an expiration date. It's a calculation of daily expirations. That’s not we need here. 
	The way that we understand it is the expiration date means the final expiration date of the American exercise period. So you have the opportunity for continuous exercise period from the commencement date through to the expiration date. 
o	That means something different from expiration date under European exercise or expiration date under Bermudan exercise, where you have multiple opportunities at intervals to do the exercise. The only situation under which you get multiple expiration dates, though the only meaningful one will be Bermuda exercise where you have opportunities to exercise at intervals, e.g. yearly intervals.
o	With the refactoring done and as it is, we do need the proposed modification of the condition provided we understand expiration date as meaning the final expirationDate in the context of an American.

-	AOB - None

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by manucarreramoreno** [comment]
Manuel Carrera / TradeHeader

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by HajnalOB** [comment]
Hajnal /Regnosys

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
