### ISSUE TITLE
CDM Technology Architecture WG - May 9th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2899]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
May 9th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2819
- [x] TAWG Vision Statement - [TAWG Vision Statement.pptx](https://github.com/finos/common-domain-model/files/15251414/TAWG.Vision.Statement.pptx)
   - [x] #2858 
   - [x] #2859 
- [x] AOB, Q&A & Adjourn (5mins)
   - [x] Deprecate unused Code Generators

## Action Items
- [x] Update the TAWG Vision Statement deck and attach to the Issue - @chrisisla
   - [x] [TAWG Vision Statement.pptx](https://github.com/finos/common-domain-model/files/15264340/TAWG.Vision.Statement.pptx)
- [x] Close discussions on Vision Statement and Adoption - @chrisisla
- [x] Create new discussion to derive applicable technology changes and their definitions - @chrisisla
- [x] Broadcast status and new discussion number to TAWG mailing list - @chrisisla
- [x] Propose the deprecation of code generators at the next SWG - @chrisisla

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by dschwartznyc** [comment]
Daniel Schwartz/FT Advisory

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by mikealambert** [comment]
Mike Lambert / Broadridge

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
