### ISSUE TITLE
CDM Steering Working Group - May 14th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2903]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
May 14th, 2024  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2821
  - [x] Action check: roadmap updates submitted for inclusion on website  https://github.com/finos/common-domain-model/blob/master/ROADMAP.md
- [x] Release governance update- summary of outcomes @tomhealey-icma 
- [x] ART Progress update @Oblongs 
[ARTForce 14May24 for SteerWG.pptx](https://github.com/finos/common-domain-model/files/15308599/ARTForce.14May24.for.SteerWG.pptx)
- [x] From the TAWG - Deprecation of unused Code Generators - @chrisisla 
- [ ] AOB

## Minutes

- Meeting admin completed, previous minutes ratified
- Reminder to all chairs to continue to submit roadmap updates to Eteri

Release governance update
- @tomhealey-icma gave an update. Summary of the 5 discussion topics has been circulated. There has been some further commentary but Tom is looking to close out comments in next week. Tom is beginning to implement a solution for creating a draft PR

ART update
- @oblongs gave an update as per the material attached. It was highlighted that scope is beginning to creep and this Thursday's session would be used to re-baseline and confirm out of scope items. Additionally, @JBZ-Fragmos requested a mark to market vs the initial objectives of the group. @dshoneisda requested a catch up with @oblongs prior to meeting as sponsor of the work, since he was not able to make the Thursday session

Code generator deprecation
- @chrisisla explained that as part of the TAWG's work to move from CodeFresh to Github Actions, it had been noted that many of the existing code generators may not be being maintained, and the automated tests should focus on those that are. As such proposal is to survey community members, pointing them at an issue describing what is happening and checking with community members whether they use the generators. action: @chrisisla 
- @lolabeis suggested that maintainers also volunteer to back code generators of importance
- @dshoneisda pointed out that members of the SWG should pass on the survey to those members of TAs or other users of CDM who may not yet have subscribed to the cdm lists.

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by dshoneisda** [comment]
david shone /isda

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by mikealambert** [comment]
Mike Lambert / Broadridge

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by DIVA291265** [comment]
Daniel Ivanier / Fragmos Chain

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by ftadvisory** [comment]
Dan Schwartz/FT Advisory
