### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - May 22nd, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2905]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

May 22nd, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/2897
- [x] FRAGMOS - minor fix for portfolio swap https://github.com/finos/common-domain-model/pull/2910 @JBZ-Fragmos 
- [x] FRAGMOS – remove condition "PrincipalAmount" that forces PrincipalAmount to exist inside PrincipalPayment https://github.com/finos/common-domain-model/issues/2163 PR: https://github.com/finos/common-domain-model/pull/2930 @lolabeis 
- [ ] fixedPricePayout- continuation of discussion on usage [see comments from email to DPBE dist pasted in first meeting comment below] @JBZ-Fragmos
- [ ] commodityPayout- does "delivery" need refactoring? [see comments from email to DPBE dist pasted in first meeting comment below] @JBZ-Fragmos
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

- Meeting admin successfully completed. No changes to previous minutes
- Fix for portfolio swap.
   - @lolabeis summarised feedback (see the PR). For proposals 1 & 3 it was agreed that these could be submitted (@JBZ-Fragmos to re-submit without change 2). For item 2 there is an investigation into the DSL, and it will be fixed at that level.
- Principal Amount. This has been reviewed by @lolabeis- see PR for detail. Reset attribute was removed and PR submitted- will be approved
- fixedPricepayout- this item will be resolved within the Asset Refactoring Taskforce
- commodityPayout- @JBZ-Fragmos went through his points (see comments and pictures below). The reason behind these modelling decisions was elaborated upon by a commodities SME.
  - For point one on schedules @JBZ-Fragmos will take away and consider whether there is indeed an improvement possible once discontinuous schedules have been taken into account (effectively custom schedules are why the model is currently the way it is
  - For points 2 & 3 no further action is to be taken. SME explained that for regulatory reporting reasons, in which equivalent delivery periods must be reported even for finanially settled transactions, as well as reporting some physical commodity attributes at the derivative contract level, has resulted in the model being the way it is. It was agreed that rather than risk breaking something that currently works, no further action to be taken at this point

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by HajnalOB** [comment]
Hajnal/Regnosys

**Comment by manucarreramoreno** [comment]
Manuel Carrera / TradeHeader

**Comment by jonathan-jpmc** [comment]
jonathan/jpmc

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by eelramy** [comment]
Elias El-Ramy / Société Générale

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by dshoneisda** [comment]
![image](https://github.com/finos/common-domain-model/assets/139778661/500c263f-72fb-4959-b51d-6a64929b68c3)

**Comment by JBZ-Fragmos** [comment]
JB Ziade - FRAGMOS
