### ISSUE TITLE
CDM Collateral Working Group - June 25th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2907]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

June 25th, 2024 - 10 am EST / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve Past Meeting Minutes
   - [x] https://github.com/finos/common-domain-model/issues/2826
- [ ] **Meeting Material 25th June2024**
**[ISDA Common Domain Model - Collateral WG 25th June 2024.pdf](https://github.com/user-attachments/files/15930068/ISDA.Common.Domain.Model.-.Collateral.WG.25th.June.2024.pdf)**
- [ ] AGENDA 1 - CDM Collateral - Get started guide go live 
- [ ] AGENDA 2 - 2.	CDM Eligible Collateral extensions contributions 
•	Margin Type
•	Agency Rating priority resolution
- [ ] AGENDA 3 - Specifying ‘contract/ transaction type’ such as (Repo, Loans, UMR) to apply to eligible collateral terms
- [ ] AGENDA 4 - CDM Asset refactoring overview and relationship with eligible collateral model  
- [ ] AGENDA 5 -  Update on CSA Legacy structure in ‘ISDA Foundations’
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes- @eteridvalishvili 
- [ ] @Oblongs and @valdensmith presented the agenda items in the meeting material slides (ISDA Common Domain Model- Collateral WG) outlined in the agenda. Actions from the meeting are highlighted in the action items section.

## Action Items
- [x] **ACTION 1**  
Get Started with CDM for Collateral 
With reference to agenda item No1 ‘Get Started with CDM for Collateral’, detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) paged 3-13. This can be found using the following link https://www.isda.org/2023/02/16/isda-collateral-initiatives/ We would encourage members provide any feedback, please please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [x] **ACTION 2**  
Eligible Collateral – contract transaction type 
A means for specifying ‘contract/ transaction type’ such as (Repo, Loans, UMR) to apply to eligible terms as well as margin type, detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 16. 
No further action will be taken on this addition at this point, as members do not appear to support. If you wish to provide additional feedback, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [x] **ACTION 3**  
Asset Refactoring
If members of the working group have any further questions related to the CDM Asset refactoring as detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) page 17-18. Please contact [lionel.smith-gordon@regnosys.com](mailto:lionel.smith-gordon@regnosys.com) AND [valdensmith@isda.org](mailto:valdensmith@isda.org).
- [x] **ACTION 4** 
ISDA will continue working on extension of 1994/95 CSA clause contributions to ISDA Foundations outlined on slide 19 and aim to complete this by end of August 2024. 

### Zoom info

Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09
Meeting ID: 960 8428 4579
Passcode: 477790

Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by valdensmith** [comment]
Vernon ISDA

**Comment by GerryDenham** [comment]
Gerry Denham

**Comment by sf-lseg** [comment]
Sean Funke, Acadia/LSEG

**Comment by acrangle-murex** [comment]
Aidan Crangle, Murex Advanced Technologies

**Comment by fldemarche** [comment]
Florent Demarche, Murex

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by murphnOSTTRA** [comment]
Neil Murphy / OSTTRA

**Comment by adamulman** [comment]
Adam Ulman / SmartStream
