### ISSUE TITLE
CDM Steering Working Group - June 11th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2953]
# CDM Steering Working Group Minutes 
Meeting Host: Tom Healey, ICMA

## Date
June 11th, 2024  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2903
- [x] ART Progress update @Oblongs
   - [ARTForce Steering 10Jun24.pptx](https://github.com/user-attachments/files/15788376/ARTForce.Steering.10Jun24.pptx)
- [x] Release governance update- summary of outcomes @tomhealey-icma
- [x] Release- roadmap alignment @dshoneisda @brianlynn2 
- [x] AOB

## Minutes
- No feedback on proposal to deprecate any code generators.
- Update on ART. Planned release into v6.0 in July. 
- Release governance final proposal issue. Final decision to accept/reject by next SWG. See proposals here, 
[Final governance proposal.docx](https://github.com/user-attachments/files/15793394/Final.governance.proposal.docx)
[PR Category Classifications2.pptx](https://github.com/user-attachments/files/15793396/PR.Category.Classifications2.pptx)
- Update from Brian on ISDA roadmap.
- Tom requested members to provide a policy statement on what should be included in the CDM re: client specific test cases,   client specific FpML files, examples,etc). See discussion, [2979](https://github.com/finos/common-domain-model/discussions/2979)

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by eelramy** [comment]
Elias El Ramy / Société Générale

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / for REGnosys

**Comment by ADaleISLA** [comment]
Adrian Dale/ISLA

**Comment by bohuang19** [comment]
Bo Huang / Bloomberg

**Comment by jonathan-jpmc** [comment]
jonathan/jpmc

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by LathaamWilson** [comment]
Lathaam / JPMC

**Comment by eacunaISDA** [comment]
Eleonora / ISDA
