### ISSUE TITLE
CDM Steering Working Group - July 9th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3024]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
July 9th, 2024  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2953
- [x] Release schedule and guidelines @brianlynn2 
[CDM Release Guidelines Task Force Summary - July 8 2024 .pptx](https://github.com/user-attachments/files/16144653/CDM.Release.Guidelines.Task.Force.Summary.-.July.8.2024.pptx)
20 min]
- [x] PR approval process update @tomhealey-icma [10 min]
- [x] Asset Refactoring Taskforce update @Oblongs [10 min]
[ARTForce SteerWG 9Jul24 (1).pptx](https://github.com/user-attachments/files/16143561/ARTForce.SteerWG.9Jul24.1.pptx)
- [x] Prioritisation of future items- community involvement - discussion @dshoneisda [10 min]
- [x] AOB

## Minutes

- Meeting admin completed
- Past minutes were approved. It was noted that the discussion #2979 had had no commentary. @tomhealey-icma to make some initial suggestions in the discussion so the group can assess what they are being asked for and input to the discussion. Verbally, the thought was that items such as tests for specific firms, and certain mappings, product/function stubs, no longer needed to be part of the core CDM. @gabriel-ICMA has a draft proposal, which can be added to the discussion

**Releases**
- @brianlynn2 ran through the summary deck covering release management and scheduling proposals. This was generally well received by the group. Follow up actions are:
   - @brianlynn2 to complete transferring the detailed governance to governance.md and release.md
   - @brianlynn2 to ask @eteridvalishvili to update the website accordingly, including the summary deck for ease
   - @brianlynn2 to invite @tomhealey-icma to the next release discussion (Friday 12th Jul) to bottom out PR review proposals where there remains conflicting proposals/details to be ironed out
   - @eteridvalishvili to edit recording of this proposal and include on website and circulate for CDM community (this was agreed on the maintainers slack channel after the meeting at the proposal of @jgavronsky 
- @tomhealey-icma deferred any further update until the meeting above as most of his material was covered by @brianlynn2 

**Asset Refactoring**
- @Oblongs provided the update per the powerpoint slide, focusing heavily on the timelines set out in slide 5. 
- Primary change requested by group was to bring forward the communication period to the community by 2 weeks into mid July.
- It was agreed that the formal release announcement would be made (a reminder in reality) to the CRWG on 23rd July.
- @lolabeis agreed to produce the formal release note for CDM 6.0 (similar to those made for CDM 5.0) detailing the major changes included
- It was noted by @tomhealey-icma that he had further commentary to address wrt. repos and the refactoring [this conversation has continued over email]

**Prioritisation of future work**
- @dshoneisda noted that budget season was fast approaching, if not already upon us. There are multiple possible items to fund across the SWG, domain WGs and the TAWG. @dshoneisda asked for ideas from the group as to how to go about getting feedback from community
- Agreed for SWG/maintainers to provide issues/core items then a "Poll" discussion can be created to attract votes. 
- It was noted that ultimately the associations funding items would have to make the decision on which items were funded and when, but it gives an insight as to what the community really feel is required from the model

**AOB**
- @jgavronsky reminded the group that the call for papers for the OSFF NY closes on July 14th.
- @jgavronsky also suggested that the prioritization of work discussion could occur as a session at the OSFF, to collate use cases

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS
