### ISSUE TITLE
CDM Technology Architecture WG - July 11th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3025]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
July 11th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/2954
- [x] Updates (15 mins)
   - [x] TAWG Maintainers update - @chrisisla 
   - [x] Deprecation of Code Generators - @chrisisla
   - [x] Github Actions - @dschwartznyc 
   - [x] Choice operator - @chrisisla
   - [x] Rune projects - @minesh-s-patel 
- [x] Review recent Technical changes contributed to the CDM (10 mins)
- [x] Change Control Guidelines for Rune & CDM (25 mins)
   - [x] Aim: To discuss categories of changes, for example
     - non-breaking changes - where a Rune change does not impact CDM at all
     - breaking - where a Rune change breaks something that works now
     - compatibility issues - where a Rune change need changes to generated libraries
     - new features - where new features are introduced into a Rune version
     - (category names in this list are open to discussion)
   - [ ] Goal for today's meeting
     - define draft of non-breaking changes category
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points

- _Updates_
   - Code Generators
      - Code generators will have first lines of support assigned to them
      - Dan pointed out that help will be expected from the community too
      - Need the community to assist otherwise generators may not stay current
      - TAWG should also provide documentation on how to support code generators
   - Github Actions
      - Initiative has been parked until people are able to commit time to it
	  - There are some outstanding technical issues
	  - The latest update will be added to #2623
	  - Minesh confirmed all changes can be committed to his repo (link is in #2623)
   - Rune Projects
      - Minesh confirmed there are 3 Rune projects under FINOS at the moment
	     - Rune DSL
		 - Rune Testing
		 - Rune Common
	  - Rune Code Generators will be contributed too
	  - Rune Serialisation is also being incubated at FINOS

- _Change Control Guidelines for Rune and CDM_
   - Brian suggested we should look at the Rune changes from two angles:
      - Syntax changes - these could be backward compatible or incompatible
	  - New Features
   - Also need to consider where Rune change means a Java library is modified and causes issues down the line
   - Should also think about what could possibly go wrong due to a Rune change
   - Dan asked what the process is for the CDM to request changes to Rune
   - Minesh confirmed this can be done by raising an Issue on the Rune repo
   - Minesh also suggested that we talk to users who have been using the CDM and may have encountered issues due to Rune changes
   - An initial list of users was proposed which Chris will follow up with Minesh on

## Action Items

_Action Points_
- [x] Update the Code Generators discussion with final results - @chrisisla 
- [x] Email discussion link to all CDM groups again for final notice - @chrisisla 
- [x] Github Actions Issue #2623 to be updated with current status - @dschwartznyc 
- [x] Ask users of CDM what issues they have encountered due to changes in Rune - @chrisisla 
   - [x] Create a discussion and broadcast to CDM lists: #3046

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by fgignoux** [comment]
Frederic GIGNOUX / SG

**Comment by dschwartznyc** [comment]
dan schwartz/FT Advisory

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader
