### ISSUE TITLE
CDM Collateral Working Group - July 30th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3030]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

July 30th, 2024 - 10 am EST / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
   - [x] https://github.com/finos/common-domain-model/issues/2907
- [x] **Meeting Material**
**[ISDA Common Domain Model - Collateral WG 30th July 2024.pdf](https://github.com/user-attachments/files/16424643/ISDA.Common.Domain.Model.-.Collateral.WG.30th.July.2024.pdf)**
- [x] **AGENDA 1** - CDM Collateral IM CSA use case in production overview – Vermeg
- [x] **AGENDA 2** - ISLA - Outcome from CDM priorities survey – Collateral priorities 
- [x] **AGENDA 3** - ISLA- Eligible Collateral data sample and object builder 
- [x] **AGENDA 4** - Collateral Substitutions workflows discussion – manual substitutions and operational burden, potential for CDM benefits 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes- @eteridvalishvili 

* Vermeg gave an update on the CDM collateral, discussing the CDM connector used to ingest different types of data and the progress made on eligibility collateral schedules.
* Chris Rayner from ISLA went over the results of a CDM survey that ISLA ran and identified collateral priorities, highlighting the focus on collateral and legal agreements.
* The group discussed collateral substitution workflows, identifying pain points such as identifying when a substitution is needed, the communication and validation process, and the custodian aspect.
* Acadia mentioned their substitution workflow and the need for a message definition to communicate substitutions between parties.
* Tom Healey from ICMA discussed a parallel scenario to collateral substitutions on the repo side, mentioning a model they implemented using the Cdm.
* The group agreed to continue the discussion on collateral substitutions at the next meeting, potentially with a presentation from Tom on the ICMA model.

## Actions-
- [x] **Action 1**
ISLA – Priorities survey and eligible collateral data 
With reference to agenda item No 2 & 3, detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) paged 5-8. If you have any questions related to the ISLA CDM survey and outcomes, or would like to provide eligible collateral examples related to securities lending, please contact  [Chris.Rayner@islaemea.org](mailto:Chris.Rayner@islaemea.org) 
Please also find here the link to the CDM object builder discussed during the working group call https://cdm-object-builder.finos.org/
- [x]  **Action 2**
Collateral Substitutions workflow- follow ups
As detailed and discussed during the meeting on the meeting material slides (ISDA Common Domain Model- Collateral WG) page. Several points were raised in relation to challenges in the collateral substitutions workflow where CDM may be able to help, noted as follows: 
o	 Identity of substitution reason (inc regulators declaring ineligibility, or governments declaring sanctions)
o	agreement and communication steps
o	validation
o	margin call steps, issuance and response
o	custodian and settlement workflows
o	issues with settle vs release of collateral timing   
o	40 act seg account/ transparency to dealer
ICMA mentioned they have already looked at CDM for solving problems raised within the ERCC committee in relation to best practices for pair offs and repo substitutions. This includes steps like proposal, acceptance, agreement, transfer, cancel, issue involving SWIFT messaging. These business events and workflows have been built into a demo created within ICMA working groups but not contributed to CDM. ICMA agreed to share the substitution workflow at this working group in a future meeting.
One of the vendors present at the meeting mentioned that for their substitutions workflow service, if more of the market were to start adopting CDM standards for specific definitions they could map to CDM to improve workflows via API and STP, creating a better communication network.  
If you wish to provide additional feedback on the collateral substitution workflow, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org)

### Zoom info

Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09
Meeting ID: 960 8428 4579
Passcode: 477790

Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by valdensmith** [comment]
Vernon A-S ISDA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by adamulman** [comment]
Adam Ulman - SmartStream

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by dharm-kapadia** [comment]
Dharm Kapadia / EquiLend

**Comment by AmyCaruso** [comment]
Amy Caruso/ISDA

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by dshoneisda** [comment]
David Shone ISDA

**Comment by criss11fr** [comment]
Cris Searle / Clearstream

**Comment by KHVermeg8686** [comment]
Khaled Hassani/ Vermeg

**Comment by VRao85** [comment]
Vinit Rao/Nasdaq

**Comment by nourhamida** [comment]
Nour Hamida/ Vermeg

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by wlo15** [comment]
William Lo/ MassMutual

**Comment by turntablistic** [comment]
Richard Barton/LSEG
