### ISSUE TITLE
PR 2214 changes have been reverted back to old model

### ISSUE THREAD

**Issue by tomhealey-icma** [finos/common-domain-model#3049]
PR 2214, https://github.com/finos/common-domain-model/pull/2214 was approved to:
- Add settlement party to settlement base, https://github.com/finos/common-domain-model/pull/2327; and
- Deprecated SettlementCenterEnum, https://github.com/finos/common-domain-model/issues/2213

The changes have reverted back to the original model in both prod 5.0 and dev 6.0 version.

Does anyone know why?

**Comment by lolabeis** [comment]
The motivation for the change is sound, but it was incorrectly implemented and needs be revised according to the comment that I left on the PR at the time:
https://github.com/finos/common-domain-model/pull/2214#issuecomment-1645776359

The change had to be reverted (in #2326) as it was merged prematurely and broke the CDM build. It didn't include any required doc change or release note so could not be released as is. Please see conversation on the CDM Maintainers channel (in Slack) from 21-Aug 2023.

I reopened the issue (#2213) shortly thereafter, but you then closed it again. I suggest keeping it open.
