### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - August 14th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3077]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

August 14th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3061
- [x] https://github.com/finos/common-domain-model/issues/3087  @winitall01 
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes

- Meeting admin was completed
- Past meeting minutes were approved
- @nicholas-moger walked the group through PR #3087 
    - Additions/amendments of conditions and qualifications (items on PR labelled 1,2,4,5) were approved by the group
    - Item 3 was agreed to be pulled from the PR. Whilst this is a change already made in 6.0, this would bring the change into 5.x  This was not approved at this meeting due to a need to update the relevant documentation for more clarity. @HajnalOB agreed to address with @winitall01 and this will be brought to the next DPBE WG
 
- There was no other business

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by HajnalOB** [comment]
Hajnal/Regnosys

**Comment by nicholas-moger** [comment]
Nick Moger/JPM
