### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - August 28th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3080]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

August 28th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3061
- [x] ObservationTerms & ValuationTerms: Issue
[FRAGMOS - ObservationTerms & ValuationTerms · Issue #3058 · finos/common-domain-model · GitHub](https://url.usb.m.mimecastprotect.com/s/7wQ6CzqwR7SXy81Of4fMu9fuep?domain=github.com) Draft PR
[JEAN BAPTISTE ZIADE ObservationTermsValuationTerms_DRAFT by regnosys-prod-user · Pull Request #3051 · finos/common-domain-model (github.com)](https://url.usb.m.mimecastprotect.com/s/IFsjCA8YwMIxPrQGC8hJuGYWty?domain=github.com) 
- [x] Re-visit of item from 31st July- any further feedback on: Standardized Schedule calculations for Initial Margin: https://github.com/finos/common-domain-model/issues/3060 TradeHeader
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- JB (Fragmos) presented issue #3058 in detail. It proposes the refactoring of ObservationTerms & ValuationTerms
  - DPBE WG members have an action to review offline and provide feedback. This is work in progress requiring input from everyone.
  - Additional refactoring - ObservationSchedule
    - feedback:
      - [Caroline BNPP] in commodity, fixing date are a series of observation dates. the concepts are very similar. there is potential to refactor further. 
      - JB clarified the difference between observation and valuation date
      - need a holiday calendar commonly used under commodities (Harry clarified this is different than specifying business centers, more relevant to rates asset class). 
      - numberOfObservationDates (optional) - in commodities, would be using a Platt's calendar (as opposed to a number of observations) to work out which dates are observation dates for that month vs weekends, bank holidays
      - [Harry BNPP] in the commodities asset class, the transaction may very well cite a calendar, but it will depend on what's possible for the class of observable itself. So the observable has some properties, the reference data, which determine what dates are, what dates are possible then to take in the contract. often it's an interaction between the properties of the observable, which, for us here are kind of reference data and the specific terms of the of the transaction.
      - [Leo Regnosys] [all the comments from Caroline on commodities apply to other asset classes] this merits some analysis for another type of payout, interest rate payout, to see whether we can fit into what we don't want to have. Is if we just add this payout base, then interest rate payout will have both its existing structure and the new one. And that's not something we want. So if we can feed the existing of interest rate, for instance, in observation term calculation dates, which is already an interest rate that would imply moving things.
         - JB proposed begining this kind of an assessment paired by payout. for instance, if we would have this kind of a payout base, what would be the impact, let's say, on e.g.  interest rate payout and commodity payouts
      - another point that was raised in the previous meeting observable. We need to carefully consider this one. CDM is currently ongoing asset refactoring. Because what we don't want like this looks like the underlier, and this looks like this is sometimes defined elsewhere in the payout, and we don't want to have two paths to define it. There's going to be a question whether this should sit in observation term or out, and everybody has it, or whether it should sit alongside it.
      - Leo raised attention to the inclusion of the observed price where JB positions them in the observation terms proposal
        - the concern with this approach is that every time you have a new observation, you effectively have to create a new instance of the product. And that's exactly what we wanted to avoid with CDM. We may need to find a different mechanism. It's a referencing issue.
        - We want to follow the principle that we don't want to correct a different product instance, whenever there is an observation. This should not cause new trade instance.
          - JB answered that precisely some metadata reference were attached in proposal, exactly to align with such principle
          - (the point of attention raised by Leo was answered because JB's proposal is precisely taking into account such requirement, (so there was no disagreement in conclusion, more a need to further assess how that would work at target)”
   - Additional refactoring - ObservationDates
     - discussed observationDates > parametricDates
     - observationDate RelativeDateOffset using DateRelaviveToEnum (new Enum)
   - The direction was quite appreciated overall on principle, provided gap analysis is performed notably with commodityPayout and interestRatePayout in order to further assess potential impacts, notably take into account remarks about observable/underlier potential overlaps.

- --
- Implementation of the Standardized Schedule Method for Initial Margin Calculation in CDM #3060 
   - was deferred to the next meeting as Marc Gratacos (Tradeheader) couldn't attend.
- AOB - None

## Action Items
- DPBE WG members have an action to review offline and provide feedback. This is work in progress requiring input from everyone.

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by JBZ-Fragmos** [comment]
JB Ziadé / FRAGMOS

**Comment by Oblongs** [comment]
Lionel Smith-Gordon

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St. Kliment Ohridski

**Comment by tabi5h** [comment]
Tabish Ahmed / ISDA

**Comment by HajnalOB** [comment]
Hajnal/REGnosys

**Comment by JBZ-Fragmos** [comment]
@lolabeis and **BNP participants** (Harry and Caroline) who provided most feedback during discussion about ObservationTerms and ValuationTerms,

kindly see last "Comment" in related Issue where i have made, as agreed, the **"gap analysis"** for commodityPayout and for interestRatePayout
https://github.com/finos/common-domain-model/issues/3058

have also updated PR accordingly 
https://github.com/finos/common-domain-model/pull/3051

same directly in Open Contrinbution in Rosetta GUI
![image](https://github.com/user-attachments/assets/fe10ac2e-586b-4219-b593-97a2824ebb7f)

thanks in advance for your feedbacks
