### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - September 11th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3118]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

September 11th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3080
- [x] Carry forward: Implementation of the Standardized Schedule Method for Initial Margin Calculation in CDM #3060 TradeHeader
- [x] Notice of change of chair going forward @dshoneisda  (2min)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

- meeting admin was completed
- previous minutes were accepted; only discrete follow up was carried as the item on the agenda for this meeting
- @mgratacos gave a re-cap summary of the item #3060 .  He noted that feedback received in prior meeting was being incorporated into an additional PR to enhance the PR already associated with this issue:
1) Error validation will be added
2) Naming conventions corrected
It was also noted that the proposal would remain as a separate namespace for now, but could be embedded with others when more mature/users have had a chance to use this functionality. Additionally it was clarified that the proposal remains generic and not specific to any particular jurisdiction

One attendee asked if this method was mandatory if using CDM; the answer was no, it is optional and available to use as a user sees fit
Same attendee asked about incorporation of FX rates into the calculation. The Standardized Schedule Method assumes single currency, thus FX conversion is assumed to be carried out prior to use of this model

With no further concern or feedback contribution was approved

- @dshoneisda announced that @llynhiavu will take on chairing this WG going forward
- there was no other business raised

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by dshoneisda** [comment]
dshone/isda

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by HajnalOB** [comment]
Hajnal/REGnosys

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
