### ISSUE TITLE
CDM Collateral Working Group - September 18th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3121]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

September 18th, 2024 - 10 am EST / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
   - [x] https://github.com/finos/common-domain-model/issues/3030
- [ ] **September 18th 2024 Meeting Material** 
**[ISDA Common Domain Model - Collateral WG 18th September 2024.pdf](https://github.com/user-attachments/files/17029226/ISDA.Common.Domain.Model.-.Collateral.WG.18th.September.2024.pdf)**
- [ ] **AGENDA 1** ISLA Eligible Collateral data samples update
- [ ] **AGENDA 2**  CDM Collateral VM CSA use case in production overview – DRS/Ark51 
- [ ] **AGENDA 3** ICMA Repo Substitutions business events and workflows demo
- [ ] AOB, Q&A & Adjourn (5mins)

## Short Meeting Summary & Actions-
- [x] Action 1 
ISLA –Eligible Collateral data samples update
With reference to agenda item No 1 detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) paged 3-4. Following the ISLA CDM survey and outcomes, where collateral use cases scored high, Chris Rayner provided an overview on eligible collateral examples related to securities lending which have been reviewed in the ISLA working groups. This included the model gaps identified during this analysis, which will be considered to be added to the CDM model. Please contact  [Chris.Rayner@islaemea.org](mailto:Chris.Rayner@islaemea.org) for any further information. 
Please also find here the link to the CDM object builder which was used to builder the schedule examples. https://cdm-object-builder.finos.org/
- [x] Action 2
CDM Collateral VM CSA use case in production overview – DRS/Ark51
Paul Hands (Parallel 51) firstly introduced DRS- ARK51 with the meeting material slides (ISDA Common Domain Model- Collateral WG) page 5 -6. Following this a live demo showed the working group how the platform uses AI to transform soft copy document information to CDM data JSON output. For more information please contact [paul.hands@parallel-51.com](https://github.com/finos/common-domain-model/issues/paul.hands@parallel-51.com)
- [x] Action 3
ICMA - Repo Substitutions business events and workflows demo
During the working group meeting 30th July ICMA mentioned they have already looked at CDM for solving problems raised within the ERCC committee in relation to best practices for pair offs and repo substitutions. This includes steps like proposal, acceptance, agreement, transfer, cancel, issue involving SWIFT messaging. These business events and workflows have been built into a demo created within ICMA working groups but not contributed to CDM 
Tom Healy ICMA shared information related to the substitution workflow at this working group meeting. Details can be found in the following presentation:
[Collateral Mgmt Subtitutions for Collateral Working Group - Final.pdf](https://github.com/user-attachments/files/17129249/Collateral.Mgmt.Subtitutions.for.Collateral.Working.Group.-.Final.pdf)
Following this Tom provide a live demo of the workflows to the working groups members.
If you wish to provide additional feedback on the collateral substitution workflow, please contact [valdensmith@isda.org](mailto:valdensmith@isda.org) , [Tom.Healey@icmagroup.org](mailto:Tom.Healey@icmagroup.org) and mailto:Chris.Rayner@islaemea.org
### Zoom info

Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09
Meeting ID: 960 8428 4579
Passcode: 477790

Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by valdensmith** [comment]
Vernon A-S ISDA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by adamulman** [comment]
Adam Ulman / SmartStream

**Comment by paulhands** [comment]
Paul Hands / Parallel-51 / DRS

**Comment by acrangle-murex** [comment]
Aidan Crangle - Murex

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by AmyCaruso** [comment]
Amy Caruso/ISDA
