### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - September 25th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3122]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: Lyteck Lynhiavu, ISDA

September 25th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3118
- [x] FRA incomplete (?) mapping of calculationPeriodNumberOfDays into CDM interestRatePayout/cashFlowRepresentation/paymentCalculationPeriod (Lyteck for Axoni)
- [x] AI meets CDM (David Lee ISDA)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- FRA mapping (FpML to CDM) incomplete for calculationPeriodNumberOfDays interestRatePayout/cashFlowRepresentation/paymentCalculationPeriod (Lyteck for Axoni)
  - BNPP indicated there was no point coding this last field
  - However, if we wanted to complete the FRA, it can be part of the larger initiative on the roadmap "to complete the mapping of supported products"
  - A ticket would need to be raised to keep track of the issue, and prioritized
- The "AI Meets CDM" workshop (Luca Borella, David Lee, Manuel Martos) is a line-up of demos of generative AI applications for CDM.
  - Provectus showing a knowledge graph built for CDM
  - ISDA showing a framework for transforming legacy contracts into CDM format
  - TradeHeader showing a CDM summarizer that will interpret CDM for the user
  - Columbia University showing an LLM Chatbot using an open-source fine-tuned financial LLM
It will be showcased at the FINOS OSFF In New York, October 1.
- AOB
  - Dan Schwartz raised two questions:
    - CDM's support for life cycle events has limited documentation and seems to be incomplete. In particular, it is unclear how to represent an **Affirmation** (JB believe is is more of a status opposed to . Similarly Marc / Tradeheader added that **Allocation** may have some gaps.
    - In light of these gaps, Dan questioned whether a review of the event model (workflow) in CDM is warranted. CDM leverages a relatively complex collection of types and steps (e.g. Workflow, Workflow Step, EventInstruction, Business Event) and suggested exploring whether there may be opportunities to remove those barriers through simplification of the data and event modeling.
      - BNPP and Fragmos were not interested in initiating a review. The framework seems fit for purpose. Current focus is on products and DRR implementation. 

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by lucaborella89** [comment]
Luca Borella / FINOS

**Comment by JBZ-Fragmos** [comment]
jb Ziade / FRAGMOS

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory
