### ISSUE TITLE
Proposed change to the CDM for Equity Products

### ISSUE THREAD

**Issue by winitall01** [finos/common-domain-model#3163]
## Issue 1: Activity Date ##

_Problem Statement:_ Modelling of Activity Date in Create_TradeState Function is incomplete. Currently, activity date in empty in the function
![Screenshot 2024-10-07 at 09 30 50](https://github.com/user-attachments/assets/ebbe51c0-9613-40b4-930e-d021f72d5afc)

## Proposal ##
_Populate activity date with event Date_
![Screenshot 2024-10-07 at 09 32 53](https://github.com/user-attachments/assets/a67eee9c-a9bf-43a7-b9c9-745db28a0348)
This will also include making changes in all associated functions. Please refer to the following PR for full list of changes:

## Issue 2: FpML Conditions require modification## 
1. FpML_ird_9
2. FpML_ird_29

_Current State_
![Screenshot 2024-10-07 at 09 40 24](https://github.com/user-attachments/assets/af38f6da-af00-4e9d-a9a5-2039d377cf4f)

## Proposal ##
_Proposed State_
![Screenshot 2024-10-07 at 09 39 15](https://github.com/user-attachments/assets/a0fd88f0-176c-47ef-86d0-1c061f37dddb)

## Issue 3: Commodity Qualification function ##
_Modifications to Qualify_AssetClass_Commodity and Qualify_Commodity_Forward_
Addition of Single forwardPayoutLeg required
_Current State_
![Screenshot 2024-10-07 at 21 58 49](https://github.com/user-attachments/assets/f43202df-4a70-4c3c-b9ce-235ae5dec9db)

## Proposal ##
_Proposed State_
![Screenshot 2024-10-07 at 21 59 02](https://github.com/user-attachments/assets/2d387c4a-b801-4bc8-a9ae-cf863270302e)
![Screenshot 2024-10-09 at 15 55 22](https://github.com/user-attachments/assets/dbe92f45-9c21-4168-8722-b24c8fd0fa26)

## Issue 4: Equity Qualification function ##

_Modifications to Qualify_AssetClass_Equity_
Addition of AssetClass check for index underlier
_Current State_
![Screenshot 2024-10-07 at 22 01 12](https://github.com/user-attachments/assets/151e029c-4c34-4941-83e0-d2f3b65d7b49)

## Proposal ##
_Proposed State_
![Screenshot 2024-10-07 at 22 14 28](https://github.com/user-attachments/assets/1d4d4912-4079-4e3c-b244-9df07aba88c2)

## Issue 5: cardinality of expirationTime ##
Problem Statement: in type ExerciseTerms, expirationTime has a mandatory cardinality (1..1). For FX Options, there’s no fix expirationTime.
_Current State_
![Screenshot 2024-10-07 at 22 03 13](https://github.com/user-attachments/assets/4c1cb983-55e7-42a7-8980-272f2d40bd64)

## Proposal ##
_Proposal:_ relax expirationTime cardinality rule. Also, add a condition to require expirationTimeType when expirationTime exists or vice versa (to be added to AmericanExercise, BermudaExercise and EuropeanExercise)

_Propos
![Screenshot 2024-10-09 at 15 57 21](https://github.com/user-attachments/assets/1eb23854-1ead-490a-b4a8-f59cf72d7196)
ed State_

**Comment by manucarreramoreno** [comment]
On **Issue 3: Commodity Qualification function**, why is the addition of a "Price Return Vanilla Forward" required? The attribute _ForwardPayout_ does not allow the representation of a price, so we cannot determine at which price the commodity delivered is being payed (this is why we need to combine it with a _fixedPricePayout_ or a _commodityPayout_)
