### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - October 9th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3164]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: Lyteck Lynhiavu, ISDA

October 9th, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3122
- [x] Update on the Asset Refactoring Task Force (ART) (Lionel / Regnosys)
- [x] https://github.com/finos/common-domain-model/issues/3163 (Nicholas, Vineet)
- [x] https://github.com/finos/common-domain-model/pull/3157 (Tradeheader)
- [x] Event model / Workflow process
   - [x] https://github.com/finos/common-domain-model/issues/3170 (Dan Schwartz)
   - [x] https://github.com/finos/common-domain-model/discussions/3171 (Dan Schwartz)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Past minutes were approved. No objections.
- [x] Update on the Asset Refactoring Task Force (ART) led by Lionel / Regnosys
   - CDM 6.0.0-dev.72 is out an includes the work from the ART
   - Comprehensive release notes are available at https://github.com/finos/common-domain-model/releases 
   - **ACTION Firms have an action to review the asset refactoring and provide feedback**
   - The ETA for the final 6.x production version is about one / one and-a-half month. Feedback is critical to make sure the changes are fit for purpose.
   - Regnosys is working on compatibility/integration with DRR 6.x
   - Manuel raised a question regarding open pull requests for CDM 5: if any of these open or pending requests to be merged need updates. How will these get handled e.g. if there's anything that breaks with the new CDM 6 and you cannot integrate it, or maintainers don't know how to integrate it. what is the process? 
      - for open contributions that were made prior to the Regnosys refactoring, it is Regnosys' responsibility to update what you already contributed
      - for contributions that came after that latest release in Dev, their changes will need to be to be made compatible with the latest version
- [x] #3163 (Nicholas, Vineet)
   - no objections. approved. 
   - Issue 3: Commodity Qualification function may be impacted by the ART work. The proposal can be integrated in 5.x but will require a discussion between Nicholas/Vineet/Lionel to upgrade to 6.x
- [x] #3157 (Manuel / Tradeheader)
   - no objections. approved. 
- [x] Event model / Workflow process
   - There was general agreement that there are issues with the current modeling and implementation of life cycle events including those cited in the issue below and others raised in the meeting (captured herein):
   - [x] https://github.com/finos/common-domain-model/issues/3170 (Dan Schwartz)
      - Leo believes allocation, partial allocation should be covered by the existing model. 
      - Dan: perhaps the model works but the documentation needs to be improved?
      - Lionel: Affirmation and Confirmation have actually been removed in CDM 6.x Dev , as part of the ART, because they were incomplete. So Affirmation and Confirmation still need to be fleshed out. 
      - Other firms may have other issues that have not been raised yet
         - JPM mentioned enhancements around the cancelation of Workflow steps 
            - So at the moment, all of the cancelation of workflow steps are interpreted as error. But obviously, if you've got a new an increase, and you cancel the increase, you still have a live state. I don't know whether it's CDM or DRR, that needs to interpret that as an actual amendment on the overall trade, rather than a cancelation, but that's something we've run into. So if you have increase, and then you cancel the increase workflow step and restore your current state to be the state of the new that's still being interpreted as a cancelation overall. 
               - [In other words, if there is an increase in volume that is cancelled the result is that in addition to the increase the original trade is also marked as cancelled.]
            **- The group agreed creating a "laundry list" of concerns that firms may have around processes. We could then present to the Steerco.**  **ACTION Firms can add items to issue #3170** 
   - [x] https://github.com/finos/common-domain-model/discussions/3171 (Dan Schwartz)
      - There was interest from Dan, Tokenovate, JPMorgan to have a refresher/orientation session on the event / workflow framework to gain a better understanding. 
         - Stephen: is very important in terms of opening doors and maximizing the value of what CDM is and how it can help the industry. This is something Tokenovate is looking at. We're working on some of the workflow challenges today, so this is definitely something would merit a wider discussion.
      - At the previous meeting (Sept 25), we heard no interest from BNPP / Fragmos to open this.
      - Leo mentioned there has been training, decks and 1/2 - 1  day workshops on the topic, and that's probably the right length for a proper dive. In Regnosys' experience, an hour session is very short and doesn't deliver on what was expected. 
          - Lyteck: (my thought, after the meeting) I think most of us in this group have been exposed to the framework (workflow step, business event) through reading the documentation, listening through training sessions, or actually using the model etc... so we are not starting from scratch. a shorter session/recap/orientation would be sufficient as a start imho]
          - Leo noted there would be some substantial preparation work involved to maximize the effectiveness. The prep work will be important for the event to be successful, even if the training is short
      - TBD when such session would take place (ad-hoc or as part of an upcoming wg meeting?
- AOB
   - **JPMorgan "has there ever been any discussion around modeling units such as book portfolio desk in CDM?"**
      - At the moment, we've got party and business unit. Obviously, any given trade is between two parties, but it's also between two risk units or two books. The books could change without the parties being changed through transfers, etc, internally, and that can change the identifiers on the trade circuit, causing us some some issues. But if book and or risk unit was was modeled within CDM, that might be a way to counter for that. 
      - Leo mentioned it's been discussed but probably superficially. There is, a concept of count that you can attach to a party, which I think is an attempt at capturing those concepts. There as never really a use case for pushing it, but maybe now there is. Regnosys could help put together a proposal, and then submit it to the wider group.
      - Stephen / Tokenovate has had similar conversation about this. Nick and Stephen will connect off-line. 

## Actions
   - [ ] Asset Refactoring - All firms to review the asset refactoring work in CDM 6.0.0-dev.72 + release notes
   - [ ] Event Model - The group agreed to create and investigate a "laundry list" of potential issues with the current processes. If real issues are found, the DPBE WG would then present its findings to the SWG for guidance on resolution. Firms can add items to issue [Proposed change to the CDM - Completion Life Cycle Events Implementations #3170](https://github.com/finos/common-domain-model/issues/3170)
   - [ ] Organize an orientation session -led by Regnosys- to go over the CDM Event Model / Workflow (Lyteck will discuss to Leo offline)

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by HajnalOB** [comment]
Hajnal/REGnosys

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by sashworthTKN** [comment]
Stephen Ashworth / Tokenovate

**Comment by dschwartznyc** [comment]
dan schwartz/FT Advisory
