### ISSUE TITLE
CDM Technology Architecture WG - October 10th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3165]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
October 10th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/3119
- [x] Update on Serialisation design
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] CDM via pip

## Minutes &  Discussion points
- Chris gave an overview of the current state of the Serialisation design process
- Dan explained how the Python version of the CDM will soon be available through pip
- This will provide access to the Production versions of the CDM
- This has been a joint effort between FTAdvisory, CloudRisk and TradeHeader
- Manuel and Dan also confirmed that improvements have been made to the Python Code Generator
- These include the ability to now support functions in the generated code
- Brian asked what versions would be available in pip? 
  - Dan confirmed this would be Production Major and Minor versions
  - Dev releases are generally not made available through pip

## Action Items
- None

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by ftadvisory** [comment]
Dan Schwartz/FT Advisory

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by martincwwalker** [comment]
Martin Walker / FIS

**Comment by fgignoux** [comment]
Frederic GIGNOUX / SG

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
