### ISSUE TITLE
CDM Steering Working Group - October 16th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3166]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
October 16th, 2024  - 10am ET / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/3117
- [x] Asset Refactoring Taskforce update @lolabeis/@Oblongs [5 min] leading to....
- [x] CDM 6.0 update @lolabeis/@Oblongs [5 min]
- [x] Serialisation update @chrisisla [5 min]] 
- [x] Updates from X-TA meeting 7th October @dshoneisda/Georgina Jarratt/@ADaleISLA  [10 min]
   - [x] TOM
   - [x] Funding (high level)
   - [x] Next steps
- [x] Proposals re: CRWG/DPBE scope & coverage @lolabeis [10 min]
- [x] AOB

## Minutes

- Meeting Admin was completed
- Previous minutes approved

**ART**
- @Oblongs confirmed the third tranche of updates for the ART efforts have been made and are in 6-dev already for firms to assess and experiment with
- It was noted that some further minor enhancements had been proposed and are being worked on with a view to also getting submitted prior to 6-prod release
- @dschwartznyc asked for a summary of changes made in the three releases, @Oblongs will send him the relevant release notes.

**6.0 Prod**
- @lolabeis confirmed time frame is now prior to the end of the year- estimated end of Nov- to incorporate the minor changes from ART but also to incorporate efforts to minimise downstream impact to existing users including DRR. 6.0 represents many major changes from 5.0
- It was confirmed that full and comprehensive changes, including removed/deprecated code, from 5.x--> 6.0 will be compiled for the release, just as they were for CDM 5.0

**Serialisation**
- @chrisisla confirmed that meetings have begun on this topic with a dedicated group of maintainers and TAWG attendees, covering the proposal from last November ratified by the SWG
- This group will present a design at the next TAWG; any refinements will then be presented as a whole to the SWG in November
- It was noted that there will likely be backward incompatible changes and thus consideration will have to be given as to when to schedule next year's major release, in accordance with the release guidelines and governance approved earlier this year

**X-TA updates**
- @dshoneisda informed the group that there was a meeting between ISDA, ISLA, ICMA and FINOS on 7th October in which a TOM for end 2025 was agreed. Additionally there will be funding for centralised resources (Release Manager, Doc Writer, Release Engineer- pending further assesment) as well as a pot to draw down on for TAWG initiatives as agreed by the SWG
- There is a follow up meeting scheduled 18th October to agree some of the mechanics of that last pool, as well as further strategy around adoption
- @dschwartznyc asked whether success criteria for 2025 had been set out, @dshoneisda said it was hoped that would emerge from strategy discussion on 18th, but agreed it was something to be aimed for.

**CRWG/DPBE scope**
- @lolabeis observed these two groups have been operating in a relatively interchangeable way with different levels of engagement at each
- @dshoneisda admitted this is due to a vacuum of topics for the CRWG during the period there has been no release manager, which will hopefully be resolved should the contracting of a Release Manager get across the line. The CRWG should be used to discuss and push on release content/approval, as well as a source of X-domain modelling discussion. DPBE should be used to discuss Derivatives products and business events
- @dshoneisda  to send out to the community a recap on the purposes of each WG, scope, overlap and encourage signing up for the CRWG should people not currently be engaged

**AOB**
- It was requested we review 2025 roadmap at next SWG with planned releases and content
- DShone noted there were no formal governance in place to dictate frequency of rotation of the Chair or indeed any process for facilitating that. In the spirit of democracy it was proposed that nominees for Chair from January are made to the SWG before November's SWG, with voting to then occur at December's SWG.  The form for nominations by 11th November 2024 is here: https://github.com/finos/common-domain-model/issues/3187

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by brianlynn2** [comment]
Brian Lynn / GEM for ISDA

**Comment by DIVA291265** [comment]
Daniel Ivanier / Fragmos Chain

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by dschwartznyc** [comment]
Dan Schwartz/FT Advisory

**Comment by ADaleISLA** [comment]
Adrian Dale/ISLA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
