### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - October 23rd, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3168]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: Lyteck Lynhiavu, ISDA

October 23rd, 2024 - 11:30 am EST / 4:30 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes 
   - [x] https://github.com/finos/common-domain-model/issues/3164
- [x] https://github.com/finos/common-domain-model/issues/3194 (Manuel / TH)
- [x] Update on "workflow, CDM event model, support for business processes" discussion (Lyteck)
- [x] https://github.com/finos/common-domain-model/issues/3059 (JB / Fragmos)
- [x] Asset Refactoring update (Lionel / Regnosys)
  - Payout as a Choice – Contribution to review.
  - Fix Security Lending defects – design to review.
  - Refactor FloatingRateIndex – design to review.
  - Improve Product Qualification to include ETDs more comprehensively – design to review.
  - Price on Payout – design to review
  - Ensure Corporate Action includes Index – design to review.
  - Refactor AssetCriteria (as used in Eligible Collateral) to align with Asset – to be presented to Collateral WG.
  - [ARTForce DPBE 23Oct24.pdf](https://github.com/user-attachments/files/17479633/ARTForce.DPBE.23Oct24.pdf)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Past minutes approved
- [ ] https://github.com/finos/common-domain-model/issues/3194 (Manuel / TH)
   - Manuel presented the proposal and firms were generally in favor. Agreed to aim for CDM 6 (rather than 5.x which could present namespace/compatibility issues). TH will do a review of the code at the next CRWG.
- [ ] **Update on "workflow, CDM event model, support for business processes" discussion** (Lyteck)
   - We plan to organize a workshop in 2025 Q1 (ETA mid-late January): e.g. 2 half-days for a deep dive, giving the opportunity for firms to discuss specific business use cases and challenge the existing model. Details are being worked out and we will keep the WG updated.
   - Meanwhile, we are gathering a "laundry list of issues" and asking Firms to add their "workflow/business event model" issues to #3170 (and indicate the urgency, if any).
- [ ] https://github.com/finos/common-domain-model/issues/3059 (JB / Fragmos)
  - JB presented the proposal in detail. Feedback was mixed (TH was in general agreement with the direction, BNP expressed some concerns). The proposal is not ready to be contributed yet and will need additional passes. JB is also waiting for the final version of the ART to finalize his model.
  - Firms are invited to review the proposal offline. JB could possibly share the workspace if people are interested and have ad-hoc meetings.
- [ ] **Asset Refactoring Work**: Lionel only had a few minutes left in the meeting to present the work. There is additional refactoring work dubbed "Phase 3 Plus" All members are invited to review the deck [ARTForce DPBE 23Oct24.pdf](https://github.com/user-attachments/files/17479633/ARTForce.DPBE.23Oct24.pdf). This was also presented in detail at the CRWG https://github.com/finos/common-domain-model/issues/3167
- AOB - None

## Action
- Asset Refactoring: All the review the deck and latest model in CDM Dev 6.0.0-dev.75
- Event Model - Create and investigate a "laundry list" of potential issues with the current processes. Firms can add items to issue https://github.com/finos/common-domain-model/issues/3170
- 

### Zoom info

Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607
Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by Oblongs** [comment]
PR's reviewed in this meeting: https://github.com/finos/common-domain-model/pull/3188 https://github.com/finos/common-domain-model/pull/3189 https://github.com/finos/common-domain-model/pull/3190

**Comment by Oblongs** [comment]
PR's reviewed in this meeting: https://github.com/finos/common-domain-model/pull/3178

**Comment by JBZ-Fragmos** [comment]
@Oblongs 
as regards **Asset Refactoring** (ARTForce) : agree with most proposals, including having fixedPrice in settlementPayout

suggest to consider additional changes below : 
- not only fixedPrice in settlementPayout deserves to benefit from [metadata reference] : actually **all kinds** of prices used as core component of given payout should have the same e.g. **strike** in optionPayout, **volatilityStrike** and **varianceStrike** and **correlationStrike**
- include **observationTerms** in PayoutBasis (as an optional attribute)
- same for **valuationTerms** (to be created by renaming and refactoring from the existing type PerformanceValuationDate)
- improve representation of **physical transfer** that is to say refactor current **Transfer** primitive instruction
     - by **(a)** **increasing current cardinality of Quantity** in Transfer from (0..1) up to (0..2) with a condition to ensure ony 1 among these 2 can have unit.currency, optional for representing the **nominal amount** of the quantity being delivered, and the other shall be compulosry to exist with any other type than "money" thus corresponding to **physical units** being delivered e.g. capacityUnit or whetherUnit or financialUnit (all in all this means that if Quantity count = 1, then unit.currency is absent, else unit.currency count = 1)
     - also add **(b)** **Price** attribute (optional with card 0..1) that is to permit representing the price at which the delivery takes place (and implementors might have rules to check for instance that physical Quantity x Price = nominal Quantity, etc.)
