### ISSUE TITLE
CDM Collateral Working Group - October 29th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3169]
# CDM Collateral Working Group Minutes 
Meeting Host: Vernon Alden Smith, ISDA

October 29th, 2024 - 10 am EST / 2 pm GMT

## Untracked attendees
- Claire Rodman, XP

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
   - [x] https://github.com/finos/common-domain-model/issues/3121
- [x] **CDM Collateral WG Meeting Material 29th Oct 2024** [ISDA Common Domain Model - Collateral WG 29th October 2024.pdf](https://github.com/user-attachments/files/17545280/ISDA.Common.Domain.Model.-.Collateral.WG.29th.October.2024.pdf)
- [x] **AGENDA 1** Summary of CDM collateral start up guide workshop 23/24 September
- [x] **AGENDA 2** Transforming Legacy CSAs into CDM with AI
- [x] **AGENDA 3** Explore AND/OR Eligibility rules in the CDM
- [x] **AGENDA 4** CDM Asset refactoring – potential impact to Eligible Collateral Criteria Asset identity 
- [x] AOB, Q&A & Adjourn (5mins)

### 2. Workshop Recap and Future Sessions
- **Overview**: Reviewed the recent workshop, with plans to schedule additional sessions in the future. Members were invited to express interest in participation.
- **Next Steps**: Dates for upcoming workshops will be circulated to the group.

###  3. Asset Refactoring and Eligibility Rules
- **Eligible Collateral Structure**: Discussion centered on ensuring clarity in the model structure when specifying eligible collateral schedules. Agreed on the need for clearer guidance within the model to avoid confusion, particularly around asset identification.
- **Enumeration of Indices**: Chris asked whether indices should be an enumerated list within the model. Lionel and others highlighted that while feasible, an enumerated list could be cumbersome and would require frequent updates across working groups. Lionel noted that the metadata scheme could allow implementers to map data to external sources as needed.
- **Metadata Schema Clarification**: The group emphasized that the current metadata schema allows implementers to map values to external data sources, and firms can choose to implement enumerated lists internally if desired.

###  4. Digital and Tokenized Asset Categorization
- **Clarification of Terms**: Lionel gave definitions to differentiate between digital assets and tokenized assets. Digital assets, such as Bitcoin, exist solely in digital form, whereas tokenized assets represent an existing asset on a digital platform. Lionel mentioned that a member firm had asked about handling tokenized assets separately.
- **Guidance for Implementers**: The team discussed possible adjustments to make identification of cash assets more apparent within the model. It was suggested that adding conditional language in the model’s descriptions could help guide implementers in structuring eligible collateral schedules.

###  5. Next Steps and Timeline
- **Immediate Actions**: Lionel will draft and circulate potential conditions and documentation enhancements to clarify the model's guidance on asset structuring.
- **Timeline for Changes**: Any agreed model updates will be presented in the next meeting, with an aim for integration by the November release.
- **AI Demonstration**: The team anticipates a demonstration by David Lee on AI-related work in the upcoming November meeting.

## Short Meeting Summary & Actions-
- [ ] Action 1 
Collateral Start up Guide Workshop
With reference to agenda item No 1 detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) pages 3 - 4. 
After Vernon Alden-Smith gave an overview of the in person collateral start up guide workshop that took place in London 23/24 September, it was suggested that the event will run again in 2025, expected to be in New York March 2025 and London H2 2025. Please notify your interest to both [valdensmith@isda.org](mailto:valdensmith@isda.org) and Chris.Rayner@islaemea.org
- [ ] Action 2 
Transforming Legacy CSAs into CDM with AI
Due to the absence of the presenter for agenda item No2 detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) pages 5-10. This item will be presented at the next WG meeting scheduled for November 26th 2024. 
- [x] Action 3
Explore AND/OR Eligibility rules in the CDM
With reference to agenda item No 3 detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) pages 11- 12. 
Lionel Smith Gordon (Regnosys) highlighted requirements for CDM to better represent AND/ OR logic for Eligible Collateral Specification. Examples were shown to the working group members and they were asked if they would support the additional build to the CDM to accommodate. There was a clear consensus to move forward. Therefore model enhancements will be prepared for review, expected to be in time to be shared with the working members at the next CDM Collateral WG. 
It was also discussed that any model changes in this area will add more complexity to the model. Therefore once changes have been made there would be a requirement to add sufficient clarity on how the model would be used correctly, including clear descriptions within the code/conditions as well as updated commentary in the related user documentation.
- [x] Action 4
CDM Asset refactoring potential impact to Eligible Collateral Criteria Asset identity 
With reference to agenda item No 4 detailed in the meeting material slides (ISDA Common Domain Model- Collateral WG) pages 13- 17. 
Lionel Smith Gordon (Regnosys) highlighted how the Asset Criteria can be aligned with the Asset product CDM model to give a broader means of identify collateral using the Eligible Collateral Criteria. However it was discussed that this may offer duplications in identify of certain types of assets. Once the updates have been made in CDM version 6, we will explore ways to ensure the user applies the correct choices for defining assets when using the Eligible Collateral Criteria.

### Zoom info

Join Zoom Meeting
https://zoom.us/j/96084284579?pwd=QTJ3bTBrMURkWXA1S0owa1djaEVIUT09
Meeting ID: 960 8428 4579
Passcode: 477790

Find your local number: https://zoom.us/u/aoBkYnW9l

**Comment by dharm-kapadia** [comment]
Dharm Kapadia (EquiLend)

**Comment by valdensmith** [comment]
Vernon ISDA

**Comment by AmyCaruso** [comment]
Amy Caruso (ISDA)

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by paulpkelly** [comment]
Paul Kelly (Logical Construct)

**Comment by paulhands** [comment]
Paul Hands (Parallel 51 / DRS)

**Comment by MalwinaAzemi** [comment]
Malwina Wasowska-Azemi / CloudMargin

**Comment by adamulman** [comment]
Adam Ulman - SmartStream

**Comment by CarltonOrola** [comment]
Carlton Orola / EquiLend

**Comment by turntablistic** [comment]
Richard Barton / LSEG

**Comment by PNR4** [comment]
Phil Ross - J.P. Morgan

**Comment by mani-otc** [comment]
Mani Pillai / otcDigital

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by VRao85** [comment]
Vinit Rao / Nasdaq-Adenza
